




// Generated by PIDL compiler.
// Do not modify this file, but modify the source .pidl file.

using System;
using System.Net;

namespace ServerToClient
{
	internal class Proxy:Nettention.Proud.RmiProxy
	{
public bool ResponseLoginEvent(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, bool bIsSuccess, int ErrorType)
{
	using (Nettention.Proud.FreeListPopper<Nettention.Proud.Message> freeList = new Nettention.Proud.FreeListPopper<Nettention.Proud.Message>())
		{
		Nettention.Proud.Message __msg=freeList.GetObject();
		__msg.Clear();
		__msg.SimplePacketMode = core.IsSimplePacketMode();
		Nettention.Proud.RmiID __msgid= Common.ResponseLoginEvent;
		__msg.Write(__msgid);
		Nettention.Proud.Marshaler.Write(__msg, bIsSuccess);
		Nettention.Proud.Marshaler.Write(__msg, ErrorType);
		
	Nettention.Proud.HostID[] __list = new Nettention.Proud.HostID[1];
	__list[0] = remote;
		
	return RmiSend(__list,rmiContext,__msg,
		RmiName_ResponseLoginEvent, Common.ResponseLoginEvent);
        }
}

public bool ResponseLoginEvent(Nettention.Proud.HostID[] remotes,Nettention.Proud.RmiContext rmiContext, bool bIsSuccess, int ErrorType)
{
	using (Nettention.Proud.FreeListPopper<Nettention.Proud.Message> freeList = new Nettention.Proud.FreeListPopper<Nettention.Proud.Message>())
{
Nettention.Proud.Message __msg=freeList.GetObject();
__msg.Clear();
__msg.SimplePacketMode = core.IsSimplePacketMode();
Nettention.Proud.RmiID __msgid= Common.ResponseLoginEvent;
__msg.Write(__msgid);
Nettention.Proud.Marshaler.Write(__msg, bIsSuccess);
Nettention.Proud.Marshaler.Write(__msg, ErrorType);
		
	return RmiSend(remotes,rmiContext,__msg,
		RmiName_ResponseLoginEvent, Common.ResponseLoginEvent);
        }
}
public bool ResponseCheckNickname(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, int clientId, bool bIsAble)
{
	using (Nettention.Proud.FreeListPopper<Nettention.Proud.Message> freeList = new Nettention.Proud.FreeListPopper<Nettention.Proud.Message>())
		{
		Nettention.Proud.Message __msg=freeList.GetObject();
		__msg.Clear();
		__msg.SimplePacketMode = core.IsSimplePacketMode();
		Nettention.Proud.RmiID __msgid= Common.ResponseCheckNickname;
		__msg.Write(__msgid);
		Nettention.Proud.Marshaler.Write(__msg, clientId);
		Nettention.Proud.Marshaler.Write(__msg, bIsAble);
		
	Nettention.Proud.HostID[] __list = new Nettention.Proud.HostID[1];
	__list[0] = remote;
		
	return RmiSend(__list,rmiContext,__msg,
		RmiName_ResponseCheckNickname, Common.ResponseCheckNickname);
        }
}

public bool ResponseCheckNickname(Nettention.Proud.HostID[] remotes,Nettention.Proud.RmiContext rmiContext, int clientId, bool bIsAble)
{
	using (Nettention.Proud.FreeListPopper<Nettention.Proud.Message> freeList = new Nettention.Proud.FreeListPopper<Nettention.Proud.Message>())
{
Nettention.Proud.Message __msg=freeList.GetObject();
__msg.Clear();
__msg.SimplePacketMode = core.IsSimplePacketMode();
Nettention.Proud.RmiID __msgid= Common.ResponseCheckNickname;
__msg.Write(__msgid);
Nettention.Proud.Marshaler.Write(__msg, clientId);
Nettention.Proud.Marshaler.Write(__msg, bIsAble);
		
	return RmiSend(remotes,rmiContext,__msg,
		RmiName_ResponseCheckNickname, Common.ResponseCheckNickname);
        }
}
public bool OnPlayerJoined(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, int clientId, string szNickName, float PosX, float PosY, float PosZ)
{
	using (Nettention.Proud.FreeListPopper<Nettention.Proud.Message> freeList = new Nettention.Proud.FreeListPopper<Nettention.Proud.Message>())
		{
		Nettention.Proud.Message __msg=freeList.GetObject();
		__msg.Clear();
		__msg.SimplePacketMode = core.IsSimplePacketMode();
		Nettention.Proud.RmiID __msgid= Common.OnPlayerJoined;
		__msg.Write(__msgid);
		Nettention.Proud.Marshaler.Write(__msg, clientId);
		Nettention.Proud.Marshaler.Write(__msg, szNickName);
		Nettention.Proud.Marshaler.Write(__msg, PosX);
		Nettention.Proud.Marshaler.Write(__msg, PosY);
		Nettention.Proud.Marshaler.Write(__msg, PosZ);
		
	Nettention.Proud.HostID[] __list = new Nettention.Proud.HostID[1];
	__list[0] = remote;
		
	return RmiSend(__list,rmiContext,__msg,
		RmiName_OnPlayerJoined, Common.OnPlayerJoined);
        }
}

public bool OnPlayerJoined(Nettention.Proud.HostID[] remotes,Nettention.Proud.RmiContext rmiContext, int clientId, string szNickName, float PosX, float PosY, float PosZ)
{
	using (Nettention.Proud.FreeListPopper<Nettention.Proud.Message> freeList = new Nettention.Proud.FreeListPopper<Nettention.Proud.Message>())
{
Nettention.Proud.Message __msg=freeList.GetObject();
__msg.Clear();
__msg.SimplePacketMode = core.IsSimplePacketMode();
Nettention.Proud.RmiID __msgid= Common.OnPlayerJoined;
__msg.Write(__msgid);
Nettention.Proud.Marshaler.Write(__msg, clientId);
Nettention.Proud.Marshaler.Write(__msg, szNickName);
Nettention.Proud.Marshaler.Write(__msg, PosX);
Nettention.Proud.Marshaler.Write(__msg, PosY);
Nettention.Proud.Marshaler.Write(__msg, PosZ);
		
	return RmiSend(remotes,rmiContext,__msg,
		RmiName_OnPlayerJoined, Common.OnPlayerJoined);
        }
}
public bool OnOtherPlayerUpdated(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, int ClientID, string NickName, float PosX, float PosY, float PosZ)
{
	using (Nettention.Proud.FreeListPopper<Nettention.Proud.Message> freeList = new Nettention.Proud.FreeListPopper<Nettention.Proud.Message>())
		{
		Nettention.Proud.Message __msg=freeList.GetObject();
		__msg.Clear();
		__msg.SimplePacketMode = core.IsSimplePacketMode();
		Nettention.Proud.RmiID __msgid= Common.OnOtherPlayerUpdated;
		__msg.Write(__msgid);
		Nettention.Proud.Marshaler.Write(__msg, ClientID);
		Nettention.Proud.Marshaler.Write(__msg, NickName);
		Nettention.Proud.Marshaler.Write(__msg, PosX);
		Nettention.Proud.Marshaler.Write(__msg, PosY);
		Nettention.Proud.Marshaler.Write(__msg, PosZ);
		
	Nettention.Proud.HostID[] __list = new Nettention.Proud.HostID[1];
	__list[0] = remote;
		
	return RmiSend(__list,rmiContext,__msg,
		RmiName_OnOtherPlayerUpdated, Common.OnOtherPlayerUpdated);
        }
}

public bool OnOtherPlayerUpdated(Nettention.Proud.HostID[] remotes,Nettention.Proud.RmiContext rmiContext, int ClientID, string NickName, float PosX, float PosY, float PosZ)
{
	using (Nettention.Proud.FreeListPopper<Nettention.Proud.Message> freeList = new Nettention.Proud.FreeListPopper<Nettention.Proud.Message>())
{
Nettention.Proud.Message __msg=freeList.GetObject();
__msg.Clear();
__msg.SimplePacketMode = core.IsSimplePacketMode();
Nettention.Proud.RmiID __msgid= Common.OnOtherPlayerUpdated;
__msg.Write(__msgid);
Nettention.Proud.Marshaler.Write(__msg, ClientID);
Nettention.Proud.Marshaler.Write(__msg, NickName);
Nettention.Proud.Marshaler.Write(__msg, PosX);
Nettention.Proud.Marshaler.Write(__msg, PosY);
Nettention.Proud.Marshaler.Write(__msg, PosZ);
		
	return RmiSend(remotes,rmiContext,__msg,
		RmiName_OnOtherPlayerUpdated, Common.OnOtherPlayerUpdated);
        }
}
public bool OnOtherPlayerAnimUpdated(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, int ClientID, int AnimState, int AnimTime)
{
	using (Nettention.Proud.FreeListPopper<Nettention.Proud.Message> freeList = new Nettention.Proud.FreeListPopper<Nettention.Proud.Message>())
		{
		Nettention.Proud.Message __msg=freeList.GetObject();
		__msg.Clear();
		__msg.SimplePacketMode = core.IsSimplePacketMode();
		Nettention.Proud.RmiID __msgid= Common.OnOtherPlayerAnimUpdated;
		__msg.Write(__msgid);
		Nettention.Proud.Marshaler.Write(__msg, ClientID);
		Nettention.Proud.Marshaler.Write(__msg, AnimState);
		Nettention.Proud.Marshaler.Write(__msg, AnimTime);
		
	Nettention.Proud.HostID[] __list = new Nettention.Proud.HostID[1];
	__list[0] = remote;
		
	return RmiSend(__list,rmiContext,__msg,
		RmiName_OnOtherPlayerAnimUpdated, Common.OnOtherPlayerAnimUpdated);
        }
}

public bool OnOtherPlayerAnimUpdated(Nettention.Proud.HostID[] remotes,Nettention.Proud.RmiContext rmiContext, int ClientID, int AnimState, int AnimTime)
{
	using (Nettention.Proud.FreeListPopper<Nettention.Proud.Message> freeList = new Nettention.Proud.FreeListPopper<Nettention.Proud.Message>())
{
Nettention.Proud.Message __msg=freeList.GetObject();
__msg.Clear();
__msg.SimplePacketMode = core.IsSimplePacketMode();
Nettention.Proud.RmiID __msgid= Common.OnOtherPlayerAnimUpdated;
__msg.Write(__msgid);
Nettention.Proud.Marshaler.Write(__msg, ClientID);
Nettention.Proud.Marshaler.Write(__msg, AnimState);
Nettention.Proud.Marshaler.Write(__msg, AnimTime);
		
	return RmiSend(remotes,rmiContext,__msg,
		RmiName_OnOtherPlayerAnimUpdated, Common.OnOtherPlayerAnimUpdated);
        }
}
public bool SpawnObjectEvent(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, string Key, int templetedID, float px, float py, float pz)
{
	using (Nettention.Proud.FreeListPopper<Nettention.Proud.Message> freeList = new Nettention.Proud.FreeListPopper<Nettention.Proud.Message>())
		{
		Nettention.Proud.Message __msg=freeList.GetObject();
		__msg.Clear();
		__msg.SimplePacketMode = core.IsSimplePacketMode();
		Nettention.Proud.RmiID __msgid= Common.SpawnObjectEvent;
		__msg.Write(__msgid);
		Nettention.Proud.Marshaler.Write(__msg, Key);
		Nettention.Proud.Marshaler.Write(__msg, templetedID);
		Nettention.Proud.Marshaler.Write(__msg, px);
		Nettention.Proud.Marshaler.Write(__msg, py);
		Nettention.Proud.Marshaler.Write(__msg, pz);
		
	Nettention.Proud.HostID[] __list = new Nettention.Proud.HostID[1];
	__list[0] = remote;
		
	return RmiSend(__list,rmiContext,__msg,
		RmiName_SpawnObjectEvent, Common.SpawnObjectEvent);
        }
}

public bool SpawnObjectEvent(Nettention.Proud.HostID[] remotes,Nettention.Proud.RmiContext rmiContext, string Key, int templetedID, float px, float py, float pz)
{
	using (Nettention.Proud.FreeListPopper<Nettention.Proud.Message> freeList = new Nettention.Proud.FreeListPopper<Nettention.Proud.Message>())
{
Nettention.Proud.Message __msg=freeList.GetObject();
__msg.Clear();
__msg.SimplePacketMode = core.IsSimplePacketMode();
Nettention.Proud.RmiID __msgid= Common.SpawnObjectEvent;
__msg.Write(__msgid);
Nettention.Proud.Marshaler.Write(__msg, Key);
Nettention.Proud.Marshaler.Write(__msg, templetedID);
Nettention.Proud.Marshaler.Write(__msg, px);
Nettention.Proud.Marshaler.Write(__msg, py);
Nettention.Proud.Marshaler.Write(__msg, pz);
		
	return RmiSend(remotes,rmiContext,__msg,
		RmiName_SpawnObjectEvent, Common.SpawnObjectEvent);
        }
}
public bool OnOtherActorUpdated(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, int templeteID, float PosX, float PosY, float PosZ)
{
	using (Nettention.Proud.FreeListPopper<Nettention.Proud.Message> freeList = new Nettention.Proud.FreeListPopper<Nettention.Proud.Message>())
		{
		Nettention.Proud.Message __msg=freeList.GetObject();
		__msg.Clear();
		__msg.SimplePacketMode = core.IsSimplePacketMode();
		Nettention.Proud.RmiID __msgid= Common.OnOtherActorUpdated;
		__msg.Write(__msgid);
		Nettention.Proud.Marshaler.Write(__msg, templeteID);
		Nettention.Proud.Marshaler.Write(__msg, PosX);
		Nettention.Proud.Marshaler.Write(__msg, PosY);
		Nettention.Proud.Marshaler.Write(__msg, PosZ);
		
	Nettention.Proud.HostID[] __list = new Nettention.Proud.HostID[1];
	__list[0] = remote;
		
	return RmiSend(__list,rmiContext,__msg,
		RmiName_OnOtherActorUpdated, Common.OnOtherActorUpdated);
        }
}

public bool OnOtherActorUpdated(Nettention.Proud.HostID[] remotes,Nettention.Proud.RmiContext rmiContext, int templeteID, float PosX, float PosY, float PosZ)
{
	using (Nettention.Proud.FreeListPopper<Nettention.Proud.Message> freeList = new Nettention.Proud.FreeListPopper<Nettention.Proud.Message>())
{
Nettention.Proud.Message __msg=freeList.GetObject();
__msg.Clear();
__msg.SimplePacketMode = core.IsSimplePacketMode();
Nettention.Proud.RmiID __msgid= Common.OnOtherActorUpdated;
__msg.Write(__msgid);
Nettention.Proud.Marshaler.Write(__msg, templeteID);
Nettention.Proud.Marshaler.Write(__msg, PosX);
Nettention.Proud.Marshaler.Write(__msg, PosY);
Nettention.Proud.Marshaler.Write(__msg, PosZ);
		
	return RmiSend(remotes,rmiContext,__msg,
		RmiName_OnOtherActorUpdated, Common.OnOtherActorUpdated);
        }
}
public bool OnOtherActorAnimUpdated(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, int templeteID, int AnimState, int AnimTime)
{
	using (Nettention.Proud.FreeListPopper<Nettention.Proud.Message> freeList = new Nettention.Proud.FreeListPopper<Nettention.Proud.Message>())
		{
		Nettention.Proud.Message __msg=freeList.GetObject();
		__msg.Clear();
		__msg.SimplePacketMode = core.IsSimplePacketMode();
		Nettention.Proud.RmiID __msgid= Common.OnOtherActorAnimUpdated;
		__msg.Write(__msgid);
		Nettention.Proud.Marshaler.Write(__msg, templeteID);
		Nettention.Proud.Marshaler.Write(__msg, AnimState);
		Nettention.Proud.Marshaler.Write(__msg, AnimTime);
		
	Nettention.Proud.HostID[] __list = new Nettention.Proud.HostID[1];
	__list[0] = remote;
		
	return RmiSend(__list,rmiContext,__msg,
		RmiName_OnOtherActorAnimUpdated, Common.OnOtherActorAnimUpdated);
        }
}

public bool OnOtherActorAnimUpdated(Nettention.Proud.HostID[] remotes,Nettention.Proud.RmiContext rmiContext, int templeteID, int AnimState, int AnimTime)
{
	using (Nettention.Proud.FreeListPopper<Nettention.Proud.Message> freeList = new Nettention.Proud.FreeListPopper<Nettention.Proud.Message>())
{
Nettention.Proud.Message __msg=freeList.GetObject();
__msg.Clear();
__msg.SimplePacketMode = core.IsSimplePacketMode();
Nettention.Proud.RmiID __msgid= Common.OnOtherActorAnimUpdated;
__msg.Write(__msgid);
Nettention.Proud.Marshaler.Write(__msg, templeteID);
Nettention.Proud.Marshaler.Write(__msg, AnimState);
Nettention.Proud.Marshaler.Write(__msg, AnimTime);
		
	return RmiSend(remotes,rmiContext,__msg,
		RmiName_OnOtherActorAnimUpdated, Common.OnOtherActorAnimUpdated);
        }
}
public bool OnPositionUpdated(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, int clientId, float PosX, float PosY, float PosZ, float DirX, float DirY, float DirZ)
{
	using (Nettention.Proud.FreeListPopper<Nettention.Proud.Message> freeList = new Nettention.Proud.FreeListPopper<Nettention.Proud.Message>())
		{
		Nettention.Proud.Message __msg=freeList.GetObject();
		__msg.Clear();
		__msg.SimplePacketMode = core.IsSimplePacketMode();
		Nettention.Proud.RmiID __msgid= Common.OnPositionUpdated;
		__msg.Write(__msgid);
		Nettention.Proud.Marshaler.Write(__msg, clientId);
		Nettention.Proud.Marshaler.Write(__msg, PosX);
		Nettention.Proud.Marshaler.Write(__msg, PosY);
		Nettention.Proud.Marshaler.Write(__msg, PosZ);
		Nettention.Proud.Marshaler.Write(__msg, DirX);
		Nettention.Proud.Marshaler.Write(__msg, DirY);
		Nettention.Proud.Marshaler.Write(__msg, DirZ);
		
	Nettention.Proud.HostID[] __list = new Nettention.Proud.HostID[1];
	__list[0] = remote;
		
	return RmiSend(__list,rmiContext,__msg,
		RmiName_OnPositionUpdated, Common.OnPositionUpdated);
        }
}

public bool OnPositionUpdated(Nettention.Proud.HostID[] remotes,Nettention.Proud.RmiContext rmiContext, int clientId, float PosX, float PosY, float PosZ, float DirX, float DirY, float DirZ)
{
	using (Nettention.Proud.FreeListPopper<Nettention.Proud.Message> freeList = new Nettention.Proud.FreeListPopper<Nettention.Proud.Message>())
{
Nettention.Proud.Message __msg=freeList.GetObject();
__msg.Clear();
__msg.SimplePacketMode = core.IsSimplePacketMode();
Nettention.Proud.RmiID __msgid= Common.OnPositionUpdated;
__msg.Write(__msgid);
Nettention.Proud.Marshaler.Write(__msg, clientId);
Nettention.Proud.Marshaler.Write(__msg, PosX);
Nettention.Proud.Marshaler.Write(__msg, PosY);
Nettention.Proud.Marshaler.Write(__msg, PosZ);
Nettention.Proud.Marshaler.Write(__msg, DirX);
Nettention.Proud.Marshaler.Write(__msg, DirY);
Nettention.Proud.Marshaler.Write(__msg, DirZ);
		
	return RmiSend(remotes,rmiContext,__msg,
		RmiName_OnPositionUpdated, Common.OnPositionUpdated);
        }
}
public bool OnActorPositionUpdated(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, int templeteID, float PosX, float PosY, float PosZ, float DirX, float DirY, float DirZ)
{
	using (Nettention.Proud.FreeListPopper<Nettention.Proud.Message> freeList = new Nettention.Proud.FreeListPopper<Nettention.Proud.Message>())
		{
		Nettention.Proud.Message __msg=freeList.GetObject();
		__msg.Clear();
		__msg.SimplePacketMode = core.IsSimplePacketMode();
		Nettention.Proud.RmiID __msgid= Common.OnActorPositionUpdated;
		__msg.Write(__msgid);
		Nettention.Proud.Marshaler.Write(__msg, templeteID);
		Nettention.Proud.Marshaler.Write(__msg, PosX);
		Nettention.Proud.Marshaler.Write(__msg, PosY);
		Nettention.Proud.Marshaler.Write(__msg, PosZ);
		Nettention.Proud.Marshaler.Write(__msg, DirX);
		Nettention.Proud.Marshaler.Write(__msg, DirY);
		Nettention.Proud.Marshaler.Write(__msg, DirZ);
		
	Nettention.Proud.HostID[] __list = new Nettention.Proud.HostID[1];
	__list[0] = remote;
		
	return RmiSend(__list,rmiContext,__msg,
		RmiName_OnActorPositionUpdated, Common.OnActorPositionUpdated);
        }
}

public bool OnActorPositionUpdated(Nettention.Proud.HostID[] remotes,Nettention.Proud.RmiContext rmiContext, int templeteID, float PosX, float PosY, float PosZ, float DirX, float DirY, float DirZ)
{
	using (Nettention.Proud.FreeListPopper<Nettention.Proud.Message> freeList = new Nettention.Proud.FreeListPopper<Nettention.Proud.Message>())
{
Nettention.Proud.Message __msg=freeList.GetObject();
__msg.Clear();
__msg.SimplePacketMode = core.IsSimplePacketMode();
Nettention.Proud.RmiID __msgid= Common.OnActorPositionUpdated;
__msg.Write(__msgid);
Nettention.Proud.Marshaler.Write(__msg, templeteID);
Nettention.Proud.Marshaler.Write(__msg, PosX);
Nettention.Proud.Marshaler.Write(__msg, PosY);
Nettention.Proud.Marshaler.Write(__msg, PosZ);
Nettention.Proud.Marshaler.Write(__msg, DirX);
Nettention.Proud.Marshaler.Write(__msg, DirY);
Nettention.Proud.Marshaler.Write(__msg, DirZ);
		
	return RmiSend(remotes,rmiContext,__msg,
		RmiName_OnActorPositionUpdated, Common.OnActorPositionUpdated);
        }
}
public bool UpdateCharacterAnimState(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, int clientId, int AnimSate, float Time)
{
	using (Nettention.Proud.FreeListPopper<Nettention.Proud.Message> freeList = new Nettention.Proud.FreeListPopper<Nettention.Proud.Message>())
		{
		Nettention.Proud.Message __msg=freeList.GetObject();
		__msg.Clear();
		__msg.SimplePacketMode = core.IsSimplePacketMode();
		Nettention.Proud.RmiID __msgid= Common.UpdateCharacterAnimState;
		__msg.Write(__msgid);
		Nettention.Proud.Marshaler.Write(__msg, clientId);
		Nettention.Proud.Marshaler.Write(__msg, AnimSate);
		Nettention.Proud.Marshaler.Write(__msg, Time);
		
	Nettention.Proud.HostID[] __list = new Nettention.Proud.HostID[1];
	__list[0] = remote;
		
	return RmiSend(__list,rmiContext,__msg,
		RmiName_UpdateCharacterAnimState, Common.UpdateCharacterAnimState);
        }
}

public bool UpdateCharacterAnimState(Nettention.Proud.HostID[] remotes,Nettention.Proud.RmiContext rmiContext, int clientId, int AnimSate, float Time)
{
	using (Nettention.Proud.FreeListPopper<Nettention.Proud.Message> freeList = new Nettention.Proud.FreeListPopper<Nettention.Proud.Message>())
{
Nettention.Proud.Message __msg=freeList.GetObject();
__msg.Clear();
__msg.SimplePacketMode = core.IsSimplePacketMode();
Nettention.Proud.RmiID __msgid= Common.UpdateCharacterAnimState;
__msg.Write(__msgid);
Nettention.Proud.Marshaler.Write(__msg, clientId);
Nettention.Proud.Marshaler.Write(__msg, AnimSate);
Nettention.Proud.Marshaler.Write(__msg, Time);
		
	return RmiSend(remotes,rmiContext,__msg,
		RmiName_UpdateCharacterAnimState, Common.UpdateCharacterAnimState);
        }
}
public bool UpdateActorAnimState(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, int templeteID, int AnimSate, float Time)
{
	using (Nettention.Proud.FreeListPopper<Nettention.Proud.Message> freeList = new Nettention.Proud.FreeListPopper<Nettention.Proud.Message>())
		{
		Nettention.Proud.Message __msg=freeList.GetObject();
		__msg.Clear();
		__msg.SimplePacketMode = core.IsSimplePacketMode();
		Nettention.Proud.RmiID __msgid= Common.UpdateActorAnimState;
		__msg.Write(__msgid);
		Nettention.Proud.Marshaler.Write(__msg, templeteID);
		Nettention.Proud.Marshaler.Write(__msg, AnimSate);
		Nettention.Proud.Marshaler.Write(__msg, Time);
		
	Nettention.Proud.HostID[] __list = new Nettention.Proud.HostID[1];
	__list[0] = remote;
		
	return RmiSend(__list,rmiContext,__msg,
		RmiName_UpdateActorAnimState, Common.UpdateActorAnimState);
        }
}

public bool UpdateActorAnimState(Nettention.Proud.HostID[] remotes,Nettention.Proud.RmiContext rmiContext, int templeteID, int AnimSate, float Time)
{
	using (Nettention.Proud.FreeListPopper<Nettention.Proud.Message> freeList = new Nettention.Proud.FreeListPopper<Nettention.Proud.Message>())
{
Nettention.Proud.Message __msg=freeList.GetObject();
__msg.Clear();
__msg.SimplePacketMode = core.IsSimplePacketMode();
Nettention.Proud.RmiID __msgid= Common.UpdateActorAnimState;
__msg.Write(__msgid);
Nettention.Proud.Marshaler.Write(__msg, templeteID);
Nettention.Proud.Marshaler.Write(__msg, AnimSate);
Nettention.Proud.Marshaler.Write(__msg, Time);
		
	return RmiSend(remotes,rmiContext,__msg,
		RmiName_UpdateActorAnimState, Common.UpdateActorAnimState);
        }
}
public bool OnChat(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, int clientId, string message)
{
	using (Nettention.Proud.FreeListPopper<Nettention.Proud.Message> freeList = new Nettention.Proud.FreeListPopper<Nettention.Proud.Message>())
		{
		Nettention.Proud.Message __msg=freeList.GetObject();
		__msg.Clear();
		__msg.SimplePacketMode = core.IsSimplePacketMode();
		Nettention.Proud.RmiID __msgid= Common.OnChat;
		__msg.Write(__msgid);
		Nettention.Proud.Marshaler.Write(__msg, clientId);
		Nettention.Proud.Marshaler.Write(__msg, message);
		
	Nettention.Proud.HostID[] __list = new Nettention.Proud.HostID[1];
	__list[0] = remote;
		
	return RmiSend(__list,rmiContext,__msg,
		RmiName_OnChat, Common.OnChat);
        }
}

public bool OnChat(Nettention.Proud.HostID[] remotes,Nettention.Proud.RmiContext rmiContext, int clientId, string message)
{
	using (Nettention.Proud.FreeListPopper<Nettention.Proud.Message> freeList = new Nettention.Proud.FreeListPopper<Nettention.Proud.Message>())
{
Nettention.Proud.Message __msg=freeList.GetObject();
__msg.Clear();
__msg.SimplePacketMode = core.IsSimplePacketMode();
Nettention.Proud.RmiID __msgid= Common.OnChat;
__msg.Write(__msgid);
Nettention.Proud.Marshaler.Write(__msg, clientId);
Nettention.Proud.Marshaler.Write(__msg, message);
		
	return RmiSend(remotes,rmiContext,__msg,
		RmiName_OnChat, Common.OnChat);
        }
}
	
		#if USE_RMI_NAME_STRING
// RMI name declaration.
// It is the unique pointer that indicates RMI name such as RMI profiler.
public const string RmiName_ResponseLoginEvent="ResponseLoginEvent";
public const string RmiName_ResponseCheckNickname="ResponseCheckNickname";
public const string RmiName_OnPlayerJoined="OnPlayerJoined";
public const string RmiName_OnOtherPlayerUpdated="OnOtherPlayerUpdated";
public const string RmiName_OnOtherPlayerAnimUpdated="OnOtherPlayerAnimUpdated";
public const string RmiName_SpawnObjectEvent="SpawnObjectEvent";
public const string RmiName_OnOtherActorUpdated="OnOtherActorUpdated";
public const string RmiName_OnOtherActorAnimUpdated="OnOtherActorAnimUpdated";
public const string RmiName_OnPositionUpdated="OnPositionUpdated";
public const string RmiName_OnActorPositionUpdated="OnActorPositionUpdated";
public const string RmiName_UpdateCharacterAnimState="UpdateCharacterAnimState";
public const string RmiName_UpdateActorAnimState="UpdateActorAnimState";
public const string RmiName_OnChat="OnChat";
       
public const string RmiName_First = RmiName_ResponseLoginEvent;
		#else
// RMI name declaration.
// It is the unique pointer that indicates RMI name such as RMI profiler.
public const string RmiName_ResponseLoginEvent="";
public const string RmiName_ResponseCheckNickname="";
public const string RmiName_OnPlayerJoined="";
public const string RmiName_OnOtherPlayerUpdated="";
public const string RmiName_OnOtherPlayerAnimUpdated="";
public const string RmiName_SpawnObjectEvent="";
public const string RmiName_OnOtherActorUpdated="";
public const string RmiName_OnOtherActorAnimUpdated="";
public const string RmiName_OnPositionUpdated="";
public const string RmiName_OnActorPositionUpdated="";
public const string RmiName_UpdateCharacterAnimState="";
public const string RmiName_UpdateActorAnimState="";
public const string RmiName_OnChat="";
       
public const string RmiName_First = "";
		#endif

		public override Nettention.Proud.RmiID[] GetRmiIDList() { return Common.RmiIDList; } 
	}
}

