
// Generated by PIDL compiler.
// Do not modify this file, but modify the source .pidl file.


#include "ServerRmi_common.h"
namespace ServerToClient {


	::Proud::RmiID g_RmiIDList[] = {
               
		Rmi_ResponseLoginEvent,
               
		Rmi_ResponseCheckNickname,
               
		Rmi_OnPlayerJoined,
               
		Rmi_SpawnObjectEvent,
               
		Rmi_OtherPlayerTransformUpdated,
               
		Rmi_OnPlayerTransformUpdated,
               
		Rmi_OtherActorTransformUpdated,
               
		Rmi_ActorTransformUpdated,
               
		Rmi_UpdateCharacterAnimState,
               
		Rmi_OnOtherPlayerAnimUpdated,
               
		Rmi_UpdateActorAnimState,
               
		Rmi_OnOtherActorAnimUpdated,
               
		Rmi_Request_AddItem,
               
		Rmi_Request_RemoveItem,
               
		Rmi_Request_ItemData,
               
		Rmi_Request_AddGold,
               
		Rmi_OnChat,
	};

	int g_RmiIDListCount = 17;

}





