
// Generated by PIDL compiler.
// Do not modify this file, but modify the source .pidl file.


#include "ServerRmi_common.h"
namespace ServerToClient {


	::Proud::RmiID g_RmiIDList[] = {
               
		Rmi_OnPlayerJoined,
               
		Rmi_OnPositionUpdated,
               
		Rmi_OnChat,
	};

	int g_RmiIDListCount = 3;

}





