  






// Generated by PIDL compiler.
// Do not modify this file, but modify the source .pidl file.
   
#pragma once


#include "ServerRmi_common.h"

     
namespace ServerToClient {


	class Stub : public ::Proud::IRmiStub
	{
	public:
               
		virtual bool ResponseLoginEvent ( ::Proud::HostID, ::Proud::RmiContext& , const bool & , const int & )		{ 
			return false;
		} 

#define DECRMI_ServerToClient_ResponseLoginEvent bool ResponseLoginEvent ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const bool & bIsSuccess, const int & ErrorType) PN_OVERRIDE

#define DEFRMI_ServerToClient_ResponseLoginEvent(DerivedClass) bool DerivedClass::ResponseLoginEvent ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const bool & bIsSuccess, const int & ErrorType)
#define CALL_ServerToClient_ResponseLoginEvent ResponseLoginEvent ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const bool & bIsSuccess, const int & ErrorType)
#define PARAM_ServerToClient_ResponseLoginEvent ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const bool & bIsSuccess, const int & ErrorType)
               
		virtual bool ResponseCheckNickname ( ::Proud::HostID, ::Proud::RmiContext& , const int & , const bool & )		{ 
			return false;
		} 

#define DECRMI_ServerToClient_ResponseCheckNickname bool ResponseCheckNickname ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & clientId, const bool & bIsAble) PN_OVERRIDE

#define DEFRMI_ServerToClient_ResponseCheckNickname(DerivedClass) bool DerivedClass::ResponseCheckNickname ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & clientId, const bool & bIsAble)
#define CALL_ServerToClient_ResponseCheckNickname ResponseCheckNickname ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & clientId, const bool & bIsAble)
#define PARAM_ServerToClient_ResponseCheckNickname ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & clientId, const bool & bIsAble)
               
		virtual bool OnPlayerJoined ( ::Proud::HostID, ::Proud::RmiContext& , const int & , const string & , const float & , const float & , const float & )		{ 
			return false;
		} 

#define DECRMI_ServerToClient_OnPlayerJoined bool OnPlayerJoined ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & clientId, const string & szNickName, const float & PosX, const float & PosY, const float & PosZ) PN_OVERRIDE

#define DEFRMI_ServerToClient_OnPlayerJoined(DerivedClass) bool DerivedClass::OnPlayerJoined ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & clientId, const string & szNickName, const float & PosX, const float & PosY, const float & PosZ)
#define CALL_ServerToClient_OnPlayerJoined OnPlayerJoined ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & clientId, const string & szNickName, const float & PosX, const float & PosY, const float & PosZ)
#define PARAM_ServerToClient_OnPlayerJoined ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & clientId, const string & szNickName, const float & PosX, const float & PosY, const float & PosZ)
               
		virtual bool SpawnObjectEvent ( ::Proud::HostID, ::Proud::RmiContext& , const string & , const int & , const float & , const float & , const float & )		{ 
			return false;
		} 

#define DECRMI_ServerToClient_SpawnObjectEvent bool SpawnObjectEvent ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const string & Key, const int & templetedID, const float & px, const float & py, const float & pz) PN_OVERRIDE

#define DEFRMI_ServerToClient_SpawnObjectEvent(DerivedClass) bool DerivedClass::SpawnObjectEvent ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const string & Key, const int & templetedID, const float & px, const float & py, const float & pz)
#define CALL_ServerToClient_SpawnObjectEvent SpawnObjectEvent ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const string & Key, const int & templetedID, const float & px, const float & py, const float & pz)
#define PARAM_ServerToClient_SpawnObjectEvent ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const string & Key, const int & templetedID, const float & px, const float & py, const float & pz)
               
		virtual bool OtherPlayerTransformUpdated ( ::Proud::HostID, ::Proud::RmiContext& , const int & , const string & , const float & , const float & , const float & , const float & , const float & , const float & , const float & , const float & , const float & , const float & )		{ 
			return false;
		} 

#define DECRMI_ServerToClient_OtherPlayerTransformUpdated bool OtherPlayerTransformUpdated ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & ClientID, const string & NickName, const float & ScaleX, const float & ScaleY, const float & ScaleZ, const float & AngleX, const float & AngleY, const float & AngleZ, const float & AngleW, const float & PosX, const float & PosY, const float & PosZ) PN_OVERRIDE

#define DEFRMI_ServerToClient_OtherPlayerTransformUpdated(DerivedClass) bool DerivedClass::OtherPlayerTransformUpdated ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & ClientID, const string & NickName, const float & ScaleX, const float & ScaleY, const float & ScaleZ, const float & AngleX, const float & AngleY, const float & AngleZ, const float & AngleW, const float & PosX, const float & PosY, const float & PosZ)
#define CALL_ServerToClient_OtherPlayerTransformUpdated OtherPlayerTransformUpdated ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & ClientID, const string & NickName, const float & ScaleX, const float & ScaleY, const float & ScaleZ, const float & AngleX, const float & AngleY, const float & AngleZ, const float & AngleW, const float & PosX, const float & PosY, const float & PosZ)
#define PARAM_ServerToClient_OtherPlayerTransformUpdated ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & ClientID, const string & NickName, const float & ScaleX, const float & ScaleY, const float & ScaleZ, const float & AngleX, const float & AngleY, const float & AngleZ, const float & AngleW, const float & PosX, const float & PosY, const float & PosZ)
               
		virtual bool OnPlayerTransformUpdated ( ::Proud::HostID, ::Proud::RmiContext& , const int & , const float & , const float & , const float & , const float & , const float & , const float & , const float & , const float & , const float & , const float & )		{ 
			return false;
		} 

#define DECRMI_ServerToClient_OnPlayerTransformUpdated bool OnPlayerTransformUpdated ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & clientId, const float & ScaleX, const float & ScaleY, const float & ScaleZ, const float & AngleX, const float & AngleY, const float & AngleZ, const float & AngleW, const float & PosX, const float & PosY, const float & PosZ) PN_OVERRIDE

#define DEFRMI_ServerToClient_OnPlayerTransformUpdated(DerivedClass) bool DerivedClass::OnPlayerTransformUpdated ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & clientId, const float & ScaleX, const float & ScaleY, const float & ScaleZ, const float & AngleX, const float & AngleY, const float & AngleZ, const float & AngleW, const float & PosX, const float & PosY, const float & PosZ)
#define CALL_ServerToClient_OnPlayerTransformUpdated OnPlayerTransformUpdated ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & clientId, const float & ScaleX, const float & ScaleY, const float & ScaleZ, const float & AngleX, const float & AngleY, const float & AngleZ, const float & AngleW, const float & PosX, const float & PosY, const float & PosZ)
#define PARAM_ServerToClient_OnPlayerTransformUpdated ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & clientId, const float & ScaleX, const float & ScaleY, const float & ScaleZ, const float & AngleX, const float & AngleY, const float & AngleZ, const float & AngleW, const float & PosX, const float & PosY, const float & PosZ)
               
		virtual bool OtherActorTransformUpdated ( ::Proud::HostID, ::Proud::RmiContext& , const int & , const float & , const float & , const float & , const float & , const float & , const float & , const float & , const float & , const float & , const float & )		{ 
			return false;
		} 

#define DECRMI_ServerToClient_OtherActorTransformUpdated bool OtherActorTransformUpdated ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & templeteID, const float & ScaleX, const float & ScaleY, const float & ScaleZ, const float & AngleX, const float & AngleY, const float & AngleZ, const float & AngleW, const float & PosX, const float & PosY, const float & PosZ) PN_OVERRIDE

#define DEFRMI_ServerToClient_OtherActorTransformUpdated(DerivedClass) bool DerivedClass::OtherActorTransformUpdated ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & templeteID, const float & ScaleX, const float & ScaleY, const float & ScaleZ, const float & AngleX, const float & AngleY, const float & AngleZ, const float & AngleW, const float & PosX, const float & PosY, const float & PosZ)
#define CALL_ServerToClient_OtherActorTransformUpdated OtherActorTransformUpdated ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & templeteID, const float & ScaleX, const float & ScaleY, const float & ScaleZ, const float & AngleX, const float & AngleY, const float & AngleZ, const float & AngleW, const float & PosX, const float & PosY, const float & PosZ)
#define PARAM_ServerToClient_OtherActorTransformUpdated ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & templeteID, const float & ScaleX, const float & ScaleY, const float & ScaleZ, const float & AngleX, const float & AngleY, const float & AngleZ, const float & AngleW, const float & PosX, const float & PosY, const float & PosZ)
               
		virtual bool ActorTransformUpdated ( ::Proud::HostID, ::Proud::RmiContext& , const int & , const float & , const float & , const float & , const float & , const float & , const float & , const float & , const float & , const float & , const float & )		{ 
			return false;
		} 

#define DECRMI_ServerToClient_ActorTransformUpdated bool ActorTransformUpdated ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & templeteID, const float & ScaleX, const float & ScaleY, const float & ScaleZ, const float & AngleX, const float & AngleY, const float & AngleZ, const float & AngleW, const float & PosX, const float & PosY, const float & PosZ) PN_OVERRIDE

#define DEFRMI_ServerToClient_ActorTransformUpdated(DerivedClass) bool DerivedClass::ActorTransformUpdated ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & templeteID, const float & ScaleX, const float & ScaleY, const float & ScaleZ, const float & AngleX, const float & AngleY, const float & AngleZ, const float & AngleW, const float & PosX, const float & PosY, const float & PosZ)
#define CALL_ServerToClient_ActorTransformUpdated ActorTransformUpdated ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & templeteID, const float & ScaleX, const float & ScaleY, const float & ScaleZ, const float & AngleX, const float & AngleY, const float & AngleZ, const float & AngleW, const float & PosX, const float & PosY, const float & PosZ)
#define PARAM_ServerToClient_ActorTransformUpdated ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & templeteID, const float & ScaleX, const float & ScaleY, const float & ScaleZ, const float & AngleX, const float & AngleY, const float & AngleZ, const float & AngleW, const float & PosX, const float & PosY, const float & PosZ)
               
		virtual bool UpdateCharacterAnimState ( ::Proud::HostID, ::Proud::RmiContext& , const int & , const int & , const float & )		{ 
			return false;
		} 

#define DECRMI_ServerToClient_UpdateCharacterAnimState bool UpdateCharacterAnimState ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & clientId, const int & AnimSate, const float & Time) PN_OVERRIDE

#define DEFRMI_ServerToClient_UpdateCharacterAnimState(DerivedClass) bool DerivedClass::UpdateCharacterAnimState ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & clientId, const int & AnimSate, const float & Time)
#define CALL_ServerToClient_UpdateCharacterAnimState UpdateCharacterAnimState ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & clientId, const int & AnimSate, const float & Time)
#define PARAM_ServerToClient_UpdateCharacterAnimState ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & clientId, const int & AnimSate, const float & Time)
               
		virtual bool OnOtherPlayerAnimUpdated ( ::Proud::HostID, ::Proud::RmiContext& , const int & , const int & , const int & )		{ 
			return false;
		} 

#define DECRMI_ServerToClient_OnOtherPlayerAnimUpdated bool OnOtherPlayerAnimUpdated ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & ClientID, const int & AnimState, const int & AnimTime) PN_OVERRIDE

#define DEFRMI_ServerToClient_OnOtherPlayerAnimUpdated(DerivedClass) bool DerivedClass::OnOtherPlayerAnimUpdated ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & ClientID, const int & AnimState, const int & AnimTime)
#define CALL_ServerToClient_OnOtherPlayerAnimUpdated OnOtherPlayerAnimUpdated ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & ClientID, const int & AnimState, const int & AnimTime)
#define PARAM_ServerToClient_OnOtherPlayerAnimUpdated ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & ClientID, const int & AnimState, const int & AnimTime)
               
		virtual bool UpdateActorAnimState ( ::Proud::HostID, ::Proud::RmiContext& , const int & , const int & , const float & )		{ 
			return false;
		} 

#define DECRMI_ServerToClient_UpdateActorAnimState bool UpdateActorAnimState ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & templeteID, const int & AnimSate, const float & Time) PN_OVERRIDE

#define DEFRMI_ServerToClient_UpdateActorAnimState(DerivedClass) bool DerivedClass::UpdateActorAnimState ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & templeteID, const int & AnimSate, const float & Time)
#define CALL_ServerToClient_UpdateActorAnimState UpdateActorAnimState ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & templeteID, const int & AnimSate, const float & Time)
#define PARAM_ServerToClient_UpdateActorAnimState ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & templeteID, const int & AnimSate, const float & Time)
               
		virtual bool OnOtherActorAnimUpdated ( ::Proud::HostID, ::Proud::RmiContext& , const int & , const int & , const int & )		{ 
			return false;
		} 

#define DECRMI_ServerToClient_OnOtherActorAnimUpdated bool OnOtherActorAnimUpdated ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & templeteID, const int & AnimState, const int & AnimTime) PN_OVERRIDE

#define DEFRMI_ServerToClient_OnOtherActorAnimUpdated(DerivedClass) bool DerivedClass::OnOtherActorAnimUpdated ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & templeteID, const int & AnimState, const int & AnimTime)
#define CALL_ServerToClient_OnOtherActorAnimUpdated OnOtherActorAnimUpdated ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & templeteID, const int & AnimState, const int & AnimTime)
#define PARAM_ServerToClient_OnOtherActorAnimUpdated ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & templeteID, const int & AnimState, const int & AnimTime)
               
		virtual bool Request_AddItem ( ::Proud::HostID, ::Proud::RmiContext& , const int & , const int & , const int & )		{ 
			return false;
		} 

#define DECRMI_ServerToClient_Request_AddItem bool Request_AddItem ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & iClientID, const int & iItemID, const int & iItemCount) PN_OVERRIDE

#define DEFRMI_ServerToClient_Request_AddItem(DerivedClass) bool DerivedClass::Request_AddItem ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & iClientID, const int & iItemID, const int & iItemCount)
#define CALL_ServerToClient_Request_AddItem Request_AddItem ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & iClientID, const int & iItemID, const int & iItemCount)
#define PARAM_ServerToClient_Request_AddItem ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & iClientID, const int & iItemID, const int & iItemCount)
               
		virtual bool Request_RemoveItem ( ::Proud::HostID, ::Proud::RmiContext& , const int & , const int & , const int & )		{ 
			return false;
		} 

#define DECRMI_ServerToClient_Request_RemoveItem bool Request_RemoveItem ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & iClientID, const int & iItemID, const int & iItemCount) PN_OVERRIDE

#define DEFRMI_ServerToClient_Request_RemoveItem(DerivedClass) bool DerivedClass::Request_RemoveItem ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & iClientID, const int & iItemID, const int & iItemCount)
#define CALL_ServerToClient_Request_RemoveItem Request_RemoveItem ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & iClientID, const int & iItemID, const int & iItemCount)
#define PARAM_ServerToClient_Request_RemoveItem ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & iClientID, const int & iItemID, const int & iItemCount)
               
		virtual bool Request_ItemData ( ::Proud::HostID, ::Proud::RmiContext& , const int & , const int & )		{ 
			return false;
		} 

#define DECRMI_ServerToClient_Request_ItemData bool Request_ItemData ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & iClientID, const int & iItemID) PN_OVERRIDE

#define DEFRMI_ServerToClient_Request_ItemData(DerivedClass) bool DerivedClass::Request_ItemData ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & iClientID, const int & iItemID)
#define CALL_ServerToClient_Request_ItemData Request_ItemData ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & iClientID, const int & iItemID)
#define PARAM_ServerToClient_Request_ItemData ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & iClientID, const int & iItemID)
               
		virtual bool Request_AddGold ( ::Proud::HostID, ::Proud::RmiContext& , const int & , const int & )		{ 
			return false;
		} 

#define DECRMI_ServerToClient_Request_AddGold bool Request_AddGold ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & ClientID, const int & GoldAmount) PN_OVERRIDE

#define DEFRMI_ServerToClient_Request_AddGold(DerivedClass) bool DerivedClass::Request_AddGold ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & ClientID, const int & GoldAmount)
#define CALL_ServerToClient_Request_AddGold Request_AddGold ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & ClientID, const int & GoldAmount)
#define PARAM_ServerToClient_Request_AddGold ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & ClientID, const int & GoldAmount)
               
		virtual bool OnChat ( ::Proud::HostID, ::Proud::RmiContext& , const int & , const string & )		{ 
			return false;
		} 

#define DECRMI_ServerToClient_OnChat bool OnChat ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & clientId, const string & message) PN_OVERRIDE

#define DEFRMI_ServerToClient_OnChat(DerivedClass) bool DerivedClass::OnChat ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & clientId, const string & message)
#define CALL_ServerToClient_OnChat OnChat ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & clientId, const string & message)
#define PARAM_ServerToClient_OnChat ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & clientId, const string & message)
 
		virtual bool ProcessReceivedMessage(::Proud::CReceivedMessage &pa, void* hostTag) PN_OVERRIDE;
		static const PNTCHAR* RmiName_ResponseLoginEvent;
		static const PNTCHAR* RmiName_ResponseCheckNickname;
		static const PNTCHAR* RmiName_OnPlayerJoined;
		static const PNTCHAR* RmiName_SpawnObjectEvent;
		static const PNTCHAR* RmiName_OtherPlayerTransformUpdated;
		static const PNTCHAR* RmiName_OnPlayerTransformUpdated;
		static const PNTCHAR* RmiName_OtherActorTransformUpdated;
		static const PNTCHAR* RmiName_ActorTransformUpdated;
		static const PNTCHAR* RmiName_UpdateCharacterAnimState;
		static const PNTCHAR* RmiName_OnOtherPlayerAnimUpdated;
		static const PNTCHAR* RmiName_UpdateActorAnimState;
		static const PNTCHAR* RmiName_OnOtherActorAnimUpdated;
		static const PNTCHAR* RmiName_Request_AddItem;
		static const PNTCHAR* RmiName_Request_RemoveItem;
		static const PNTCHAR* RmiName_Request_ItemData;
		static const PNTCHAR* RmiName_Request_AddGold;
		static const PNTCHAR* RmiName_OnChat;
		static const PNTCHAR* RmiName_First;
		virtual ::Proud::RmiID* GetRmiIDList() PN_OVERRIDE { return g_RmiIDList; }
		virtual int GetRmiIDListCount() PN_OVERRIDE { return g_RmiIDListCount; }
	};

#ifdef SUPPORTS_CPP11 
	
	class StubFunctional : public Stub 
	{
	public:
               
		std::function< bool ( ::Proud::HostID, ::Proud::RmiContext& , const bool & , const int & ) > ResponseLoginEvent_Function;
		virtual bool ResponseLoginEvent ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const bool & bIsSuccess, const int & ErrorType) 
		{ 
			if (ResponseLoginEvent_Function==nullptr) 
				return true; 
			return ResponseLoginEvent_Function(remote,rmiContext, bIsSuccess, ErrorType); 
		}

               
		std::function< bool ( ::Proud::HostID, ::Proud::RmiContext& , const int & , const bool & ) > ResponseCheckNickname_Function;
		virtual bool ResponseCheckNickname ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & clientId, const bool & bIsAble) 
		{ 
			if (ResponseCheckNickname_Function==nullptr) 
				return true; 
			return ResponseCheckNickname_Function(remote,rmiContext, clientId, bIsAble); 
		}

               
		std::function< bool ( ::Proud::HostID, ::Proud::RmiContext& , const int & , const string & , const float & , const float & , const float & ) > OnPlayerJoined_Function;
		virtual bool OnPlayerJoined ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & clientId, const string & szNickName, const float & PosX, const float & PosY, const float & PosZ) 
		{ 
			if (OnPlayerJoined_Function==nullptr) 
				return true; 
			return OnPlayerJoined_Function(remote,rmiContext, clientId, szNickName, PosX, PosY, PosZ); 
		}

               
		std::function< bool ( ::Proud::HostID, ::Proud::RmiContext& , const string & , const int & , const float & , const float & , const float & ) > SpawnObjectEvent_Function;
		virtual bool SpawnObjectEvent ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const string & Key, const int & templetedID, const float & px, const float & py, const float & pz) 
		{ 
			if (SpawnObjectEvent_Function==nullptr) 
				return true; 
			return SpawnObjectEvent_Function(remote,rmiContext, Key, templetedID, px, py, pz); 
		}

               
		std::function< bool ( ::Proud::HostID, ::Proud::RmiContext& , const int & , const string & , const float & , const float & , const float & , const float & , const float & , const float & , const float & , const float & , const float & , const float & ) > OtherPlayerTransformUpdated_Function;
		virtual bool OtherPlayerTransformUpdated ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & ClientID, const string & NickName, const float & ScaleX, const float & ScaleY, const float & ScaleZ, const float & AngleX, const float & AngleY, const float & AngleZ, const float & AngleW, const float & PosX, const float & PosY, const float & PosZ) 
		{ 
			if (OtherPlayerTransformUpdated_Function==nullptr) 
				return true; 
			return OtherPlayerTransformUpdated_Function(remote,rmiContext, ClientID, NickName, ScaleX, ScaleY, ScaleZ, AngleX, AngleY, AngleZ, AngleW, PosX, PosY, PosZ); 
		}

               
		std::function< bool ( ::Proud::HostID, ::Proud::RmiContext& , const int & , const float & , const float & , const float & , const float & , const float & , const float & , const float & , const float & , const float & , const float & ) > OnPlayerTransformUpdated_Function;
		virtual bool OnPlayerTransformUpdated ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & clientId, const float & ScaleX, const float & ScaleY, const float & ScaleZ, const float & AngleX, const float & AngleY, const float & AngleZ, const float & AngleW, const float & PosX, const float & PosY, const float & PosZ) 
		{ 
			if (OnPlayerTransformUpdated_Function==nullptr) 
				return true; 
			return OnPlayerTransformUpdated_Function(remote,rmiContext, clientId, ScaleX, ScaleY, ScaleZ, AngleX, AngleY, AngleZ, AngleW, PosX, PosY, PosZ); 
		}

               
		std::function< bool ( ::Proud::HostID, ::Proud::RmiContext& , const int & , const float & , const float & , const float & , const float & , const float & , const float & , const float & , const float & , const float & , const float & ) > OtherActorTransformUpdated_Function;
		virtual bool OtherActorTransformUpdated ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & templeteID, const float & ScaleX, const float & ScaleY, const float & ScaleZ, const float & AngleX, const float & AngleY, const float & AngleZ, const float & AngleW, const float & PosX, const float & PosY, const float & PosZ) 
		{ 
			if (OtherActorTransformUpdated_Function==nullptr) 
				return true; 
			return OtherActorTransformUpdated_Function(remote,rmiContext, templeteID, ScaleX, ScaleY, ScaleZ, AngleX, AngleY, AngleZ, AngleW, PosX, PosY, PosZ); 
		}

               
		std::function< bool ( ::Proud::HostID, ::Proud::RmiContext& , const int & , const float & , const float & , const float & , const float & , const float & , const float & , const float & , const float & , const float & , const float & ) > ActorTransformUpdated_Function;
		virtual bool ActorTransformUpdated ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & templeteID, const float & ScaleX, const float & ScaleY, const float & ScaleZ, const float & AngleX, const float & AngleY, const float & AngleZ, const float & AngleW, const float & PosX, const float & PosY, const float & PosZ) 
		{ 
			if (ActorTransformUpdated_Function==nullptr) 
				return true; 
			return ActorTransformUpdated_Function(remote,rmiContext, templeteID, ScaleX, ScaleY, ScaleZ, AngleX, AngleY, AngleZ, AngleW, PosX, PosY, PosZ); 
		}

               
		std::function< bool ( ::Proud::HostID, ::Proud::RmiContext& , const int & , const int & , const float & ) > UpdateCharacterAnimState_Function;
		virtual bool UpdateCharacterAnimState ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & clientId, const int & AnimSate, const float & Time) 
		{ 
			if (UpdateCharacterAnimState_Function==nullptr) 
				return true; 
			return UpdateCharacterAnimState_Function(remote,rmiContext, clientId, AnimSate, Time); 
		}

               
		std::function< bool ( ::Proud::HostID, ::Proud::RmiContext& , const int & , const int & , const int & ) > OnOtherPlayerAnimUpdated_Function;
		virtual bool OnOtherPlayerAnimUpdated ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & ClientID, const int & AnimState, const int & AnimTime) 
		{ 
			if (OnOtherPlayerAnimUpdated_Function==nullptr) 
				return true; 
			return OnOtherPlayerAnimUpdated_Function(remote,rmiContext, ClientID, AnimState, AnimTime); 
		}

               
		std::function< bool ( ::Proud::HostID, ::Proud::RmiContext& , const int & , const int & , const float & ) > UpdateActorAnimState_Function;
		virtual bool UpdateActorAnimState ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & templeteID, const int & AnimSate, const float & Time) 
		{ 
			if (UpdateActorAnimState_Function==nullptr) 
				return true; 
			return UpdateActorAnimState_Function(remote,rmiContext, templeteID, AnimSate, Time); 
		}

               
		std::function< bool ( ::Proud::HostID, ::Proud::RmiContext& , const int & , const int & , const int & ) > OnOtherActorAnimUpdated_Function;
		virtual bool OnOtherActorAnimUpdated ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & templeteID, const int & AnimState, const int & AnimTime) 
		{ 
			if (OnOtherActorAnimUpdated_Function==nullptr) 
				return true; 
			return OnOtherActorAnimUpdated_Function(remote,rmiContext, templeteID, AnimState, AnimTime); 
		}

               
		std::function< bool ( ::Proud::HostID, ::Proud::RmiContext& , const int & , const int & , const int & ) > Request_AddItem_Function;
		virtual bool Request_AddItem ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & iClientID, const int & iItemID, const int & iItemCount) 
		{ 
			if (Request_AddItem_Function==nullptr) 
				return true; 
			return Request_AddItem_Function(remote,rmiContext, iClientID, iItemID, iItemCount); 
		}

               
		std::function< bool ( ::Proud::HostID, ::Proud::RmiContext& , const int & , const int & , const int & ) > Request_RemoveItem_Function;
		virtual bool Request_RemoveItem ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & iClientID, const int & iItemID, const int & iItemCount) 
		{ 
			if (Request_RemoveItem_Function==nullptr) 
				return true; 
			return Request_RemoveItem_Function(remote,rmiContext, iClientID, iItemID, iItemCount); 
		}

               
		std::function< bool ( ::Proud::HostID, ::Proud::RmiContext& , const int & , const int & ) > Request_ItemData_Function;
		virtual bool Request_ItemData ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & iClientID, const int & iItemID) 
		{ 
			if (Request_ItemData_Function==nullptr) 
				return true; 
			return Request_ItemData_Function(remote,rmiContext, iClientID, iItemID); 
		}

               
		std::function< bool ( ::Proud::HostID, ::Proud::RmiContext& , const int & , const int & ) > Request_AddGold_Function;
		virtual bool Request_AddGold ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & ClientID, const int & GoldAmount) 
		{ 
			if (Request_AddGold_Function==nullptr) 
				return true; 
			return Request_AddGold_Function(remote,rmiContext, ClientID, GoldAmount); 
		}

               
		std::function< bool ( ::Proud::HostID, ::Proud::RmiContext& , const int & , const string & ) > OnChat_Function;
		virtual bool OnChat ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & clientId, const string & message) 
		{ 
			if (OnChat_Function==nullptr) 
				return true; 
			return OnChat_Function(remote,rmiContext, clientId, message); 
		}

	};
#endif

}


