




// Generated by PIDL compiler.
// Do not modify this file, but modify the source .pidl file.

using System;
using System.Net;	     

namespace ServerToClient
{
	internal class Stub:Nettention.Proud.RmiStub
	{
public AfterRmiInvocationDelegate AfterRmiInvocation = delegate(Nettention.Proud.AfterRmiSummary summary) {};
public BeforeRmiInvocationDelegate BeforeRmiInvocation = delegate(Nettention.Proud.BeforeRmiSummary summary) {};

		public delegate bool ResponseLoginEventDelegate(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, bool bIsSuccess, int ErrorType);  
		public ResponseLoginEventDelegate ResponseLoginEvent = delegate(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, bool bIsSuccess, int ErrorType)
		{ 
			return false;
		};
		public delegate bool ResponseCheckNicknameDelegate(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, int clientId, bool bIsAble);  
		public ResponseCheckNicknameDelegate ResponseCheckNickname = delegate(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, int clientId, bool bIsAble)
		{ 
			return false;
		};
		public delegate bool OnPlayerJoinedDelegate(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, int clientId, string szNickName, float PosX, float PosY, float PosZ);  
		public OnPlayerJoinedDelegate OnPlayerJoined = delegate(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, int clientId, string szNickName, float PosX, float PosY, float PosZ)
		{ 
			return false;
		};
		public delegate bool OnOtherPlayerUpdatedDelegate(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, int ClientID, string NickName, float PosX, float PosY, float PosZ);  
		public OnOtherPlayerUpdatedDelegate OnOtherPlayerUpdated = delegate(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, int ClientID, string NickName, float PosX, float PosY, float PosZ)
		{ 
			return false;
		};
		public delegate bool OnOtherPlayerAnimUpdatedDelegate(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, int ClientID, int AnimState, int AnimTime);  
		public OnOtherPlayerAnimUpdatedDelegate OnOtherPlayerAnimUpdated = delegate(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, int ClientID, int AnimState, int AnimTime)
		{ 
			return false;
		};
		public delegate bool SpawnObjectEventDelegate(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, string Key, int templetedID, float px, float py, float pz);  
		public SpawnObjectEventDelegate SpawnObjectEvent = delegate(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, string Key, int templetedID, float px, float py, float pz)
		{ 
			return false;
		};
		public delegate bool OnOtherActorUpdatedDelegate(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, int templeteID, float PosX, float PosY, float PosZ);  
		public OnOtherActorUpdatedDelegate OnOtherActorUpdated = delegate(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, int templeteID, float PosX, float PosY, float PosZ)
		{ 
			return false;
		};
		public delegate bool OnOtherActorAnimUpdatedDelegate(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, int templeteID, int AnimState, int AnimTime);  
		public OnOtherActorAnimUpdatedDelegate OnOtherActorAnimUpdated = delegate(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, int templeteID, int AnimState, int AnimTime)
		{ 
			return false;
		};
		public delegate bool OnPositionUpdatedDelegate(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, int clientId, float PosX, float PosY, float PosZ, float DirX, float DirY, float DirZ);  
		public OnPositionUpdatedDelegate OnPositionUpdated = delegate(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, int clientId, float PosX, float PosY, float PosZ, float DirX, float DirY, float DirZ)
		{ 
			return false;
		};
		public delegate bool OnActorPositionUpdatedDelegate(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, int templeteID, float PosX, float PosY, float PosZ, float DirX, float DirY, float DirZ);  
		public OnActorPositionUpdatedDelegate OnActorPositionUpdated = delegate(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, int templeteID, float PosX, float PosY, float PosZ, float DirX, float DirY, float DirZ)
		{ 
			return false;
		};
		public delegate bool UpdateCharacterAnimStateDelegate(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, int clientId, int AnimSate, float Time);  
		public UpdateCharacterAnimStateDelegate UpdateCharacterAnimState = delegate(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, int clientId, int AnimSate, float Time)
		{ 
			return false;
		};
		public delegate bool UpdateActorAnimStateDelegate(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, int templeteID, int AnimSate, float Time);  
		public UpdateActorAnimStateDelegate UpdateActorAnimState = delegate(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, int templeteID, int AnimSate, float Time)
		{ 
			return false;
		};
		public delegate bool OnChatDelegate(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, int clientId, string message);  
		public OnChatDelegate OnChat = delegate(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, int clientId, string message)
		{ 
			return false;
		};
	public override bool ProcessReceivedMessage(Nettention.Proud.ReceivedMessage pa, Object hostTag) 
	{
		Nettention.Proud.HostID remote=pa.RemoteHostID;
		if(remote==Nettention.Proud.HostID.HostID_None)
		{
			ShowUnknownHostIDWarning(remote);
		}

		Nettention.Proud.Message __msg=pa.ReadOnlyMessage;
		int orgReadOffset = __msg.ReadOffset;
        Nettention.Proud.RmiID __rmiID = Nettention.Proud.RmiID.RmiID_None;
        if (!__msg.Read( out __rmiID))
            goto __fail;
					
		switch(__rmiID)
		{
        case Common.ResponseLoginEvent:
            ProcessReceivedMessage_ResponseLoginEvent(__msg, pa, hostTag, remote);
            break;
        case Common.ResponseCheckNickname:
            ProcessReceivedMessage_ResponseCheckNickname(__msg, pa, hostTag, remote);
            break;
        case Common.OnPlayerJoined:
            ProcessReceivedMessage_OnPlayerJoined(__msg, pa, hostTag, remote);
            break;
        case Common.OnOtherPlayerUpdated:
            ProcessReceivedMessage_OnOtherPlayerUpdated(__msg, pa, hostTag, remote);
            break;
        case Common.OnOtherPlayerAnimUpdated:
            ProcessReceivedMessage_OnOtherPlayerAnimUpdated(__msg, pa, hostTag, remote);
            break;
        case Common.SpawnObjectEvent:
            ProcessReceivedMessage_SpawnObjectEvent(__msg, pa, hostTag, remote);
            break;
        case Common.OnOtherActorUpdated:
            ProcessReceivedMessage_OnOtherActorUpdated(__msg, pa, hostTag, remote);
            break;
        case Common.OnOtherActorAnimUpdated:
            ProcessReceivedMessage_OnOtherActorAnimUpdated(__msg, pa, hostTag, remote);
            break;
        case Common.OnPositionUpdated:
            ProcessReceivedMessage_OnPositionUpdated(__msg, pa, hostTag, remote);
            break;
        case Common.OnActorPositionUpdated:
            ProcessReceivedMessage_OnActorPositionUpdated(__msg, pa, hostTag, remote);
            break;
        case Common.UpdateCharacterAnimState:
            ProcessReceivedMessage_UpdateCharacterAnimState(__msg, pa, hostTag, remote);
            break;
        case Common.UpdateActorAnimState:
            ProcessReceivedMessage_UpdateActorAnimState(__msg, pa, hostTag, remote);
            break;
        case Common.OnChat:
            ProcessReceivedMessage_OnChat(__msg, pa, hostTag, remote);
            break;
		default:
			 goto __fail;
		}
		return true;
__fail:
	  {
			__msg.ReadOffset = orgReadOffset;
			return false;
	  }
	}
    void ProcessReceivedMessage_ResponseLoginEvent(Nettention.Proud.Message __msg, Nettention.Proud.ReceivedMessage pa, Object hostTag, Nettention.Proud.HostID remote)
    {
        Nettention.Proud.RmiContext ctx = new Nettention.Proud.RmiContext();
        ctx.sentFrom=pa.RemoteHostID;
        ctx.relayed=pa.IsRelayed;
        ctx.hostTag=hostTag;
        ctx.encryptMode = pa.EncryptMode;
        ctx.compressMode = pa.CompressMode;
        ctx.rmiID = Common.ResponseLoginEvent;

        bool bIsSuccess; Nettention.Proud.Marshaler.Read(__msg,out bIsSuccess);	
int ErrorType; Nettention.Proud.Marshaler.Read(__msg,out ErrorType);	
core.PostCheckReadMessage(__msg, RmiName_ResponseLoginEvent);
        if(enableNotifyCallFromStub==true)
        {
        string parameterString = "";
        parameterString+=bIsSuccess.ToString()+",";
parameterString+=ErrorType.ToString()+",";
        NotifyCallFromStub(Common.ResponseLoginEvent, RmiName_ResponseLoginEvent,parameterString);
        }

        if(enableStubProfiling)
        {
        Nettention.Proud.BeforeRmiSummary summary = new Nettention.Proud.BeforeRmiSummary();
        summary.rmiID = Common.ResponseLoginEvent;
        summary.rmiName = RmiName_ResponseLoginEvent;
        summary.hostID = remote;
        summary.hostTag = hostTag;
        BeforeRmiInvocation(summary);
        }

        long t0 = Nettention.Proud.PreciseCurrentTime.GetTimeMs();

        // Call this method.
        bool __ret =ResponseLoginEvent (remote,ctx , bIsSuccess, ErrorType );

        if(__ret==false)
        {
        // Error: RMI function that a user did not create has been called. 
        core.ShowNotImplementedRmiWarning(RmiName_ResponseLoginEvent);
        }

        if(enableStubProfiling)
        {
        Nettention.Proud.AfterRmiSummary summary = new Nettention.Proud.AfterRmiSummary();
        summary.rmiID = Common.ResponseLoginEvent;
        summary.rmiName = RmiName_ResponseLoginEvent;
        summary.hostID = remote;
        summary.hostTag = hostTag;
        summary.elapsedTime = Nettention.Proud.PreciseCurrentTime.GetTimeMs()-t0;
        AfterRmiInvocation(summary);
        }
    }
    void ProcessReceivedMessage_ResponseCheckNickname(Nettention.Proud.Message __msg, Nettention.Proud.ReceivedMessage pa, Object hostTag, Nettention.Proud.HostID remote)
    {
        Nettention.Proud.RmiContext ctx = new Nettention.Proud.RmiContext();
        ctx.sentFrom=pa.RemoteHostID;
        ctx.relayed=pa.IsRelayed;
        ctx.hostTag=hostTag;
        ctx.encryptMode = pa.EncryptMode;
        ctx.compressMode = pa.CompressMode;
        ctx.rmiID = Common.ResponseCheckNickname;

        int clientId; Nettention.Proud.Marshaler.Read(__msg,out clientId);	
bool bIsAble; Nettention.Proud.Marshaler.Read(__msg,out bIsAble);	
core.PostCheckReadMessage(__msg, RmiName_ResponseCheckNickname);
        if(enableNotifyCallFromStub==true)
        {
        string parameterString = "";
        parameterString+=clientId.ToString()+",";
parameterString+=bIsAble.ToString()+",";
        NotifyCallFromStub(Common.ResponseCheckNickname, RmiName_ResponseCheckNickname,parameterString);
        }

        if(enableStubProfiling)
        {
        Nettention.Proud.BeforeRmiSummary summary = new Nettention.Proud.BeforeRmiSummary();
        summary.rmiID = Common.ResponseCheckNickname;
        summary.rmiName = RmiName_ResponseCheckNickname;
        summary.hostID = remote;
        summary.hostTag = hostTag;
        BeforeRmiInvocation(summary);
        }

        long t0 = Nettention.Proud.PreciseCurrentTime.GetTimeMs();

        // Call this method.
        bool __ret =ResponseCheckNickname (remote,ctx , clientId, bIsAble );

        if(__ret==false)
        {
        // Error: RMI function that a user did not create has been called. 
        core.ShowNotImplementedRmiWarning(RmiName_ResponseCheckNickname);
        }

        if(enableStubProfiling)
        {
        Nettention.Proud.AfterRmiSummary summary = new Nettention.Proud.AfterRmiSummary();
        summary.rmiID = Common.ResponseCheckNickname;
        summary.rmiName = RmiName_ResponseCheckNickname;
        summary.hostID = remote;
        summary.hostTag = hostTag;
        summary.elapsedTime = Nettention.Proud.PreciseCurrentTime.GetTimeMs()-t0;
        AfterRmiInvocation(summary);
        }
    }
    void ProcessReceivedMessage_OnPlayerJoined(Nettention.Proud.Message __msg, Nettention.Proud.ReceivedMessage pa, Object hostTag, Nettention.Proud.HostID remote)
    {
        Nettention.Proud.RmiContext ctx = new Nettention.Proud.RmiContext();
        ctx.sentFrom=pa.RemoteHostID;
        ctx.relayed=pa.IsRelayed;
        ctx.hostTag=hostTag;
        ctx.encryptMode = pa.EncryptMode;
        ctx.compressMode = pa.CompressMode;
        ctx.rmiID = Common.OnPlayerJoined;

        int clientId; Nettention.Proud.Marshaler.Read(__msg,out clientId);	
string szNickName; Nettention.Proud.Marshaler.Read(__msg,out szNickName);	
float PosX; Nettention.Proud.Marshaler.Read(__msg,out PosX);	
float PosY; Nettention.Proud.Marshaler.Read(__msg,out PosY);	
float PosZ; Nettention.Proud.Marshaler.Read(__msg,out PosZ);	
core.PostCheckReadMessage(__msg, RmiName_OnPlayerJoined);
        if(enableNotifyCallFromStub==true)
        {
        string parameterString = "";
        parameterString+=clientId.ToString()+",";
parameterString+=szNickName.ToString()+",";
parameterString+=PosX.ToString()+",";
parameterString+=PosY.ToString()+",";
parameterString+=PosZ.ToString()+",";
        NotifyCallFromStub(Common.OnPlayerJoined, RmiName_OnPlayerJoined,parameterString);
        }

        if(enableStubProfiling)
        {
        Nettention.Proud.BeforeRmiSummary summary = new Nettention.Proud.BeforeRmiSummary();
        summary.rmiID = Common.OnPlayerJoined;
        summary.rmiName = RmiName_OnPlayerJoined;
        summary.hostID = remote;
        summary.hostTag = hostTag;
        BeforeRmiInvocation(summary);
        }

        long t0 = Nettention.Proud.PreciseCurrentTime.GetTimeMs();

        // Call this method.
        bool __ret =OnPlayerJoined (remote,ctx , clientId, szNickName, PosX, PosY, PosZ );

        if(__ret==false)
        {
        // Error: RMI function that a user did not create has been called. 
        core.ShowNotImplementedRmiWarning(RmiName_OnPlayerJoined);
        }

        if(enableStubProfiling)
        {
        Nettention.Proud.AfterRmiSummary summary = new Nettention.Proud.AfterRmiSummary();
        summary.rmiID = Common.OnPlayerJoined;
        summary.rmiName = RmiName_OnPlayerJoined;
        summary.hostID = remote;
        summary.hostTag = hostTag;
        summary.elapsedTime = Nettention.Proud.PreciseCurrentTime.GetTimeMs()-t0;
        AfterRmiInvocation(summary);
        }
    }
    void ProcessReceivedMessage_OnOtherPlayerUpdated(Nettention.Proud.Message __msg, Nettention.Proud.ReceivedMessage pa, Object hostTag, Nettention.Proud.HostID remote)
    {
        Nettention.Proud.RmiContext ctx = new Nettention.Proud.RmiContext();
        ctx.sentFrom=pa.RemoteHostID;
        ctx.relayed=pa.IsRelayed;
        ctx.hostTag=hostTag;
        ctx.encryptMode = pa.EncryptMode;
        ctx.compressMode = pa.CompressMode;
        ctx.rmiID = Common.OnOtherPlayerUpdated;

        int ClientID; Nettention.Proud.Marshaler.Read(__msg,out ClientID);	
string NickName; Nettention.Proud.Marshaler.Read(__msg,out NickName);	
float PosX; Nettention.Proud.Marshaler.Read(__msg,out PosX);	
float PosY; Nettention.Proud.Marshaler.Read(__msg,out PosY);	
float PosZ; Nettention.Proud.Marshaler.Read(__msg,out PosZ);	
core.PostCheckReadMessage(__msg, RmiName_OnOtherPlayerUpdated);
        if(enableNotifyCallFromStub==true)
        {
        string parameterString = "";
        parameterString+=ClientID.ToString()+",";
parameterString+=NickName.ToString()+",";
parameterString+=PosX.ToString()+",";
parameterString+=PosY.ToString()+",";
parameterString+=PosZ.ToString()+",";
        NotifyCallFromStub(Common.OnOtherPlayerUpdated, RmiName_OnOtherPlayerUpdated,parameterString);
        }

        if(enableStubProfiling)
        {
        Nettention.Proud.BeforeRmiSummary summary = new Nettention.Proud.BeforeRmiSummary();
        summary.rmiID = Common.OnOtherPlayerUpdated;
        summary.rmiName = RmiName_OnOtherPlayerUpdated;
        summary.hostID = remote;
        summary.hostTag = hostTag;
        BeforeRmiInvocation(summary);
        }

        long t0 = Nettention.Proud.PreciseCurrentTime.GetTimeMs();

        // Call this method.
        bool __ret =OnOtherPlayerUpdated (remote,ctx , ClientID, NickName, PosX, PosY, PosZ );

        if(__ret==false)
        {
        // Error: RMI function that a user did not create has been called. 
        core.ShowNotImplementedRmiWarning(RmiName_OnOtherPlayerUpdated);
        }

        if(enableStubProfiling)
        {
        Nettention.Proud.AfterRmiSummary summary = new Nettention.Proud.AfterRmiSummary();
        summary.rmiID = Common.OnOtherPlayerUpdated;
        summary.rmiName = RmiName_OnOtherPlayerUpdated;
        summary.hostID = remote;
        summary.hostTag = hostTag;
        summary.elapsedTime = Nettention.Proud.PreciseCurrentTime.GetTimeMs()-t0;
        AfterRmiInvocation(summary);
        }
    }
    void ProcessReceivedMessage_OnOtherPlayerAnimUpdated(Nettention.Proud.Message __msg, Nettention.Proud.ReceivedMessage pa, Object hostTag, Nettention.Proud.HostID remote)
    {
        Nettention.Proud.RmiContext ctx = new Nettention.Proud.RmiContext();
        ctx.sentFrom=pa.RemoteHostID;
        ctx.relayed=pa.IsRelayed;
        ctx.hostTag=hostTag;
        ctx.encryptMode = pa.EncryptMode;
        ctx.compressMode = pa.CompressMode;
        ctx.rmiID = Common.OnOtherPlayerAnimUpdated;

        int ClientID; Nettention.Proud.Marshaler.Read(__msg,out ClientID);	
int AnimState; Nettention.Proud.Marshaler.Read(__msg,out AnimState);	
int AnimTime; Nettention.Proud.Marshaler.Read(__msg,out AnimTime);	
core.PostCheckReadMessage(__msg, RmiName_OnOtherPlayerAnimUpdated);
        if(enableNotifyCallFromStub==true)
        {
        string parameterString = "";
        parameterString+=ClientID.ToString()+",";
parameterString+=AnimState.ToString()+",";
parameterString+=AnimTime.ToString()+",";
        NotifyCallFromStub(Common.OnOtherPlayerAnimUpdated, RmiName_OnOtherPlayerAnimUpdated,parameterString);
        }

        if(enableStubProfiling)
        {
        Nettention.Proud.BeforeRmiSummary summary = new Nettention.Proud.BeforeRmiSummary();
        summary.rmiID = Common.OnOtherPlayerAnimUpdated;
        summary.rmiName = RmiName_OnOtherPlayerAnimUpdated;
        summary.hostID = remote;
        summary.hostTag = hostTag;
        BeforeRmiInvocation(summary);
        }

        long t0 = Nettention.Proud.PreciseCurrentTime.GetTimeMs();

        // Call this method.
        bool __ret =OnOtherPlayerAnimUpdated (remote,ctx , ClientID, AnimState, AnimTime );

        if(__ret==false)
        {
        // Error: RMI function that a user did not create has been called. 
        core.ShowNotImplementedRmiWarning(RmiName_OnOtherPlayerAnimUpdated);
        }

        if(enableStubProfiling)
        {
        Nettention.Proud.AfterRmiSummary summary = new Nettention.Proud.AfterRmiSummary();
        summary.rmiID = Common.OnOtherPlayerAnimUpdated;
        summary.rmiName = RmiName_OnOtherPlayerAnimUpdated;
        summary.hostID = remote;
        summary.hostTag = hostTag;
        summary.elapsedTime = Nettention.Proud.PreciseCurrentTime.GetTimeMs()-t0;
        AfterRmiInvocation(summary);
        }
    }
    void ProcessReceivedMessage_SpawnObjectEvent(Nettention.Proud.Message __msg, Nettention.Proud.ReceivedMessage pa, Object hostTag, Nettention.Proud.HostID remote)
    {
        Nettention.Proud.RmiContext ctx = new Nettention.Proud.RmiContext();
        ctx.sentFrom=pa.RemoteHostID;
        ctx.relayed=pa.IsRelayed;
        ctx.hostTag=hostTag;
        ctx.encryptMode = pa.EncryptMode;
        ctx.compressMode = pa.CompressMode;
        ctx.rmiID = Common.SpawnObjectEvent;

        string Key; Nettention.Proud.Marshaler.Read(__msg,out Key);	
int templetedID; Nettention.Proud.Marshaler.Read(__msg,out templetedID);	
float px; Nettention.Proud.Marshaler.Read(__msg,out px);	
float py; Nettention.Proud.Marshaler.Read(__msg,out py);	
float pz; Nettention.Proud.Marshaler.Read(__msg,out pz);	
core.PostCheckReadMessage(__msg, RmiName_SpawnObjectEvent);
        if(enableNotifyCallFromStub==true)
        {
        string parameterString = "";
        parameterString+=Key.ToString()+",";
parameterString+=templetedID.ToString()+",";
parameterString+=px.ToString()+",";
parameterString+=py.ToString()+",";
parameterString+=pz.ToString()+",";
        NotifyCallFromStub(Common.SpawnObjectEvent, RmiName_SpawnObjectEvent,parameterString);
        }

        if(enableStubProfiling)
        {
        Nettention.Proud.BeforeRmiSummary summary = new Nettention.Proud.BeforeRmiSummary();
        summary.rmiID = Common.SpawnObjectEvent;
        summary.rmiName = RmiName_SpawnObjectEvent;
        summary.hostID = remote;
        summary.hostTag = hostTag;
        BeforeRmiInvocation(summary);
        }

        long t0 = Nettention.Proud.PreciseCurrentTime.GetTimeMs();

        // Call this method.
        bool __ret =SpawnObjectEvent (remote,ctx , Key, templetedID, px, py, pz );

        if(__ret==false)
        {
        // Error: RMI function that a user did not create has been called. 
        core.ShowNotImplementedRmiWarning(RmiName_SpawnObjectEvent);
        }

        if(enableStubProfiling)
        {
        Nettention.Proud.AfterRmiSummary summary = new Nettention.Proud.AfterRmiSummary();
        summary.rmiID = Common.SpawnObjectEvent;
        summary.rmiName = RmiName_SpawnObjectEvent;
        summary.hostID = remote;
        summary.hostTag = hostTag;
        summary.elapsedTime = Nettention.Proud.PreciseCurrentTime.GetTimeMs()-t0;
        AfterRmiInvocation(summary);
        }
    }
    void ProcessReceivedMessage_OnOtherActorUpdated(Nettention.Proud.Message __msg, Nettention.Proud.ReceivedMessage pa, Object hostTag, Nettention.Proud.HostID remote)
    {
        Nettention.Proud.RmiContext ctx = new Nettention.Proud.RmiContext();
        ctx.sentFrom=pa.RemoteHostID;
        ctx.relayed=pa.IsRelayed;
        ctx.hostTag=hostTag;
        ctx.encryptMode = pa.EncryptMode;
        ctx.compressMode = pa.CompressMode;
        ctx.rmiID = Common.OnOtherActorUpdated;

        int templeteID; Nettention.Proud.Marshaler.Read(__msg,out templeteID);	
float PosX; Nettention.Proud.Marshaler.Read(__msg,out PosX);	
float PosY; Nettention.Proud.Marshaler.Read(__msg,out PosY);	
float PosZ; Nettention.Proud.Marshaler.Read(__msg,out PosZ);	
core.PostCheckReadMessage(__msg, RmiName_OnOtherActorUpdated);
        if(enableNotifyCallFromStub==true)
        {
        string parameterString = "";
        parameterString+=templeteID.ToString()+",";
parameterString+=PosX.ToString()+",";
parameterString+=PosY.ToString()+",";
parameterString+=PosZ.ToString()+",";
        NotifyCallFromStub(Common.OnOtherActorUpdated, RmiName_OnOtherActorUpdated,parameterString);
        }

        if(enableStubProfiling)
        {
        Nettention.Proud.BeforeRmiSummary summary = new Nettention.Proud.BeforeRmiSummary();
        summary.rmiID = Common.OnOtherActorUpdated;
        summary.rmiName = RmiName_OnOtherActorUpdated;
        summary.hostID = remote;
        summary.hostTag = hostTag;
        BeforeRmiInvocation(summary);
        }

        long t0 = Nettention.Proud.PreciseCurrentTime.GetTimeMs();

        // Call this method.
        bool __ret =OnOtherActorUpdated (remote,ctx , templeteID, PosX, PosY, PosZ );

        if(__ret==false)
        {
        // Error: RMI function that a user did not create has been called. 
        core.ShowNotImplementedRmiWarning(RmiName_OnOtherActorUpdated);
        }

        if(enableStubProfiling)
        {
        Nettention.Proud.AfterRmiSummary summary = new Nettention.Proud.AfterRmiSummary();
        summary.rmiID = Common.OnOtherActorUpdated;
        summary.rmiName = RmiName_OnOtherActorUpdated;
        summary.hostID = remote;
        summary.hostTag = hostTag;
        summary.elapsedTime = Nettention.Proud.PreciseCurrentTime.GetTimeMs()-t0;
        AfterRmiInvocation(summary);
        }
    }
    void ProcessReceivedMessage_OnOtherActorAnimUpdated(Nettention.Proud.Message __msg, Nettention.Proud.ReceivedMessage pa, Object hostTag, Nettention.Proud.HostID remote)
    {
        Nettention.Proud.RmiContext ctx = new Nettention.Proud.RmiContext();
        ctx.sentFrom=pa.RemoteHostID;
        ctx.relayed=pa.IsRelayed;
        ctx.hostTag=hostTag;
        ctx.encryptMode = pa.EncryptMode;
        ctx.compressMode = pa.CompressMode;
        ctx.rmiID = Common.OnOtherActorAnimUpdated;

        int templeteID; Nettention.Proud.Marshaler.Read(__msg,out templeteID);	
int AnimState; Nettention.Proud.Marshaler.Read(__msg,out AnimState);	
int AnimTime; Nettention.Proud.Marshaler.Read(__msg,out AnimTime);	
core.PostCheckReadMessage(__msg, RmiName_OnOtherActorAnimUpdated);
        if(enableNotifyCallFromStub==true)
        {
        string parameterString = "";
        parameterString+=templeteID.ToString()+",";
parameterString+=AnimState.ToString()+",";
parameterString+=AnimTime.ToString()+",";
        NotifyCallFromStub(Common.OnOtherActorAnimUpdated, RmiName_OnOtherActorAnimUpdated,parameterString);
        }

        if(enableStubProfiling)
        {
        Nettention.Proud.BeforeRmiSummary summary = new Nettention.Proud.BeforeRmiSummary();
        summary.rmiID = Common.OnOtherActorAnimUpdated;
        summary.rmiName = RmiName_OnOtherActorAnimUpdated;
        summary.hostID = remote;
        summary.hostTag = hostTag;
        BeforeRmiInvocation(summary);
        }

        long t0 = Nettention.Proud.PreciseCurrentTime.GetTimeMs();

        // Call this method.
        bool __ret =OnOtherActorAnimUpdated (remote,ctx , templeteID, AnimState, AnimTime );

        if(__ret==false)
        {
        // Error: RMI function that a user did not create has been called. 
        core.ShowNotImplementedRmiWarning(RmiName_OnOtherActorAnimUpdated);
        }

        if(enableStubProfiling)
        {
        Nettention.Proud.AfterRmiSummary summary = new Nettention.Proud.AfterRmiSummary();
        summary.rmiID = Common.OnOtherActorAnimUpdated;
        summary.rmiName = RmiName_OnOtherActorAnimUpdated;
        summary.hostID = remote;
        summary.hostTag = hostTag;
        summary.elapsedTime = Nettention.Proud.PreciseCurrentTime.GetTimeMs()-t0;
        AfterRmiInvocation(summary);
        }
    }
    void ProcessReceivedMessage_OnPositionUpdated(Nettention.Proud.Message __msg, Nettention.Proud.ReceivedMessage pa, Object hostTag, Nettention.Proud.HostID remote)
    {
        Nettention.Proud.RmiContext ctx = new Nettention.Proud.RmiContext();
        ctx.sentFrom=pa.RemoteHostID;
        ctx.relayed=pa.IsRelayed;
        ctx.hostTag=hostTag;
        ctx.encryptMode = pa.EncryptMode;
        ctx.compressMode = pa.CompressMode;
        ctx.rmiID = Common.OnPositionUpdated;

        int clientId; Nettention.Proud.Marshaler.Read(__msg,out clientId);	
float PosX; Nettention.Proud.Marshaler.Read(__msg,out PosX);	
float PosY; Nettention.Proud.Marshaler.Read(__msg,out PosY);	
float PosZ; Nettention.Proud.Marshaler.Read(__msg,out PosZ);	
float DirX; Nettention.Proud.Marshaler.Read(__msg,out DirX);	
float DirY; Nettention.Proud.Marshaler.Read(__msg,out DirY);	
float DirZ; Nettention.Proud.Marshaler.Read(__msg,out DirZ);	
core.PostCheckReadMessage(__msg, RmiName_OnPositionUpdated);
        if(enableNotifyCallFromStub==true)
        {
        string parameterString = "";
        parameterString+=clientId.ToString()+",";
parameterString+=PosX.ToString()+",";
parameterString+=PosY.ToString()+",";
parameterString+=PosZ.ToString()+",";
parameterString+=DirX.ToString()+",";
parameterString+=DirY.ToString()+",";
parameterString+=DirZ.ToString()+",";
        NotifyCallFromStub(Common.OnPositionUpdated, RmiName_OnPositionUpdated,parameterString);
        }

        if(enableStubProfiling)
        {
        Nettention.Proud.BeforeRmiSummary summary = new Nettention.Proud.BeforeRmiSummary();
        summary.rmiID = Common.OnPositionUpdated;
        summary.rmiName = RmiName_OnPositionUpdated;
        summary.hostID = remote;
        summary.hostTag = hostTag;
        BeforeRmiInvocation(summary);
        }

        long t0 = Nettention.Proud.PreciseCurrentTime.GetTimeMs();

        // Call this method.
        bool __ret =OnPositionUpdated (remote,ctx , clientId, PosX, PosY, PosZ, DirX, DirY, DirZ );

        if(__ret==false)
        {
        // Error: RMI function that a user did not create has been called. 
        core.ShowNotImplementedRmiWarning(RmiName_OnPositionUpdated);
        }

        if(enableStubProfiling)
        {
        Nettention.Proud.AfterRmiSummary summary = new Nettention.Proud.AfterRmiSummary();
        summary.rmiID = Common.OnPositionUpdated;
        summary.rmiName = RmiName_OnPositionUpdated;
        summary.hostID = remote;
        summary.hostTag = hostTag;
        summary.elapsedTime = Nettention.Proud.PreciseCurrentTime.GetTimeMs()-t0;
        AfterRmiInvocation(summary);
        }
    }
    void ProcessReceivedMessage_OnActorPositionUpdated(Nettention.Proud.Message __msg, Nettention.Proud.ReceivedMessage pa, Object hostTag, Nettention.Proud.HostID remote)
    {
        Nettention.Proud.RmiContext ctx = new Nettention.Proud.RmiContext();
        ctx.sentFrom=pa.RemoteHostID;
        ctx.relayed=pa.IsRelayed;
        ctx.hostTag=hostTag;
        ctx.encryptMode = pa.EncryptMode;
        ctx.compressMode = pa.CompressMode;
        ctx.rmiID = Common.OnActorPositionUpdated;

        int templeteID; Nettention.Proud.Marshaler.Read(__msg,out templeteID);	
float PosX; Nettention.Proud.Marshaler.Read(__msg,out PosX);	
float PosY; Nettention.Proud.Marshaler.Read(__msg,out PosY);	
float PosZ; Nettention.Proud.Marshaler.Read(__msg,out PosZ);	
float DirX; Nettention.Proud.Marshaler.Read(__msg,out DirX);	
float DirY; Nettention.Proud.Marshaler.Read(__msg,out DirY);	
float DirZ; Nettention.Proud.Marshaler.Read(__msg,out DirZ);	
core.PostCheckReadMessage(__msg, RmiName_OnActorPositionUpdated);
        if(enableNotifyCallFromStub==true)
        {
        string parameterString = "";
        parameterString+=templeteID.ToString()+",";
parameterString+=PosX.ToString()+",";
parameterString+=PosY.ToString()+",";
parameterString+=PosZ.ToString()+",";
parameterString+=DirX.ToString()+",";
parameterString+=DirY.ToString()+",";
parameterString+=DirZ.ToString()+",";
        NotifyCallFromStub(Common.OnActorPositionUpdated, RmiName_OnActorPositionUpdated,parameterString);
        }

        if(enableStubProfiling)
        {
        Nettention.Proud.BeforeRmiSummary summary = new Nettention.Proud.BeforeRmiSummary();
        summary.rmiID = Common.OnActorPositionUpdated;
        summary.rmiName = RmiName_OnActorPositionUpdated;
        summary.hostID = remote;
        summary.hostTag = hostTag;
        BeforeRmiInvocation(summary);
        }

        long t0 = Nettention.Proud.PreciseCurrentTime.GetTimeMs();

        // Call this method.
        bool __ret =OnActorPositionUpdated (remote,ctx , templeteID, PosX, PosY, PosZ, DirX, DirY, DirZ );

        if(__ret==false)
        {
        // Error: RMI function that a user did not create has been called. 
        core.ShowNotImplementedRmiWarning(RmiName_OnActorPositionUpdated);
        }

        if(enableStubProfiling)
        {
        Nettention.Proud.AfterRmiSummary summary = new Nettention.Proud.AfterRmiSummary();
        summary.rmiID = Common.OnActorPositionUpdated;
        summary.rmiName = RmiName_OnActorPositionUpdated;
        summary.hostID = remote;
        summary.hostTag = hostTag;
        summary.elapsedTime = Nettention.Proud.PreciseCurrentTime.GetTimeMs()-t0;
        AfterRmiInvocation(summary);
        }
    }
    void ProcessReceivedMessage_UpdateCharacterAnimState(Nettention.Proud.Message __msg, Nettention.Proud.ReceivedMessage pa, Object hostTag, Nettention.Proud.HostID remote)
    {
        Nettention.Proud.RmiContext ctx = new Nettention.Proud.RmiContext();
        ctx.sentFrom=pa.RemoteHostID;
        ctx.relayed=pa.IsRelayed;
        ctx.hostTag=hostTag;
        ctx.encryptMode = pa.EncryptMode;
        ctx.compressMode = pa.CompressMode;
        ctx.rmiID = Common.UpdateCharacterAnimState;

        int clientId; Nettention.Proud.Marshaler.Read(__msg,out clientId);	
int AnimSate; Nettention.Proud.Marshaler.Read(__msg,out AnimSate);	
float Time; Nettention.Proud.Marshaler.Read(__msg,out Time);	
core.PostCheckReadMessage(__msg, RmiName_UpdateCharacterAnimState);
        if(enableNotifyCallFromStub==true)
        {
        string parameterString = "";
        parameterString+=clientId.ToString()+",";
parameterString+=AnimSate.ToString()+",";
parameterString+=Time.ToString()+",";
        NotifyCallFromStub(Common.UpdateCharacterAnimState, RmiName_UpdateCharacterAnimState,parameterString);
        }

        if(enableStubProfiling)
        {
        Nettention.Proud.BeforeRmiSummary summary = new Nettention.Proud.BeforeRmiSummary();
        summary.rmiID = Common.UpdateCharacterAnimState;
        summary.rmiName = RmiName_UpdateCharacterAnimState;
        summary.hostID = remote;
        summary.hostTag = hostTag;
        BeforeRmiInvocation(summary);
        }

        long t0 = Nettention.Proud.PreciseCurrentTime.GetTimeMs();

        // Call this method.
        bool __ret =UpdateCharacterAnimState (remote,ctx , clientId, AnimSate, Time );

        if(__ret==false)
        {
        // Error: RMI function that a user did not create has been called. 
        core.ShowNotImplementedRmiWarning(RmiName_UpdateCharacterAnimState);
        }

        if(enableStubProfiling)
        {
        Nettention.Proud.AfterRmiSummary summary = new Nettention.Proud.AfterRmiSummary();
        summary.rmiID = Common.UpdateCharacterAnimState;
        summary.rmiName = RmiName_UpdateCharacterAnimState;
        summary.hostID = remote;
        summary.hostTag = hostTag;
        summary.elapsedTime = Nettention.Proud.PreciseCurrentTime.GetTimeMs()-t0;
        AfterRmiInvocation(summary);
        }
    }
    void ProcessReceivedMessage_UpdateActorAnimState(Nettention.Proud.Message __msg, Nettention.Proud.ReceivedMessage pa, Object hostTag, Nettention.Proud.HostID remote)
    {
        Nettention.Proud.RmiContext ctx = new Nettention.Proud.RmiContext();
        ctx.sentFrom=pa.RemoteHostID;
        ctx.relayed=pa.IsRelayed;
        ctx.hostTag=hostTag;
        ctx.encryptMode = pa.EncryptMode;
        ctx.compressMode = pa.CompressMode;
        ctx.rmiID = Common.UpdateActorAnimState;

        int templeteID; Nettention.Proud.Marshaler.Read(__msg,out templeteID);	
int AnimSate; Nettention.Proud.Marshaler.Read(__msg,out AnimSate);	
float Time; Nettention.Proud.Marshaler.Read(__msg,out Time);	
core.PostCheckReadMessage(__msg, RmiName_UpdateActorAnimState);
        if(enableNotifyCallFromStub==true)
        {
        string parameterString = "";
        parameterString+=templeteID.ToString()+",";
parameterString+=AnimSate.ToString()+",";
parameterString+=Time.ToString()+",";
        NotifyCallFromStub(Common.UpdateActorAnimState, RmiName_UpdateActorAnimState,parameterString);
        }

        if(enableStubProfiling)
        {
        Nettention.Proud.BeforeRmiSummary summary = new Nettention.Proud.BeforeRmiSummary();
        summary.rmiID = Common.UpdateActorAnimState;
        summary.rmiName = RmiName_UpdateActorAnimState;
        summary.hostID = remote;
        summary.hostTag = hostTag;
        BeforeRmiInvocation(summary);
        }

        long t0 = Nettention.Proud.PreciseCurrentTime.GetTimeMs();

        // Call this method.
        bool __ret =UpdateActorAnimState (remote,ctx , templeteID, AnimSate, Time );

        if(__ret==false)
        {
        // Error: RMI function that a user did not create has been called. 
        core.ShowNotImplementedRmiWarning(RmiName_UpdateActorAnimState);
        }

        if(enableStubProfiling)
        {
        Nettention.Proud.AfterRmiSummary summary = new Nettention.Proud.AfterRmiSummary();
        summary.rmiID = Common.UpdateActorAnimState;
        summary.rmiName = RmiName_UpdateActorAnimState;
        summary.hostID = remote;
        summary.hostTag = hostTag;
        summary.elapsedTime = Nettention.Proud.PreciseCurrentTime.GetTimeMs()-t0;
        AfterRmiInvocation(summary);
        }
    }
    void ProcessReceivedMessage_OnChat(Nettention.Proud.Message __msg, Nettention.Proud.ReceivedMessage pa, Object hostTag, Nettention.Proud.HostID remote)
    {
        Nettention.Proud.RmiContext ctx = new Nettention.Proud.RmiContext();
        ctx.sentFrom=pa.RemoteHostID;
        ctx.relayed=pa.IsRelayed;
        ctx.hostTag=hostTag;
        ctx.encryptMode = pa.EncryptMode;
        ctx.compressMode = pa.CompressMode;
        ctx.rmiID = Common.OnChat;

        int clientId; Nettention.Proud.Marshaler.Read(__msg,out clientId);	
string message; Nettention.Proud.Marshaler.Read(__msg,out message);	
core.PostCheckReadMessage(__msg, RmiName_OnChat);
        if(enableNotifyCallFromStub==true)
        {
        string parameterString = "";
        parameterString+=clientId.ToString()+",";
parameterString+=message.ToString()+",";
        NotifyCallFromStub(Common.OnChat, RmiName_OnChat,parameterString);
        }

        if(enableStubProfiling)
        {
        Nettention.Proud.BeforeRmiSummary summary = new Nettention.Proud.BeforeRmiSummary();
        summary.rmiID = Common.OnChat;
        summary.rmiName = RmiName_OnChat;
        summary.hostID = remote;
        summary.hostTag = hostTag;
        BeforeRmiInvocation(summary);
        }

        long t0 = Nettention.Proud.PreciseCurrentTime.GetTimeMs();

        // Call this method.
        bool __ret =OnChat (remote,ctx , clientId, message );

        if(__ret==false)
        {
        // Error: RMI function that a user did not create has been called. 
        core.ShowNotImplementedRmiWarning(RmiName_OnChat);
        }

        if(enableStubProfiling)
        {
        Nettention.Proud.AfterRmiSummary summary = new Nettention.Proud.AfterRmiSummary();
        summary.rmiID = Common.OnChat;
        summary.rmiName = RmiName_OnChat;
        summary.hostID = remote;
        summary.hostTag = hostTag;
        summary.elapsedTime = Nettention.Proud.PreciseCurrentTime.GetTimeMs()-t0;
        AfterRmiInvocation(summary);
        }
    }
		#if USE_RMI_NAME_STRING
// RMI name declaration.
// It is the unique pointer that indicates RMI name such as RMI profiler.
public const string RmiName_ResponseLoginEvent="ResponseLoginEvent";
public const string RmiName_ResponseCheckNickname="ResponseCheckNickname";
public const string RmiName_OnPlayerJoined="OnPlayerJoined";
public const string RmiName_OnOtherPlayerUpdated="OnOtherPlayerUpdated";
public const string RmiName_OnOtherPlayerAnimUpdated="OnOtherPlayerAnimUpdated";
public const string RmiName_SpawnObjectEvent="SpawnObjectEvent";
public const string RmiName_OnOtherActorUpdated="OnOtherActorUpdated";
public const string RmiName_OnOtherActorAnimUpdated="OnOtherActorAnimUpdated";
public const string RmiName_OnPositionUpdated="OnPositionUpdated";
public const string RmiName_OnActorPositionUpdated="OnActorPositionUpdated";
public const string RmiName_UpdateCharacterAnimState="UpdateCharacterAnimState";
public const string RmiName_UpdateActorAnimState="UpdateActorAnimState";
public const string RmiName_OnChat="OnChat";
       
public const string RmiName_First = RmiName_ResponseLoginEvent;
		#else
// RMI name declaration.
// It is the unique pointer that indicates RMI name such as RMI profiler.
public const string RmiName_ResponseLoginEvent="";
public const string RmiName_ResponseCheckNickname="";
public const string RmiName_OnPlayerJoined="";
public const string RmiName_OnOtherPlayerUpdated="";
public const string RmiName_OnOtherPlayerAnimUpdated="";
public const string RmiName_SpawnObjectEvent="";
public const string RmiName_OnOtherActorUpdated="";
public const string RmiName_OnOtherActorAnimUpdated="";
public const string RmiName_OnPositionUpdated="";
public const string RmiName_OnActorPositionUpdated="";
public const string RmiName_UpdateCharacterAnimState="";
public const string RmiName_UpdateActorAnimState="";
public const string RmiName_OnChat="";
       
public const string RmiName_First = "";
		#endif

		public override Nettention.Proud.RmiID[] GetRmiIDList { get{return Common.RmiIDList;} }
		
	}
}

