  





// Generated by PIDL compiler.
// Do not modify this file, but modify the source .pidl file.

  
#include "ServerRmi_stub.h"


const unsigned char sz_ServerRmi_stub_hRmi[] = 
{ 0x00, 0x99, 0xaa, 0xbb, 0xcc, 0xdd, 0xff, 0x00, 0x99, 0xaa, 0xbb, 0xcc, 0xdd, 0xff,
0xaa, 0xbb, 0xcc, 0xdd, 0xff,0x99, 0xaa, 0xbb, 0xcc, 0x99, 0xaa, 0xdd, 0xff, 0x00 };   


namespace ServerToClient {


	bool Stub::ProcessReceivedMessage(::Proud::CReceivedMessage &pa, void* hostTag) 
	{
#ifndef __FreeBSD__ 
		{
			// unusable but required. you may ignore it, because it does not occur any worthless load.
			unsigned char x = sz_ServerRmi_stub_hRmi[0]; 
			x++; 
		}
#endif
		::Proud::HostID remote=pa.GetRemoteHostID();
		if(remote==::Proud::HostID_None)
		{
			ShowUnknownHostIDWarning(remote);
		}

		::Proud::CMessage &__msg=pa.GetReadOnlyMessage();
		int orgReadOffset = __msg.GetReadOffset();

		::Proud::RmiID __rmiID;
		if(!__msg.Read(__rmiID))
			goto __fail;
					
		switch((int)__rmiID) // case is to prevent from clang compile error
		{
			case Rmi_ResponseLoginEvent:
				{
					::Proud::RmiContext ctx;
					ctx.m_rmiID = __rmiID;
					ctx.m_sentFrom=pa.GetRemoteHostID();
					ctx.m_relayed=pa.IsRelayed();
					ctx.m_hostTag = hostTag;
					ctx.m_encryptMode = pa.GetEncryptMode();
					ctx.m_compressMode = pa.GetCompressMode();
			
			        if(BeforeDeserialize(remote, ctx, __msg) == false)
			        {
			            // The user don't want to call the RMI function. 
						// So, We fake that it has been already called.
						__msg.SetReadOffset(__msg.GetLength());
			            return true;
			        }
			
					bool bIsSuccess; __msg >> bIsSuccess;
					int ErrorType; __msg >> ErrorType;
					m_core->PostCheckReadMessage(__msg,RmiName_ResponseLoginEvent);
					
			
					if(m_enableNotifyCallFromStub && !m_internalUse)
					{
						::Proud::String parameterString;
						
						::Proud::AppendTextOut(parameterString,bIsSuccess);	
										
						parameterString += _PNT(", ");
						::Proud::AppendTextOut(parameterString,ErrorType);	
						
						NotifyCallFromStub(remote, (::Proud::RmiID)Rmi_ResponseLoginEvent, 
							RmiName_ResponseLoginEvent,parameterString);
			
			#ifdef VIZAGENT
						m_core->Viz_NotifyRecvToStub(remote, (::Proud::RmiID)Rmi_ResponseLoginEvent, 
							RmiName_ResponseLoginEvent, parameterString);
			#endif
					}
					else if(!m_internalUse)
					{
			#ifdef VIZAGENT
						m_core->Viz_NotifyRecvToStub(remote, (::Proud::RmiID)Rmi_ResponseLoginEvent, 
							RmiName_ResponseLoginEvent, _PNT(""));
			#endif
					}
						
					int64_t __t0 = 0;
					if(!m_internalUse && m_enableStubProfiling)
					{
						::Proud::BeforeRmiSummary summary;
						summary.m_rmiID = (::Proud::RmiID)Rmi_ResponseLoginEvent;
						summary.m_rmiName = RmiName_ResponseLoginEvent;
						summary.m_hostID = remote;
						summary.m_hostTag = hostTag;
						BeforeRmiInvocation(summary);
			
						__t0 = ::Proud::GetPreciseCurrentTimeMs();
					}
						
					// Call this method.
					bool __ret = ResponseLoginEvent (remote,ctx , bIsSuccess, ErrorType );
						
					if(__ret==false)
					{
						// Error: RMI function that a user did not create has been called. 
						m_core->ShowNotImplementedRmiWarning(RmiName_ResponseLoginEvent);
					}
						
					if(!m_internalUse && m_enableStubProfiling)
					{
						::Proud::AfterRmiSummary summary;
						summary.m_rmiID = (::Proud::RmiID)Rmi_ResponseLoginEvent;
						summary.m_rmiName = RmiName_ResponseLoginEvent;
						summary.m_hostID = remote;
						summary.m_hostTag = hostTag;
						int64_t __t1;
			
						__t1 = ::Proud::GetPreciseCurrentTimeMs();
			
						summary.m_elapsedTime = (uint32_t)(__t1 - __t0);
						AfterRmiInvocation(summary);
					}
				}
				break;
			case Rmi_ResponseCheckNickname:
				{
					::Proud::RmiContext ctx;
					ctx.m_rmiID = __rmiID;
					ctx.m_sentFrom=pa.GetRemoteHostID();
					ctx.m_relayed=pa.IsRelayed();
					ctx.m_hostTag = hostTag;
					ctx.m_encryptMode = pa.GetEncryptMode();
					ctx.m_compressMode = pa.GetCompressMode();
			
			        if(BeforeDeserialize(remote, ctx, __msg) == false)
			        {
			            // The user don't want to call the RMI function. 
						// So, We fake that it has been already called.
						__msg.SetReadOffset(__msg.GetLength());
			            return true;
			        }
			
					int clientId; __msg >> clientId;
					bool bIsAble; __msg >> bIsAble;
					m_core->PostCheckReadMessage(__msg,RmiName_ResponseCheckNickname);
					
			
					if(m_enableNotifyCallFromStub && !m_internalUse)
					{
						::Proud::String parameterString;
						
						::Proud::AppendTextOut(parameterString,clientId);	
										
						parameterString += _PNT(", ");
						::Proud::AppendTextOut(parameterString,bIsAble);	
						
						NotifyCallFromStub(remote, (::Proud::RmiID)Rmi_ResponseCheckNickname, 
							RmiName_ResponseCheckNickname,parameterString);
			
			#ifdef VIZAGENT
						m_core->Viz_NotifyRecvToStub(remote, (::Proud::RmiID)Rmi_ResponseCheckNickname, 
							RmiName_ResponseCheckNickname, parameterString);
			#endif
					}
					else if(!m_internalUse)
					{
			#ifdef VIZAGENT
						m_core->Viz_NotifyRecvToStub(remote, (::Proud::RmiID)Rmi_ResponseCheckNickname, 
							RmiName_ResponseCheckNickname, _PNT(""));
			#endif
					}
						
					int64_t __t0 = 0;
					if(!m_internalUse && m_enableStubProfiling)
					{
						::Proud::BeforeRmiSummary summary;
						summary.m_rmiID = (::Proud::RmiID)Rmi_ResponseCheckNickname;
						summary.m_rmiName = RmiName_ResponseCheckNickname;
						summary.m_hostID = remote;
						summary.m_hostTag = hostTag;
						BeforeRmiInvocation(summary);
			
						__t0 = ::Proud::GetPreciseCurrentTimeMs();
					}
						
					// Call this method.
					bool __ret = ResponseCheckNickname (remote,ctx , clientId, bIsAble );
						
					if(__ret==false)
					{
						// Error: RMI function that a user did not create has been called. 
						m_core->ShowNotImplementedRmiWarning(RmiName_ResponseCheckNickname);
					}
						
					if(!m_internalUse && m_enableStubProfiling)
					{
						::Proud::AfterRmiSummary summary;
						summary.m_rmiID = (::Proud::RmiID)Rmi_ResponseCheckNickname;
						summary.m_rmiName = RmiName_ResponseCheckNickname;
						summary.m_hostID = remote;
						summary.m_hostTag = hostTag;
						int64_t __t1;
			
						__t1 = ::Proud::GetPreciseCurrentTimeMs();
			
						summary.m_elapsedTime = (uint32_t)(__t1 - __t0);
						AfterRmiInvocation(summary);
					}
				}
				break;
			case Rmi_OnPlayerJoined:
				{
					::Proud::RmiContext ctx;
					ctx.m_rmiID = __rmiID;
					ctx.m_sentFrom=pa.GetRemoteHostID();
					ctx.m_relayed=pa.IsRelayed();
					ctx.m_hostTag = hostTag;
					ctx.m_encryptMode = pa.GetEncryptMode();
					ctx.m_compressMode = pa.GetCompressMode();
			
			        if(BeforeDeserialize(remote, ctx, __msg) == false)
			        {
			            // The user don't want to call the RMI function. 
						// So, We fake that it has been already called.
						__msg.SetReadOffset(__msg.GetLength());
			            return true;
			        }
			
					int clientId; __msg >> clientId;
					string szNickName; __msg >> szNickName;
					float PosX; __msg >> PosX;
					float PosY; __msg >> PosY;
					float PosZ; __msg >> PosZ;
					m_core->PostCheckReadMessage(__msg,RmiName_OnPlayerJoined);
					
			
					if(m_enableNotifyCallFromStub && !m_internalUse)
					{
						::Proud::String parameterString;
						
						::Proud::AppendTextOut(parameterString,clientId);	
										
						parameterString += _PNT(", ");
						::Proud::AppendTextOut(parameterString,szNickName);	
										
						parameterString += _PNT(", ");
						::Proud::AppendTextOut(parameterString,PosX);	
										
						parameterString += _PNT(", ");
						::Proud::AppendTextOut(parameterString,PosY);	
										
						parameterString += _PNT(", ");
						::Proud::AppendTextOut(parameterString,PosZ);	
						
						NotifyCallFromStub(remote, (::Proud::RmiID)Rmi_OnPlayerJoined, 
							RmiName_OnPlayerJoined,parameterString);
			
			#ifdef VIZAGENT
						m_core->Viz_NotifyRecvToStub(remote, (::Proud::RmiID)Rmi_OnPlayerJoined, 
							RmiName_OnPlayerJoined, parameterString);
			#endif
					}
					else if(!m_internalUse)
					{
			#ifdef VIZAGENT
						m_core->Viz_NotifyRecvToStub(remote, (::Proud::RmiID)Rmi_OnPlayerJoined, 
							RmiName_OnPlayerJoined, _PNT(""));
			#endif
					}
						
					int64_t __t0 = 0;
					if(!m_internalUse && m_enableStubProfiling)
					{
						::Proud::BeforeRmiSummary summary;
						summary.m_rmiID = (::Proud::RmiID)Rmi_OnPlayerJoined;
						summary.m_rmiName = RmiName_OnPlayerJoined;
						summary.m_hostID = remote;
						summary.m_hostTag = hostTag;
						BeforeRmiInvocation(summary);
			
						__t0 = ::Proud::GetPreciseCurrentTimeMs();
					}
						
					// Call this method.
					bool __ret = OnPlayerJoined (remote,ctx , clientId, szNickName, PosX, PosY, PosZ );
						
					if(__ret==false)
					{
						// Error: RMI function that a user did not create has been called. 
						m_core->ShowNotImplementedRmiWarning(RmiName_OnPlayerJoined);
					}
						
					if(!m_internalUse && m_enableStubProfiling)
					{
						::Proud::AfterRmiSummary summary;
						summary.m_rmiID = (::Proud::RmiID)Rmi_OnPlayerJoined;
						summary.m_rmiName = RmiName_OnPlayerJoined;
						summary.m_hostID = remote;
						summary.m_hostTag = hostTag;
						int64_t __t1;
			
						__t1 = ::Proud::GetPreciseCurrentTimeMs();
			
						summary.m_elapsedTime = (uint32_t)(__t1 - __t0);
						AfterRmiInvocation(summary);
					}
				}
				break;
			case Rmi_SpawnObjectEvent:
				{
					::Proud::RmiContext ctx;
					ctx.m_rmiID = __rmiID;
					ctx.m_sentFrom=pa.GetRemoteHostID();
					ctx.m_relayed=pa.IsRelayed();
					ctx.m_hostTag = hostTag;
					ctx.m_encryptMode = pa.GetEncryptMode();
					ctx.m_compressMode = pa.GetCompressMode();
			
			        if(BeforeDeserialize(remote, ctx, __msg) == false)
			        {
			            // The user don't want to call the RMI function. 
						// So, We fake that it has been already called.
						__msg.SetReadOffset(__msg.GetLength());
			            return true;
			        }
			
					string Key; __msg >> Key;
					int templetedID; __msg >> templetedID;
					float px; __msg >> px;
					float py; __msg >> py;
					float pz; __msg >> pz;
					m_core->PostCheckReadMessage(__msg,RmiName_SpawnObjectEvent);
					
			
					if(m_enableNotifyCallFromStub && !m_internalUse)
					{
						::Proud::String parameterString;
						
						::Proud::AppendTextOut(parameterString,Key);	
										
						parameterString += _PNT(", ");
						::Proud::AppendTextOut(parameterString,templetedID);	
										
						parameterString += _PNT(", ");
						::Proud::AppendTextOut(parameterString,px);	
										
						parameterString += _PNT(", ");
						::Proud::AppendTextOut(parameterString,py);	
										
						parameterString += _PNT(", ");
						::Proud::AppendTextOut(parameterString,pz);	
						
						NotifyCallFromStub(remote, (::Proud::RmiID)Rmi_SpawnObjectEvent, 
							RmiName_SpawnObjectEvent,parameterString);
			
			#ifdef VIZAGENT
						m_core->Viz_NotifyRecvToStub(remote, (::Proud::RmiID)Rmi_SpawnObjectEvent, 
							RmiName_SpawnObjectEvent, parameterString);
			#endif
					}
					else if(!m_internalUse)
					{
			#ifdef VIZAGENT
						m_core->Viz_NotifyRecvToStub(remote, (::Proud::RmiID)Rmi_SpawnObjectEvent, 
							RmiName_SpawnObjectEvent, _PNT(""));
			#endif
					}
						
					int64_t __t0 = 0;
					if(!m_internalUse && m_enableStubProfiling)
					{
						::Proud::BeforeRmiSummary summary;
						summary.m_rmiID = (::Proud::RmiID)Rmi_SpawnObjectEvent;
						summary.m_rmiName = RmiName_SpawnObjectEvent;
						summary.m_hostID = remote;
						summary.m_hostTag = hostTag;
						BeforeRmiInvocation(summary);
			
						__t0 = ::Proud::GetPreciseCurrentTimeMs();
					}
						
					// Call this method.
					bool __ret = SpawnObjectEvent (remote,ctx , Key, templetedID, px, py, pz );
						
					if(__ret==false)
					{
						// Error: RMI function that a user did not create has been called. 
						m_core->ShowNotImplementedRmiWarning(RmiName_SpawnObjectEvent);
					}
						
					if(!m_internalUse && m_enableStubProfiling)
					{
						::Proud::AfterRmiSummary summary;
						summary.m_rmiID = (::Proud::RmiID)Rmi_SpawnObjectEvent;
						summary.m_rmiName = RmiName_SpawnObjectEvent;
						summary.m_hostID = remote;
						summary.m_hostTag = hostTag;
						int64_t __t1;
			
						__t1 = ::Proud::GetPreciseCurrentTimeMs();
			
						summary.m_elapsedTime = (uint32_t)(__t1 - __t0);
						AfterRmiInvocation(summary);
					}
				}
				break;
			case Rmi_OtherPlayerTransformUpdated:
				{
					::Proud::RmiContext ctx;
					ctx.m_rmiID = __rmiID;
					ctx.m_sentFrom=pa.GetRemoteHostID();
					ctx.m_relayed=pa.IsRelayed();
					ctx.m_hostTag = hostTag;
					ctx.m_encryptMode = pa.GetEncryptMode();
					ctx.m_compressMode = pa.GetCompressMode();
			
			        if(BeforeDeserialize(remote, ctx, __msg) == false)
			        {
			            // The user don't want to call the RMI function. 
						// So, We fake that it has been already called.
						__msg.SetReadOffset(__msg.GetLength());
			            return true;
			        }
			
					int ClientID; __msg >> ClientID;
					string NickName; __msg >> NickName;
					float ScaleX; __msg >> ScaleX;
					float ScaleY; __msg >> ScaleY;
					float ScaleZ; __msg >> ScaleZ;
					float AngleX; __msg >> AngleX;
					float AngleY; __msg >> AngleY;
					float AngleZ; __msg >> AngleZ;
					float AngleW; __msg >> AngleW;
					float PosX; __msg >> PosX;
					float PosY; __msg >> PosY;
					float PosZ; __msg >> PosZ;
					m_core->PostCheckReadMessage(__msg,RmiName_OtherPlayerTransformUpdated);
					
			
					if(m_enableNotifyCallFromStub && !m_internalUse)
					{
						::Proud::String parameterString;
						
						::Proud::AppendTextOut(parameterString,ClientID);	
										
						parameterString += _PNT(", ");
						::Proud::AppendTextOut(parameterString,NickName);	
										
						parameterString += _PNT(", ");
						::Proud::AppendTextOut(parameterString,ScaleX);	
										
						parameterString += _PNT(", ");
						::Proud::AppendTextOut(parameterString,ScaleY);	
										
						parameterString += _PNT(", ");
						::Proud::AppendTextOut(parameterString,ScaleZ);	
										
						parameterString += _PNT(", ");
						::Proud::AppendTextOut(parameterString,AngleX);	
										
						parameterString += _PNT(", ");
						::Proud::AppendTextOut(parameterString,AngleY);	
										
						parameterString += _PNT(", ");
						::Proud::AppendTextOut(parameterString,AngleZ);	
										
						parameterString += _PNT(", ");
						::Proud::AppendTextOut(parameterString,AngleW);	
										
						parameterString += _PNT(", ");
						::Proud::AppendTextOut(parameterString,PosX);	
										
						parameterString += _PNT(", ");
						::Proud::AppendTextOut(parameterString,PosY);	
										
						parameterString += _PNT(", ");
						::Proud::AppendTextOut(parameterString,PosZ);	
						
						NotifyCallFromStub(remote, (::Proud::RmiID)Rmi_OtherPlayerTransformUpdated, 
							RmiName_OtherPlayerTransformUpdated,parameterString);
			
			#ifdef VIZAGENT
						m_core->Viz_NotifyRecvToStub(remote, (::Proud::RmiID)Rmi_OtherPlayerTransformUpdated, 
							RmiName_OtherPlayerTransformUpdated, parameterString);
			#endif
					}
					else if(!m_internalUse)
					{
			#ifdef VIZAGENT
						m_core->Viz_NotifyRecvToStub(remote, (::Proud::RmiID)Rmi_OtherPlayerTransformUpdated, 
							RmiName_OtherPlayerTransformUpdated, _PNT(""));
			#endif
					}
						
					int64_t __t0 = 0;
					if(!m_internalUse && m_enableStubProfiling)
					{
						::Proud::BeforeRmiSummary summary;
						summary.m_rmiID = (::Proud::RmiID)Rmi_OtherPlayerTransformUpdated;
						summary.m_rmiName = RmiName_OtherPlayerTransformUpdated;
						summary.m_hostID = remote;
						summary.m_hostTag = hostTag;
						BeforeRmiInvocation(summary);
			
						__t0 = ::Proud::GetPreciseCurrentTimeMs();
					}
						
					// Call this method.
					bool __ret = OtherPlayerTransformUpdated (remote,ctx , ClientID, NickName, ScaleX, ScaleY, ScaleZ, AngleX, AngleY, AngleZ, AngleW, PosX, PosY, PosZ );
						
					if(__ret==false)
					{
						// Error: RMI function that a user did not create has been called. 
						m_core->ShowNotImplementedRmiWarning(RmiName_OtherPlayerTransformUpdated);
					}
						
					if(!m_internalUse && m_enableStubProfiling)
					{
						::Proud::AfterRmiSummary summary;
						summary.m_rmiID = (::Proud::RmiID)Rmi_OtherPlayerTransformUpdated;
						summary.m_rmiName = RmiName_OtherPlayerTransformUpdated;
						summary.m_hostID = remote;
						summary.m_hostTag = hostTag;
						int64_t __t1;
			
						__t1 = ::Proud::GetPreciseCurrentTimeMs();
			
						summary.m_elapsedTime = (uint32_t)(__t1 - __t0);
						AfterRmiInvocation(summary);
					}
				}
				break;
			case Rmi_OnPlayerTransformUpdated:
				{
					::Proud::RmiContext ctx;
					ctx.m_rmiID = __rmiID;
					ctx.m_sentFrom=pa.GetRemoteHostID();
					ctx.m_relayed=pa.IsRelayed();
					ctx.m_hostTag = hostTag;
					ctx.m_encryptMode = pa.GetEncryptMode();
					ctx.m_compressMode = pa.GetCompressMode();
			
			        if(BeforeDeserialize(remote, ctx, __msg) == false)
			        {
			            // The user don't want to call the RMI function. 
						// So, We fake that it has been already called.
						__msg.SetReadOffset(__msg.GetLength());
			            return true;
			        }
			
					int clientId; __msg >> clientId;
					float ScaleX; __msg >> ScaleX;
					float ScaleY; __msg >> ScaleY;
					float ScaleZ; __msg >> ScaleZ;
					float AngleX; __msg >> AngleX;
					float AngleY; __msg >> AngleY;
					float AngleZ; __msg >> AngleZ;
					float AngleW; __msg >> AngleW;
					float PosX; __msg >> PosX;
					float PosY; __msg >> PosY;
					float PosZ; __msg >> PosZ;
					m_core->PostCheckReadMessage(__msg,RmiName_OnPlayerTransformUpdated);
					
			
					if(m_enableNotifyCallFromStub && !m_internalUse)
					{
						::Proud::String parameterString;
						
						::Proud::AppendTextOut(parameterString,clientId);	
										
						parameterString += _PNT(", ");
						::Proud::AppendTextOut(parameterString,ScaleX);	
										
						parameterString += _PNT(", ");
						::Proud::AppendTextOut(parameterString,ScaleY);	
										
						parameterString += _PNT(", ");
						::Proud::AppendTextOut(parameterString,ScaleZ);	
										
						parameterString += _PNT(", ");
						::Proud::AppendTextOut(parameterString,AngleX);	
										
						parameterString += _PNT(", ");
						::Proud::AppendTextOut(parameterString,AngleY);	
										
						parameterString += _PNT(", ");
						::Proud::AppendTextOut(parameterString,AngleZ);	
										
						parameterString += _PNT(", ");
						::Proud::AppendTextOut(parameterString,AngleW);	
										
						parameterString += _PNT(", ");
						::Proud::AppendTextOut(parameterString,PosX);	
										
						parameterString += _PNT(", ");
						::Proud::AppendTextOut(parameterString,PosY);	
										
						parameterString += _PNT(", ");
						::Proud::AppendTextOut(parameterString,PosZ);	
						
						NotifyCallFromStub(remote, (::Proud::RmiID)Rmi_OnPlayerTransformUpdated, 
							RmiName_OnPlayerTransformUpdated,parameterString);
			
			#ifdef VIZAGENT
						m_core->Viz_NotifyRecvToStub(remote, (::Proud::RmiID)Rmi_OnPlayerTransformUpdated, 
							RmiName_OnPlayerTransformUpdated, parameterString);
			#endif
					}
					else if(!m_internalUse)
					{
			#ifdef VIZAGENT
						m_core->Viz_NotifyRecvToStub(remote, (::Proud::RmiID)Rmi_OnPlayerTransformUpdated, 
							RmiName_OnPlayerTransformUpdated, _PNT(""));
			#endif
					}
						
					int64_t __t0 = 0;
					if(!m_internalUse && m_enableStubProfiling)
					{
						::Proud::BeforeRmiSummary summary;
						summary.m_rmiID = (::Proud::RmiID)Rmi_OnPlayerTransformUpdated;
						summary.m_rmiName = RmiName_OnPlayerTransformUpdated;
						summary.m_hostID = remote;
						summary.m_hostTag = hostTag;
						BeforeRmiInvocation(summary);
			
						__t0 = ::Proud::GetPreciseCurrentTimeMs();
					}
						
					// Call this method.
					bool __ret = OnPlayerTransformUpdated (remote,ctx , clientId, ScaleX, ScaleY, ScaleZ, AngleX, AngleY, AngleZ, AngleW, PosX, PosY, PosZ );
						
					if(__ret==false)
					{
						// Error: RMI function that a user did not create has been called. 
						m_core->ShowNotImplementedRmiWarning(RmiName_OnPlayerTransformUpdated);
					}
						
					if(!m_internalUse && m_enableStubProfiling)
					{
						::Proud::AfterRmiSummary summary;
						summary.m_rmiID = (::Proud::RmiID)Rmi_OnPlayerTransformUpdated;
						summary.m_rmiName = RmiName_OnPlayerTransformUpdated;
						summary.m_hostID = remote;
						summary.m_hostTag = hostTag;
						int64_t __t1;
			
						__t1 = ::Proud::GetPreciseCurrentTimeMs();
			
						summary.m_elapsedTime = (uint32_t)(__t1 - __t0);
						AfterRmiInvocation(summary);
					}
				}
				break;
			case Rmi_OtherActorTransformUpdated:
				{
					::Proud::RmiContext ctx;
					ctx.m_rmiID = __rmiID;
					ctx.m_sentFrom=pa.GetRemoteHostID();
					ctx.m_relayed=pa.IsRelayed();
					ctx.m_hostTag = hostTag;
					ctx.m_encryptMode = pa.GetEncryptMode();
					ctx.m_compressMode = pa.GetCompressMode();
			
			        if(BeforeDeserialize(remote, ctx, __msg) == false)
			        {
			            // The user don't want to call the RMI function. 
						// So, We fake that it has been already called.
						__msg.SetReadOffset(__msg.GetLength());
			            return true;
			        }
			
					int templeteID; __msg >> templeteID;
					float ScaleX; __msg >> ScaleX;
					float ScaleY; __msg >> ScaleY;
					float ScaleZ; __msg >> ScaleZ;
					float AngleX; __msg >> AngleX;
					float AngleY; __msg >> AngleY;
					float AngleZ; __msg >> AngleZ;
					float AngleW; __msg >> AngleW;
					float PosX; __msg >> PosX;
					float PosY; __msg >> PosY;
					float PosZ; __msg >> PosZ;
					m_core->PostCheckReadMessage(__msg,RmiName_OtherActorTransformUpdated);
					
			
					if(m_enableNotifyCallFromStub && !m_internalUse)
					{
						::Proud::String parameterString;
						
						::Proud::AppendTextOut(parameterString,templeteID);	
										
						parameterString += _PNT(", ");
						::Proud::AppendTextOut(parameterString,ScaleX);	
										
						parameterString += _PNT(", ");
						::Proud::AppendTextOut(parameterString,ScaleY);	
										
						parameterString += _PNT(", ");
						::Proud::AppendTextOut(parameterString,ScaleZ);	
										
						parameterString += _PNT(", ");
						::Proud::AppendTextOut(parameterString,AngleX);	
										
						parameterString += _PNT(", ");
						::Proud::AppendTextOut(parameterString,AngleY);	
										
						parameterString += _PNT(", ");
						::Proud::AppendTextOut(parameterString,AngleZ);	
										
						parameterString += _PNT(", ");
						::Proud::AppendTextOut(parameterString,AngleW);	
										
						parameterString += _PNT(", ");
						::Proud::AppendTextOut(parameterString,PosX);	
										
						parameterString += _PNT(", ");
						::Proud::AppendTextOut(parameterString,PosY);	
										
						parameterString += _PNT(", ");
						::Proud::AppendTextOut(parameterString,PosZ);	
						
						NotifyCallFromStub(remote, (::Proud::RmiID)Rmi_OtherActorTransformUpdated, 
							RmiName_OtherActorTransformUpdated,parameterString);
			
			#ifdef VIZAGENT
						m_core->Viz_NotifyRecvToStub(remote, (::Proud::RmiID)Rmi_OtherActorTransformUpdated, 
							RmiName_OtherActorTransformUpdated, parameterString);
			#endif
					}
					else if(!m_internalUse)
					{
			#ifdef VIZAGENT
						m_core->Viz_NotifyRecvToStub(remote, (::Proud::RmiID)Rmi_OtherActorTransformUpdated, 
							RmiName_OtherActorTransformUpdated, _PNT(""));
			#endif
					}
						
					int64_t __t0 = 0;
					if(!m_internalUse && m_enableStubProfiling)
					{
						::Proud::BeforeRmiSummary summary;
						summary.m_rmiID = (::Proud::RmiID)Rmi_OtherActorTransformUpdated;
						summary.m_rmiName = RmiName_OtherActorTransformUpdated;
						summary.m_hostID = remote;
						summary.m_hostTag = hostTag;
						BeforeRmiInvocation(summary);
			
						__t0 = ::Proud::GetPreciseCurrentTimeMs();
					}
						
					// Call this method.
					bool __ret = OtherActorTransformUpdated (remote,ctx , templeteID, ScaleX, ScaleY, ScaleZ, AngleX, AngleY, AngleZ, AngleW, PosX, PosY, PosZ );
						
					if(__ret==false)
					{
						// Error: RMI function that a user did not create has been called. 
						m_core->ShowNotImplementedRmiWarning(RmiName_OtherActorTransformUpdated);
					}
						
					if(!m_internalUse && m_enableStubProfiling)
					{
						::Proud::AfterRmiSummary summary;
						summary.m_rmiID = (::Proud::RmiID)Rmi_OtherActorTransformUpdated;
						summary.m_rmiName = RmiName_OtherActorTransformUpdated;
						summary.m_hostID = remote;
						summary.m_hostTag = hostTag;
						int64_t __t1;
			
						__t1 = ::Proud::GetPreciseCurrentTimeMs();
			
						summary.m_elapsedTime = (uint32_t)(__t1 - __t0);
						AfterRmiInvocation(summary);
					}
				}
				break;
			case Rmi_ActorTransformUpdated:
				{
					::Proud::RmiContext ctx;
					ctx.m_rmiID = __rmiID;
					ctx.m_sentFrom=pa.GetRemoteHostID();
					ctx.m_relayed=pa.IsRelayed();
					ctx.m_hostTag = hostTag;
					ctx.m_encryptMode = pa.GetEncryptMode();
					ctx.m_compressMode = pa.GetCompressMode();
			
			        if(BeforeDeserialize(remote, ctx, __msg) == false)
			        {
			            // The user don't want to call the RMI function. 
						// So, We fake that it has been already called.
						__msg.SetReadOffset(__msg.GetLength());
			            return true;
			        }
			
					int templeteID; __msg >> templeteID;
					float ScaleX; __msg >> ScaleX;
					float ScaleY; __msg >> ScaleY;
					float ScaleZ; __msg >> ScaleZ;
					float AngleX; __msg >> AngleX;
					float AngleY; __msg >> AngleY;
					float AngleZ; __msg >> AngleZ;
					float AngleW; __msg >> AngleW;
					float PosX; __msg >> PosX;
					float PosY; __msg >> PosY;
					float PosZ; __msg >> PosZ;
					m_core->PostCheckReadMessage(__msg,RmiName_ActorTransformUpdated);
					
			
					if(m_enableNotifyCallFromStub && !m_internalUse)
					{
						::Proud::String parameterString;
						
						::Proud::AppendTextOut(parameterString,templeteID);	
										
						parameterString += _PNT(", ");
						::Proud::AppendTextOut(parameterString,ScaleX);	
										
						parameterString += _PNT(", ");
						::Proud::AppendTextOut(parameterString,ScaleY);	
										
						parameterString += _PNT(", ");
						::Proud::AppendTextOut(parameterString,ScaleZ);	
										
						parameterString += _PNT(", ");
						::Proud::AppendTextOut(parameterString,AngleX);	
										
						parameterString += _PNT(", ");
						::Proud::AppendTextOut(parameterString,AngleY);	
										
						parameterString += _PNT(", ");
						::Proud::AppendTextOut(parameterString,AngleZ);	
										
						parameterString += _PNT(", ");
						::Proud::AppendTextOut(parameterString,AngleW);	
										
						parameterString += _PNT(", ");
						::Proud::AppendTextOut(parameterString,PosX);	
										
						parameterString += _PNT(", ");
						::Proud::AppendTextOut(parameterString,PosY);	
										
						parameterString += _PNT(", ");
						::Proud::AppendTextOut(parameterString,PosZ);	
						
						NotifyCallFromStub(remote, (::Proud::RmiID)Rmi_ActorTransformUpdated, 
							RmiName_ActorTransformUpdated,parameterString);
			
			#ifdef VIZAGENT
						m_core->Viz_NotifyRecvToStub(remote, (::Proud::RmiID)Rmi_ActorTransformUpdated, 
							RmiName_ActorTransformUpdated, parameterString);
			#endif
					}
					else if(!m_internalUse)
					{
			#ifdef VIZAGENT
						m_core->Viz_NotifyRecvToStub(remote, (::Proud::RmiID)Rmi_ActorTransformUpdated, 
							RmiName_ActorTransformUpdated, _PNT(""));
			#endif
					}
						
					int64_t __t0 = 0;
					if(!m_internalUse && m_enableStubProfiling)
					{
						::Proud::BeforeRmiSummary summary;
						summary.m_rmiID = (::Proud::RmiID)Rmi_ActorTransformUpdated;
						summary.m_rmiName = RmiName_ActorTransformUpdated;
						summary.m_hostID = remote;
						summary.m_hostTag = hostTag;
						BeforeRmiInvocation(summary);
			
						__t0 = ::Proud::GetPreciseCurrentTimeMs();
					}
						
					// Call this method.
					bool __ret = ActorTransformUpdated (remote,ctx , templeteID, ScaleX, ScaleY, ScaleZ, AngleX, AngleY, AngleZ, AngleW, PosX, PosY, PosZ );
						
					if(__ret==false)
					{
						// Error: RMI function that a user did not create has been called. 
						m_core->ShowNotImplementedRmiWarning(RmiName_ActorTransformUpdated);
					}
						
					if(!m_internalUse && m_enableStubProfiling)
					{
						::Proud::AfterRmiSummary summary;
						summary.m_rmiID = (::Proud::RmiID)Rmi_ActorTransformUpdated;
						summary.m_rmiName = RmiName_ActorTransformUpdated;
						summary.m_hostID = remote;
						summary.m_hostTag = hostTag;
						int64_t __t1;
			
						__t1 = ::Proud::GetPreciseCurrentTimeMs();
			
						summary.m_elapsedTime = (uint32_t)(__t1 - __t0);
						AfterRmiInvocation(summary);
					}
				}
				break;
			case Rmi_UpdateCharacterAnimState:
				{
					::Proud::RmiContext ctx;
					ctx.m_rmiID = __rmiID;
					ctx.m_sentFrom=pa.GetRemoteHostID();
					ctx.m_relayed=pa.IsRelayed();
					ctx.m_hostTag = hostTag;
					ctx.m_encryptMode = pa.GetEncryptMode();
					ctx.m_compressMode = pa.GetCompressMode();
			
			        if(BeforeDeserialize(remote, ctx, __msg) == false)
			        {
			            // The user don't want to call the RMI function. 
						// So, We fake that it has been already called.
						__msg.SetReadOffset(__msg.GetLength());
			            return true;
			        }
			
					int clientId; __msg >> clientId;
					int AnimSate; __msg >> AnimSate;
					float Time; __msg >> Time;
					m_core->PostCheckReadMessage(__msg,RmiName_UpdateCharacterAnimState);
					
			
					if(m_enableNotifyCallFromStub && !m_internalUse)
					{
						::Proud::String parameterString;
						
						::Proud::AppendTextOut(parameterString,clientId);	
										
						parameterString += _PNT(", ");
						::Proud::AppendTextOut(parameterString,AnimSate);	
										
						parameterString += _PNT(", ");
						::Proud::AppendTextOut(parameterString,Time);	
						
						NotifyCallFromStub(remote, (::Proud::RmiID)Rmi_UpdateCharacterAnimState, 
							RmiName_UpdateCharacterAnimState,parameterString);
			
			#ifdef VIZAGENT
						m_core->Viz_NotifyRecvToStub(remote, (::Proud::RmiID)Rmi_UpdateCharacterAnimState, 
							RmiName_UpdateCharacterAnimState, parameterString);
			#endif
					}
					else if(!m_internalUse)
					{
			#ifdef VIZAGENT
						m_core->Viz_NotifyRecvToStub(remote, (::Proud::RmiID)Rmi_UpdateCharacterAnimState, 
							RmiName_UpdateCharacterAnimState, _PNT(""));
			#endif
					}
						
					int64_t __t0 = 0;
					if(!m_internalUse && m_enableStubProfiling)
					{
						::Proud::BeforeRmiSummary summary;
						summary.m_rmiID = (::Proud::RmiID)Rmi_UpdateCharacterAnimState;
						summary.m_rmiName = RmiName_UpdateCharacterAnimState;
						summary.m_hostID = remote;
						summary.m_hostTag = hostTag;
						BeforeRmiInvocation(summary);
			
						__t0 = ::Proud::GetPreciseCurrentTimeMs();
					}
						
					// Call this method.
					bool __ret = UpdateCharacterAnimState (remote,ctx , clientId, AnimSate, Time );
						
					if(__ret==false)
					{
						// Error: RMI function that a user did not create has been called. 
						m_core->ShowNotImplementedRmiWarning(RmiName_UpdateCharacterAnimState);
					}
						
					if(!m_internalUse && m_enableStubProfiling)
					{
						::Proud::AfterRmiSummary summary;
						summary.m_rmiID = (::Proud::RmiID)Rmi_UpdateCharacterAnimState;
						summary.m_rmiName = RmiName_UpdateCharacterAnimState;
						summary.m_hostID = remote;
						summary.m_hostTag = hostTag;
						int64_t __t1;
			
						__t1 = ::Proud::GetPreciseCurrentTimeMs();
			
						summary.m_elapsedTime = (uint32_t)(__t1 - __t0);
						AfterRmiInvocation(summary);
					}
				}
				break;
			case Rmi_OnOtherPlayerAnimUpdated:
				{
					::Proud::RmiContext ctx;
					ctx.m_rmiID = __rmiID;
					ctx.m_sentFrom=pa.GetRemoteHostID();
					ctx.m_relayed=pa.IsRelayed();
					ctx.m_hostTag = hostTag;
					ctx.m_encryptMode = pa.GetEncryptMode();
					ctx.m_compressMode = pa.GetCompressMode();
			
			        if(BeforeDeserialize(remote, ctx, __msg) == false)
			        {
			            // The user don't want to call the RMI function. 
						// So, We fake that it has been already called.
						__msg.SetReadOffset(__msg.GetLength());
			            return true;
			        }
			
					int ClientID; __msg >> ClientID;
					int AnimState; __msg >> AnimState;
					int AnimTime; __msg >> AnimTime;
					m_core->PostCheckReadMessage(__msg,RmiName_OnOtherPlayerAnimUpdated);
					
			
					if(m_enableNotifyCallFromStub && !m_internalUse)
					{
						::Proud::String parameterString;
						
						::Proud::AppendTextOut(parameterString,ClientID);	
										
						parameterString += _PNT(", ");
						::Proud::AppendTextOut(parameterString,AnimState);	
										
						parameterString += _PNT(", ");
						::Proud::AppendTextOut(parameterString,AnimTime);	
						
						NotifyCallFromStub(remote, (::Proud::RmiID)Rmi_OnOtherPlayerAnimUpdated, 
							RmiName_OnOtherPlayerAnimUpdated,parameterString);
			
			#ifdef VIZAGENT
						m_core->Viz_NotifyRecvToStub(remote, (::Proud::RmiID)Rmi_OnOtherPlayerAnimUpdated, 
							RmiName_OnOtherPlayerAnimUpdated, parameterString);
			#endif
					}
					else if(!m_internalUse)
					{
			#ifdef VIZAGENT
						m_core->Viz_NotifyRecvToStub(remote, (::Proud::RmiID)Rmi_OnOtherPlayerAnimUpdated, 
							RmiName_OnOtherPlayerAnimUpdated, _PNT(""));
			#endif
					}
						
					int64_t __t0 = 0;
					if(!m_internalUse && m_enableStubProfiling)
					{
						::Proud::BeforeRmiSummary summary;
						summary.m_rmiID = (::Proud::RmiID)Rmi_OnOtherPlayerAnimUpdated;
						summary.m_rmiName = RmiName_OnOtherPlayerAnimUpdated;
						summary.m_hostID = remote;
						summary.m_hostTag = hostTag;
						BeforeRmiInvocation(summary);
			
						__t0 = ::Proud::GetPreciseCurrentTimeMs();
					}
						
					// Call this method.
					bool __ret = OnOtherPlayerAnimUpdated (remote,ctx , ClientID, AnimState, AnimTime );
						
					if(__ret==false)
					{
						// Error: RMI function that a user did not create has been called. 
						m_core->ShowNotImplementedRmiWarning(RmiName_OnOtherPlayerAnimUpdated);
					}
						
					if(!m_internalUse && m_enableStubProfiling)
					{
						::Proud::AfterRmiSummary summary;
						summary.m_rmiID = (::Proud::RmiID)Rmi_OnOtherPlayerAnimUpdated;
						summary.m_rmiName = RmiName_OnOtherPlayerAnimUpdated;
						summary.m_hostID = remote;
						summary.m_hostTag = hostTag;
						int64_t __t1;
			
						__t1 = ::Proud::GetPreciseCurrentTimeMs();
			
						summary.m_elapsedTime = (uint32_t)(__t1 - __t0);
						AfterRmiInvocation(summary);
					}
				}
				break;
			case Rmi_UpdateActorAnimState:
				{
					::Proud::RmiContext ctx;
					ctx.m_rmiID = __rmiID;
					ctx.m_sentFrom=pa.GetRemoteHostID();
					ctx.m_relayed=pa.IsRelayed();
					ctx.m_hostTag = hostTag;
					ctx.m_encryptMode = pa.GetEncryptMode();
					ctx.m_compressMode = pa.GetCompressMode();
			
			        if(BeforeDeserialize(remote, ctx, __msg) == false)
			        {
			            // The user don't want to call the RMI function. 
						// So, We fake that it has been already called.
						__msg.SetReadOffset(__msg.GetLength());
			            return true;
			        }
			
					int templeteID; __msg >> templeteID;
					int AnimSate; __msg >> AnimSate;
					float Time; __msg >> Time;
					m_core->PostCheckReadMessage(__msg,RmiName_UpdateActorAnimState);
					
			
					if(m_enableNotifyCallFromStub && !m_internalUse)
					{
						::Proud::String parameterString;
						
						::Proud::AppendTextOut(parameterString,templeteID);	
										
						parameterString += _PNT(", ");
						::Proud::AppendTextOut(parameterString,AnimSate);	
										
						parameterString += _PNT(", ");
						::Proud::AppendTextOut(parameterString,Time);	
						
						NotifyCallFromStub(remote, (::Proud::RmiID)Rmi_UpdateActorAnimState, 
							RmiName_UpdateActorAnimState,parameterString);
			
			#ifdef VIZAGENT
						m_core->Viz_NotifyRecvToStub(remote, (::Proud::RmiID)Rmi_UpdateActorAnimState, 
							RmiName_UpdateActorAnimState, parameterString);
			#endif
					}
					else if(!m_internalUse)
					{
			#ifdef VIZAGENT
						m_core->Viz_NotifyRecvToStub(remote, (::Proud::RmiID)Rmi_UpdateActorAnimState, 
							RmiName_UpdateActorAnimState, _PNT(""));
			#endif
					}
						
					int64_t __t0 = 0;
					if(!m_internalUse && m_enableStubProfiling)
					{
						::Proud::BeforeRmiSummary summary;
						summary.m_rmiID = (::Proud::RmiID)Rmi_UpdateActorAnimState;
						summary.m_rmiName = RmiName_UpdateActorAnimState;
						summary.m_hostID = remote;
						summary.m_hostTag = hostTag;
						BeforeRmiInvocation(summary);
			
						__t0 = ::Proud::GetPreciseCurrentTimeMs();
					}
						
					// Call this method.
					bool __ret = UpdateActorAnimState (remote,ctx , templeteID, AnimSate, Time );
						
					if(__ret==false)
					{
						// Error: RMI function that a user did not create has been called. 
						m_core->ShowNotImplementedRmiWarning(RmiName_UpdateActorAnimState);
					}
						
					if(!m_internalUse && m_enableStubProfiling)
					{
						::Proud::AfterRmiSummary summary;
						summary.m_rmiID = (::Proud::RmiID)Rmi_UpdateActorAnimState;
						summary.m_rmiName = RmiName_UpdateActorAnimState;
						summary.m_hostID = remote;
						summary.m_hostTag = hostTag;
						int64_t __t1;
			
						__t1 = ::Proud::GetPreciseCurrentTimeMs();
			
						summary.m_elapsedTime = (uint32_t)(__t1 - __t0);
						AfterRmiInvocation(summary);
					}
				}
				break;
			case Rmi_OnOtherActorAnimUpdated:
				{
					::Proud::RmiContext ctx;
					ctx.m_rmiID = __rmiID;
					ctx.m_sentFrom=pa.GetRemoteHostID();
					ctx.m_relayed=pa.IsRelayed();
					ctx.m_hostTag = hostTag;
					ctx.m_encryptMode = pa.GetEncryptMode();
					ctx.m_compressMode = pa.GetCompressMode();
			
			        if(BeforeDeserialize(remote, ctx, __msg) == false)
			        {
			            // The user don't want to call the RMI function. 
						// So, We fake that it has been already called.
						__msg.SetReadOffset(__msg.GetLength());
			            return true;
			        }
			
					int templeteID; __msg >> templeteID;
					int AnimState; __msg >> AnimState;
					int AnimTime; __msg >> AnimTime;
					m_core->PostCheckReadMessage(__msg,RmiName_OnOtherActorAnimUpdated);
					
			
					if(m_enableNotifyCallFromStub && !m_internalUse)
					{
						::Proud::String parameterString;
						
						::Proud::AppendTextOut(parameterString,templeteID);	
										
						parameterString += _PNT(", ");
						::Proud::AppendTextOut(parameterString,AnimState);	
										
						parameterString += _PNT(", ");
						::Proud::AppendTextOut(parameterString,AnimTime);	
						
						NotifyCallFromStub(remote, (::Proud::RmiID)Rmi_OnOtherActorAnimUpdated, 
							RmiName_OnOtherActorAnimUpdated,parameterString);
			
			#ifdef VIZAGENT
						m_core->Viz_NotifyRecvToStub(remote, (::Proud::RmiID)Rmi_OnOtherActorAnimUpdated, 
							RmiName_OnOtherActorAnimUpdated, parameterString);
			#endif
					}
					else if(!m_internalUse)
					{
			#ifdef VIZAGENT
						m_core->Viz_NotifyRecvToStub(remote, (::Proud::RmiID)Rmi_OnOtherActorAnimUpdated, 
							RmiName_OnOtherActorAnimUpdated, _PNT(""));
			#endif
					}
						
					int64_t __t0 = 0;
					if(!m_internalUse && m_enableStubProfiling)
					{
						::Proud::BeforeRmiSummary summary;
						summary.m_rmiID = (::Proud::RmiID)Rmi_OnOtherActorAnimUpdated;
						summary.m_rmiName = RmiName_OnOtherActorAnimUpdated;
						summary.m_hostID = remote;
						summary.m_hostTag = hostTag;
						BeforeRmiInvocation(summary);
			
						__t0 = ::Proud::GetPreciseCurrentTimeMs();
					}
						
					// Call this method.
					bool __ret = OnOtherActorAnimUpdated (remote,ctx , templeteID, AnimState, AnimTime );
						
					if(__ret==false)
					{
						// Error: RMI function that a user did not create has been called. 
						m_core->ShowNotImplementedRmiWarning(RmiName_OnOtherActorAnimUpdated);
					}
						
					if(!m_internalUse && m_enableStubProfiling)
					{
						::Proud::AfterRmiSummary summary;
						summary.m_rmiID = (::Proud::RmiID)Rmi_OnOtherActorAnimUpdated;
						summary.m_rmiName = RmiName_OnOtherActorAnimUpdated;
						summary.m_hostID = remote;
						summary.m_hostTag = hostTag;
						int64_t __t1;
			
						__t1 = ::Proud::GetPreciseCurrentTimeMs();
			
						summary.m_elapsedTime = (uint32_t)(__t1 - __t0);
						AfterRmiInvocation(summary);
					}
				}
				break;
			case Rmi_Request_AddItem:
				{
					::Proud::RmiContext ctx;
					ctx.m_rmiID = __rmiID;
					ctx.m_sentFrom=pa.GetRemoteHostID();
					ctx.m_relayed=pa.IsRelayed();
					ctx.m_hostTag = hostTag;
					ctx.m_encryptMode = pa.GetEncryptMode();
					ctx.m_compressMode = pa.GetCompressMode();
			
			        if(BeforeDeserialize(remote, ctx, __msg) == false)
			        {
			            // The user don't want to call the RMI function. 
						// So, We fake that it has been already called.
						__msg.SetReadOffset(__msg.GetLength());
			            return true;
			        }
			
					int iClientID; __msg >> iClientID;
					int iItemID; __msg >> iItemID;
					int iItemCount; __msg >> iItemCount;
					m_core->PostCheckReadMessage(__msg,RmiName_Request_AddItem);
					
			
					if(m_enableNotifyCallFromStub && !m_internalUse)
					{
						::Proud::String parameterString;
						
						::Proud::AppendTextOut(parameterString,iClientID);	
										
						parameterString += _PNT(", ");
						::Proud::AppendTextOut(parameterString,iItemID);	
										
						parameterString += _PNT(", ");
						::Proud::AppendTextOut(parameterString,iItemCount);	
						
						NotifyCallFromStub(remote, (::Proud::RmiID)Rmi_Request_AddItem, 
							RmiName_Request_AddItem,parameterString);
			
			#ifdef VIZAGENT
						m_core->Viz_NotifyRecvToStub(remote, (::Proud::RmiID)Rmi_Request_AddItem, 
							RmiName_Request_AddItem, parameterString);
			#endif
					}
					else if(!m_internalUse)
					{
			#ifdef VIZAGENT
						m_core->Viz_NotifyRecvToStub(remote, (::Proud::RmiID)Rmi_Request_AddItem, 
							RmiName_Request_AddItem, _PNT(""));
			#endif
					}
						
					int64_t __t0 = 0;
					if(!m_internalUse && m_enableStubProfiling)
					{
						::Proud::BeforeRmiSummary summary;
						summary.m_rmiID = (::Proud::RmiID)Rmi_Request_AddItem;
						summary.m_rmiName = RmiName_Request_AddItem;
						summary.m_hostID = remote;
						summary.m_hostTag = hostTag;
						BeforeRmiInvocation(summary);
			
						__t0 = ::Proud::GetPreciseCurrentTimeMs();
					}
						
					// Call this method.
					bool __ret = Request_AddItem (remote,ctx , iClientID, iItemID, iItemCount );
						
					if(__ret==false)
					{
						// Error: RMI function that a user did not create has been called. 
						m_core->ShowNotImplementedRmiWarning(RmiName_Request_AddItem);
					}
						
					if(!m_internalUse && m_enableStubProfiling)
					{
						::Proud::AfterRmiSummary summary;
						summary.m_rmiID = (::Proud::RmiID)Rmi_Request_AddItem;
						summary.m_rmiName = RmiName_Request_AddItem;
						summary.m_hostID = remote;
						summary.m_hostTag = hostTag;
						int64_t __t1;
			
						__t1 = ::Proud::GetPreciseCurrentTimeMs();
			
						summary.m_elapsedTime = (uint32_t)(__t1 - __t0);
						AfterRmiInvocation(summary);
					}
				}
				break;
			case Rmi_Request_RemoveItem:
				{
					::Proud::RmiContext ctx;
					ctx.m_rmiID = __rmiID;
					ctx.m_sentFrom=pa.GetRemoteHostID();
					ctx.m_relayed=pa.IsRelayed();
					ctx.m_hostTag = hostTag;
					ctx.m_encryptMode = pa.GetEncryptMode();
					ctx.m_compressMode = pa.GetCompressMode();
			
			        if(BeforeDeserialize(remote, ctx, __msg) == false)
			        {
			            // The user don't want to call the RMI function. 
						// So, We fake that it has been already called.
						__msg.SetReadOffset(__msg.GetLength());
			            return true;
			        }
			
					int iClientID; __msg >> iClientID;
					int iItemID; __msg >> iItemID;
					int iItemCount; __msg >> iItemCount;
					m_core->PostCheckReadMessage(__msg,RmiName_Request_RemoveItem);
					
			
					if(m_enableNotifyCallFromStub && !m_internalUse)
					{
						::Proud::String parameterString;
						
						::Proud::AppendTextOut(parameterString,iClientID);	
										
						parameterString += _PNT(", ");
						::Proud::AppendTextOut(parameterString,iItemID);	
										
						parameterString += _PNT(", ");
						::Proud::AppendTextOut(parameterString,iItemCount);	
						
						NotifyCallFromStub(remote, (::Proud::RmiID)Rmi_Request_RemoveItem, 
							RmiName_Request_RemoveItem,parameterString);
			
			#ifdef VIZAGENT
						m_core->Viz_NotifyRecvToStub(remote, (::Proud::RmiID)Rmi_Request_RemoveItem, 
							RmiName_Request_RemoveItem, parameterString);
			#endif
					}
					else if(!m_internalUse)
					{
			#ifdef VIZAGENT
						m_core->Viz_NotifyRecvToStub(remote, (::Proud::RmiID)Rmi_Request_RemoveItem, 
							RmiName_Request_RemoveItem, _PNT(""));
			#endif
					}
						
					int64_t __t0 = 0;
					if(!m_internalUse && m_enableStubProfiling)
					{
						::Proud::BeforeRmiSummary summary;
						summary.m_rmiID = (::Proud::RmiID)Rmi_Request_RemoveItem;
						summary.m_rmiName = RmiName_Request_RemoveItem;
						summary.m_hostID = remote;
						summary.m_hostTag = hostTag;
						BeforeRmiInvocation(summary);
			
						__t0 = ::Proud::GetPreciseCurrentTimeMs();
					}
						
					// Call this method.
					bool __ret = Request_RemoveItem (remote,ctx , iClientID, iItemID, iItemCount );
						
					if(__ret==false)
					{
						// Error: RMI function that a user did not create has been called. 
						m_core->ShowNotImplementedRmiWarning(RmiName_Request_RemoveItem);
					}
						
					if(!m_internalUse && m_enableStubProfiling)
					{
						::Proud::AfterRmiSummary summary;
						summary.m_rmiID = (::Proud::RmiID)Rmi_Request_RemoveItem;
						summary.m_rmiName = RmiName_Request_RemoveItem;
						summary.m_hostID = remote;
						summary.m_hostTag = hostTag;
						int64_t __t1;
			
						__t1 = ::Proud::GetPreciseCurrentTimeMs();
			
						summary.m_elapsedTime = (uint32_t)(__t1 - __t0);
						AfterRmiInvocation(summary);
					}
				}
				break;
			case Rmi_Request_ItemData:
				{
					::Proud::RmiContext ctx;
					ctx.m_rmiID = __rmiID;
					ctx.m_sentFrom=pa.GetRemoteHostID();
					ctx.m_relayed=pa.IsRelayed();
					ctx.m_hostTag = hostTag;
					ctx.m_encryptMode = pa.GetEncryptMode();
					ctx.m_compressMode = pa.GetCompressMode();
			
			        if(BeforeDeserialize(remote, ctx, __msg) == false)
			        {
			            // The user don't want to call the RMI function. 
						// So, We fake that it has been already called.
						__msg.SetReadOffset(__msg.GetLength());
			            return true;
			        }
			
					int iClientID; __msg >> iClientID;
					int iItemID; __msg >> iItemID;
					m_core->PostCheckReadMessage(__msg,RmiName_Request_ItemData);
					
			
					if(m_enableNotifyCallFromStub && !m_internalUse)
					{
						::Proud::String parameterString;
						
						::Proud::AppendTextOut(parameterString,iClientID);	
										
						parameterString += _PNT(", ");
						::Proud::AppendTextOut(parameterString,iItemID);	
						
						NotifyCallFromStub(remote, (::Proud::RmiID)Rmi_Request_ItemData, 
							RmiName_Request_ItemData,parameterString);
			
			#ifdef VIZAGENT
						m_core->Viz_NotifyRecvToStub(remote, (::Proud::RmiID)Rmi_Request_ItemData, 
							RmiName_Request_ItemData, parameterString);
			#endif
					}
					else if(!m_internalUse)
					{
			#ifdef VIZAGENT
						m_core->Viz_NotifyRecvToStub(remote, (::Proud::RmiID)Rmi_Request_ItemData, 
							RmiName_Request_ItemData, _PNT(""));
			#endif
					}
						
					int64_t __t0 = 0;
					if(!m_internalUse && m_enableStubProfiling)
					{
						::Proud::BeforeRmiSummary summary;
						summary.m_rmiID = (::Proud::RmiID)Rmi_Request_ItemData;
						summary.m_rmiName = RmiName_Request_ItemData;
						summary.m_hostID = remote;
						summary.m_hostTag = hostTag;
						BeforeRmiInvocation(summary);
			
						__t0 = ::Proud::GetPreciseCurrentTimeMs();
					}
						
					// Call this method.
					bool __ret = Request_ItemData (remote,ctx , iClientID, iItemID );
						
					if(__ret==false)
					{
						// Error: RMI function that a user did not create has been called. 
						m_core->ShowNotImplementedRmiWarning(RmiName_Request_ItemData);
					}
						
					if(!m_internalUse && m_enableStubProfiling)
					{
						::Proud::AfterRmiSummary summary;
						summary.m_rmiID = (::Proud::RmiID)Rmi_Request_ItemData;
						summary.m_rmiName = RmiName_Request_ItemData;
						summary.m_hostID = remote;
						summary.m_hostTag = hostTag;
						int64_t __t1;
			
						__t1 = ::Proud::GetPreciseCurrentTimeMs();
			
						summary.m_elapsedTime = (uint32_t)(__t1 - __t0);
						AfterRmiInvocation(summary);
					}
				}
				break;
			case Rmi_Request_AddGold:
				{
					::Proud::RmiContext ctx;
					ctx.m_rmiID = __rmiID;
					ctx.m_sentFrom=pa.GetRemoteHostID();
					ctx.m_relayed=pa.IsRelayed();
					ctx.m_hostTag = hostTag;
					ctx.m_encryptMode = pa.GetEncryptMode();
					ctx.m_compressMode = pa.GetCompressMode();
			
			        if(BeforeDeserialize(remote, ctx, __msg) == false)
			        {
			            // The user don't want to call the RMI function. 
						// So, We fake that it has been already called.
						__msg.SetReadOffset(__msg.GetLength());
			            return true;
			        }
			
					int ClientID; __msg >> ClientID;
					int GoldAmount; __msg >> GoldAmount;
					m_core->PostCheckReadMessage(__msg,RmiName_Request_AddGold);
					
			
					if(m_enableNotifyCallFromStub && !m_internalUse)
					{
						::Proud::String parameterString;
						
						::Proud::AppendTextOut(parameterString,ClientID);	
										
						parameterString += _PNT(", ");
						::Proud::AppendTextOut(parameterString,GoldAmount);	
						
						NotifyCallFromStub(remote, (::Proud::RmiID)Rmi_Request_AddGold, 
							RmiName_Request_AddGold,parameterString);
			
			#ifdef VIZAGENT
						m_core->Viz_NotifyRecvToStub(remote, (::Proud::RmiID)Rmi_Request_AddGold, 
							RmiName_Request_AddGold, parameterString);
			#endif
					}
					else if(!m_internalUse)
					{
			#ifdef VIZAGENT
						m_core->Viz_NotifyRecvToStub(remote, (::Proud::RmiID)Rmi_Request_AddGold, 
							RmiName_Request_AddGold, _PNT(""));
			#endif
					}
						
					int64_t __t0 = 0;
					if(!m_internalUse && m_enableStubProfiling)
					{
						::Proud::BeforeRmiSummary summary;
						summary.m_rmiID = (::Proud::RmiID)Rmi_Request_AddGold;
						summary.m_rmiName = RmiName_Request_AddGold;
						summary.m_hostID = remote;
						summary.m_hostTag = hostTag;
						BeforeRmiInvocation(summary);
			
						__t0 = ::Proud::GetPreciseCurrentTimeMs();
					}
						
					// Call this method.
					bool __ret = Request_AddGold (remote,ctx , ClientID, GoldAmount );
						
					if(__ret==false)
					{
						// Error: RMI function that a user did not create has been called. 
						m_core->ShowNotImplementedRmiWarning(RmiName_Request_AddGold);
					}
						
					if(!m_internalUse && m_enableStubProfiling)
					{
						::Proud::AfterRmiSummary summary;
						summary.m_rmiID = (::Proud::RmiID)Rmi_Request_AddGold;
						summary.m_rmiName = RmiName_Request_AddGold;
						summary.m_hostID = remote;
						summary.m_hostTag = hostTag;
						int64_t __t1;
			
						__t1 = ::Proud::GetPreciseCurrentTimeMs();
			
						summary.m_elapsedTime = (uint32_t)(__t1 - __t0);
						AfterRmiInvocation(summary);
					}
				}
				break;
			case Rmi_OnChat:
				{
					::Proud::RmiContext ctx;
					ctx.m_rmiID = __rmiID;
					ctx.m_sentFrom=pa.GetRemoteHostID();
					ctx.m_relayed=pa.IsRelayed();
					ctx.m_hostTag = hostTag;
					ctx.m_encryptMode = pa.GetEncryptMode();
					ctx.m_compressMode = pa.GetCompressMode();
			
			        if(BeforeDeserialize(remote, ctx, __msg) == false)
			        {
			            // The user don't want to call the RMI function. 
						// So, We fake that it has been already called.
						__msg.SetReadOffset(__msg.GetLength());
			            return true;
			        }
			
					int clientId; __msg >> clientId;
					string message; __msg >> message;
					m_core->PostCheckReadMessage(__msg,RmiName_OnChat);
					
			
					if(m_enableNotifyCallFromStub && !m_internalUse)
					{
						::Proud::String parameterString;
						
						::Proud::AppendTextOut(parameterString,clientId);	
										
						parameterString += _PNT(", ");
						::Proud::AppendTextOut(parameterString,message);	
						
						NotifyCallFromStub(remote, (::Proud::RmiID)Rmi_OnChat, 
							RmiName_OnChat,parameterString);
			
			#ifdef VIZAGENT
						m_core->Viz_NotifyRecvToStub(remote, (::Proud::RmiID)Rmi_OnChat, 
							RmiName_OnChat, parameterString);
			#endif
					}
					else if(!m_internalUse)
					{
			#ifdef VIZAGENT
						m_core->Viz_NotifyRecvToStub(remote, (::Proud::RmiID)Rmi_OnChat, 
							RmiName_OnChat, _PNT(""));
			#endif
					}
						
					int64_t __t0 = 0;
					if(!m_internalUse && m_enableStubProfiling)
					{
						::Proud::BeforeRmiSummary summary;
						summary.m_rmiID = (::Proud::RmiID)Rmi_OnChat;
						summary.m_rmiName = RmiName_OnChat;
						summary.m_hostID = remote;
						summary.m_hostTag = hostTag;
						BeforeRmiInvocation(summary);
			
						__t0 = ::Proud::GetPreciseCurrentTimeMs();
					}
						
					// Call this method.
					bool __ret = OnChat (remote,ctx , clientId, message );
						
					if(__ret==false)
					{
						// Error: RMI function that a user did not create has been called. 
						m_core->ShowNotImplementedRmiWarning(RmiName_OnChat);
					}
						
					if(!m_internalUse && m_enableStubProfiling)
					{
						::Proud::AfterRmiSummary summary;
						summary.m_rmiID = (::Proud::RmiID)Rmi_OnChat;
						summary.m_rmiName = RmiName_OnChat;
						summary.m_hostID = remote;
						summary.m_hostTag = hostTag;
						int64_t __t1;
			
						__t1 = ::Proud::GetPreciseCurrentTimeMs();
			
						summary.m_elapsedTime = (uint32_t)(__t1 - __t0);
						AfterRmiInvocation(summary);
					}
				}
				break;
		default:
			goto __fail;
		}		
		return true;
__fail:
		{
			__msg.SetReadOffset(orgReadOffset);
			return false;
		}
	}
	#ifdef USE_RMI_NAME_STRING
	const PNTCHAR* Stub::RmiName_ResponseLoginEvent =_PNT("ResponseLoginEvent");
	#else
	const PNTCHAR* Stub::RmiName_ResponseLoginEvent =_PNT("");
	#endif
	#ifdef USE_RMI_NAME_STRING
	const PNTCHAR* Stub::RmiName_ResponseCheckNickname =_PNT("ResponseCheckNickname");
	#else
	const PNTCHAR* Stub::RmiName_ResponseCheckNickname =_PNT("");
	#endif
	#ifdef USE_RMI_NAME_STRING
	const PNTCHAR* Stub::RmiName_OnPlayerJoined =_PNT("OnPlayerJoined");
	#else
	const PNTCHAR* Stub::RmiName_OnPlayerJoined =_PNT("");
	#endif
	#ifdef USE_RMI_NAME_STRING
	const PNTCHAR* Stub::RmiName_SpawnObjectEvent =_PNT("SpawnObjectEvent");
	#else
	const PNTCHAR* Stub::RmiName_SpawnObjectEvent =_PNT("");
	#endif
	#ifdef USE_RMI_NAME_STRING
	const PNTCHAR* Stub::RmiName_OtherPlayerTransformUpdated =_PNT("OtherPlayerTransformUpdated");
	#else
	const PNTCHAR* Stub::RmiName_OtherPlayerTransformUpdated =_PNT("");
	#endif
	#ifdef USE_RMI_NAME_STRING
	const PNTCHAR* Stub::RmiName_OnPlayerTransformUpdated =_PNT("OnPlayerTransformUpdated");
	#else
	const PNTCHAR* Stub::RmiName_OnPlayerTransformUpdated =_PNT("");
	#endif
	#ifdef USE_RMI_NAME_STRING
	const PNTCHAR* Stub::RmiName_OtherActorTransformUpdated =_PNT("OtherActorTransformUpdated");
	#else
	const PNTCHAR* Stub::RmiName_OtherActorTransformUpdated =_PNT("");
	#endif
	#ifdef USE_RMI_NAME_STRING
	const PNTCHAR* Stub::RmiName_ActorTransformUpdated =_PNT("ActorTransformUpdated");
	#else
	const PNTCHAR* Stub::RmiName_ActorTransformUpdated =_PNT("");
	#endif
	#ifdef USE_RMI_NAME_STRING
	const PNTCHAR* Stub::RmiName_UpdateCharacterAnimState =_PNT("UpdateCharacterAnimState");
	#else
	const PNTCHAR* Stub::RmiName_UpdateCharacterAnimState =_PNT("");
	#endif
	#ifdef USE_RMI_NAME_STRING
	const PNTCHAR* Stub::RmiName_OnOtherPlayerAnimUpdated =_PNT("OnOtherPlayerAnimUpdated");
	#else
	const PNTCHAR* Stub::RmiName_OnOtherPlayerAnimUpdated =_PNT("");
	#endif
	#ifdef USE_RMI_NAME_STRING
	const PNTCHAR* Stub::RmiName_UpdateActorAnimState =_PNT("UpdateActorAnimState");
	#else
	const PNTCHAR* Stub::RmiName_UpdateActorAnimState =_PNT("");
	#endif
	#ifdef USE_RMI_NAME_STRING
	const PNTCHAR* Stub::RmiName_OnOtherActorAnimUpdated =_PNT("OnOtherActorAnimUpdated");
	#else
	const PNTCHAR* Stub::RmiName_OnOtherActorAnimUpdated =_PNT("");
	#endif
	#ifdef USE_RMI_NAME_STRING
	const PNTCHAR* Stub::RmiName_Request_AddItem =_PNT("Request_AddItem");
	#else
	const PNTCHAR* Stub::RmiName_Request_AddItem =_PNT("");
	#endif
	#ifdef USE_RMI_NAME_STRING
	const PNTCHAR* Stub::RmiName_Request_RemoveItem =_PNT("Request_RemoveItem");
	#else
	const PNTCHAR* Stub::RmiName_Request_RemoveItem =_PNT("");
	#endif
	#ifdef USE_RMI_NAME_STRING
	const PNTCHAR* Stub::RmiName_Request_ItemData =_PNT("Request_ItemData");
	#else
	const PNTCHAR* Stub::RmiName_Request_ItemData =_PNT("");
	#endif
	#ifdef USE_RMI_NAME_STRING
	const PNTCHAR* Stub::RmiName_Request_AddGold =_PNT("Request_AddGold");
	#else
	const PNTCHAR* Stub::RmiName_Request_AddGold =_PNT("");
	#endif
	#ifdef USE_RMI_NAME_STRING
	const PNTCHAR* Stub::RmiName_OnChat =_PNT("OnChat");
	#else
	const PNTCHAR* Stub::RmiName_OnChat =_PNT("");
	#endif
	const PNTCHAR* Stub::RmiName_First = RmiName_ResponseLoginEvent;

}



