  






// Generated by PIDL compiler.
// Do not modify this file, but modify the source .pidl file.
   
#pragma once


#include "ServerRmi_common.h"

     
namespace ServerToClient {


	class Stub : public ::Proud::IRmiStub
	{
	public:
               
		virtual bool ResponseLoginEvent ( ::Proud::HostID, ::Proud::RmiContext& , const bool & , const int & )		{ 
			return false;
		} 

#define DECRMI_ServerToClient_ResponseLoginEvent bool ResponseLoginEvent ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const bool & bIsSuccess, const int & ErrorType) PN_OVERRIDE

#define DEFRMI_ServerToClient_ResponseLoginEvent(DerivedClass) bool DerivedClass::ResponseLoginEvent ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const bool & bIsSuccess, const int & ErrorType)
#define CALL_ServerToClient_ResponseLoginEvent ResponseLoginEvent ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const bool & bIsSuccess, const int & ErrorType)
#define PARAM_ServerToClient_ResponseLoginEvent ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const bool & bIsSuccess, const int & ErrorType)
               
		virtual bool ResponseCheckNickname ( ::Proud::HostID, ::Proud::RmiContext& , const int & , const bool & )		{ 
			return false;
		} 

#define DECRMI_ServerToClient_ResponseCheckNickname bool ResponseCheckNickname ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & clientId, const bool & bIsAble) PN_OVERRIDE

#define DEFRMI_ServerToClient_ResponseCheckNickname(DerivedClass) bool DerivedClass::ResponseCheckNickname ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & clientId, const bool & bIsAble)
#define CALL_ServerToClient_ResponseCheckNickname ResponseCheckNickname ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & clientId, const bool & bIsAble)
#define PARAM_ServerToClient_ResponseCheckNickname ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & clientId, const bool & bIsAble)
               
		virtual bool OnPlayerJoined ( ::Proud::HostID, ::Proud::RmiContext& , const int & , const string & , const float & , const float & , const float & )		{ 
			return false;
		} 

#define DECRMI_ServerToClient_OnPlayerJoined bool OnPlayerJoined ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & clientId, const string & szNickName, const float & PosX, const float & PosY, const float & PosZ) PN_OVERRIDE

#define DEFRMI_ServerToClient_OnPlayerJoined(DerivedClass) bool DerivedClass::OnPlayerJoined ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & clientId, const string & szNickName, const float & PosX, const float & PosY, const float & PosZ)
#define CALL_ServerToClient_OnPlayerJoined OnPlayerJoined ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & clientId, const string & szNickName, const float & PosX, const float & PosY, const float & PosZ)
#define PARAM_ServerToClient_OnPlayerJoined ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & clientId, const string & szNickName, const float & PosX, const float & PosY, const float & PosZ)
               
		virtual bool OnOtherPlayerUpdated ( ::Proud::HostID, ::Proud::RmiContext& , const int & , const string & , const float & , const float & , const float & )		{ 
			return false;
		} 

#define DECRMI_ServerToClient_OnOtherPlayerUpdated bool OnOtherPlayerUpdated ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & ClientID, const string & NickName, const float & PosX, const float & PosY, const float & PosZ) PN_OVERRIDE

#define DEFRMI_ServerToClient_OnOtherPlayerUpdated(DerivedClass) bool DerivedClass::OnOtherPlayerUpdated ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & ClientID, const string & NickName, const float & PosX, const float & PosY, const float & PosZ)
#define CALL_ServerToClient_OnOtherPlayerUpdated OnOtherPlayerUpdated ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & ClientID, const string & NickName, const float & PosX, const float & PosY, const float & PosZ)
#define PARAM_ServerToClient_OnOtherPlayerUpdated ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & ClientID, const string & NickName, const float & PosX, const float & PosY, const float & PosZ)
               
		virtual bool OnOtherPlayerAnimUpdated ( ::Proud::HostID, ::Proud::RmiContext& , const int & , const int & , const int & )		{ 
			return false;
		} 

#define DECRMI_ServerToClient_OnOtherPlayerAnimUpdated bool OnOtherPlayerAnimUpdated ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & ClientID, const int & AnimState, const int & AnimTime) PN_OVERRIDE

#define DEFRMI_ServerToClient_OnOtherPlayerAnimUpdated(DerivedClass) bool DerivedClass::OnOtherPlayerAnimUpdated ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & ClientID, const int & AnimState, const int & AnimTime)
#define CALL_ServerToClient_OnOtherPlayerAnimUpdated OnOtherPlayerAnimUpdated ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & ClientID, const int & AnimState, const int & AnimTime)
#define PARAM_ServerToClient_OnOtherPlayerAnimUpdated ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & ClientID, const int & AnimState, const int & AnimTime)
               
		virtual bool SpawnObjectEvent ( ::Proud::HostID, ::Proud::RmiContext& , const string & , const int & , const float & , const float & , const float & )		{ 
			return false;
		} 

#define DECRMI_ServerToClient_SpawnObjectEvent bool SpawnObjectEvent ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const string & Key, const int & templetedID, const float & px, const float & py, const float & pz) PN_OVERRIDE

#define DEFRMI_ServerToClient_SpawnObjectEvent(DerivedClass) bool DerivedClass::SpawnObjectEvent ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const string & Key, const int & templetedID, const float & px, const float & py, const float & pz)
#define CALL_ServerToClient_SpawnObjectEvent SpawnObjectEvent ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const string & Key, const int & templetedID, const float & px, const float & py, const float & pz)
#define PARAM_ServerToClient_SpawnObjectEvent ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const string & Key, const int & templetedID, const float & px, const float & py, const float & pz)
               
		virtual bool OnOtherActorUpdated ( ::Proud::HostID, ::Proud::RmiContext& , const int & , const float & , const float & , const float & )		{ 
			return false;
		} 

#define DECRMI_ServerToClient_OnOtherActorUpdated bool OnOtherActorUpdated ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & templeteID, const float & PosX, const float & PosY, const float & PosZ) PN_OVERRIDE

#define DEFRMI_ServerToClient_OnOtherActorUpdated(DerivedClass) bool DerivedClass::OnOtherActorUpdated ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & templeteID, const float & PosX, const float & PosY, const float & PosZ)
#define CALL_ServerToClient_OnOtherActorUpdated OnOtherActorUpdated ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & templeteID, const float & PosX, const float & PosY, const float & PosZ)
#define PARAM_ServerToClient_OnOtherActorUpdated ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & templeteID, const float & PosX, const float & PosY, const float & PosZ)
               
		virtual bool OnOtherActorAnimUpdated ( ::Proud::HostID, ::Proud::RmiContext& , const int & , const int & , const int & )		{ 
			return false;
		} 

#define DECRMI_ServerToClient_OnOtherActorAnimUpdated bool OnOtherActorAnimUpdated ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & templeteID, const int & AnimState, const int & AnimTime) PN_OVERRIDE

#define DEFRMI_ServerToClient_OnOtherActorAnimUpdated(DerivedClass) bool DerivedClass::OnOtherActorAnimUpdated ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & templeteID, const int & AnimState, const int & AnimTime)
#define CALL_ServerToClient_OnOtherActorAnimUpdated OnOtherActorAnimUpdated ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & templeteID, const int & AnimState, const int & AnimTime)
#define PARAM_ServerToClient_OnOtherActorAnimUpdated ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & templeteID, const int & AnimState, const int & AnimTime)
               
		virtual bool OnPositionUpdated ( ::Proud::HostID, ::Proud::RmiContext& , const int & , const float & , const float & , const float & , const float & , const float & , const float & )		{ 
			return false;
		} 

#define DECRMI_ServerToClient_OnPositionUpdated bool OnPositionUpdated ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & clientId, const float & PosX, const float & PosY, const float & PosZ, const float & DirX, const float & DirY, const float & DirZ) PN_OVERRIDE

#define DEFRMI_ServerToClient_OnPositionUpdated(DerivedClass) bool DerivedClass::OnPositionUpdated ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & clientId, const float & PosX, const float & PosY, const float & PosZ, const float & DirX, const float & DirY, const float & DirZ)
#define CALL_ServerToClient_OnPositionUpdated OnPositionUpdated ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & clientId, const float & PosX, const float & PosY, const float & PosZ, const float & DirX, const float & DirY, const float & DirZ)
#define PARAM_ServerToClient_OnPositionUpdated ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & clientId, const float & PosX, const float & PosY, const float & PosZ, const float & DirX, const float & DirY, const float & DirZ)
               
		virtual bool OnActorPositionUpdated ( ::Proud::HostID, ::Proud::RmiContext& , const int & , const float & , const float & , const float & , const float & , const float & , const float & )		{ 
			return false;
		} 

#define DECRMI_ServerToClient_OnActorPositionUpdated bool OnActorPositionUpdated ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & templeteID, const float & PosX, const float & PosY, const float & PosZ, const float & DirX, const float & DirY, const float & DirZ) PN_OVERRIDE

#define DEFRMI_ServerToClient_OnActorPositionUpdated(DerivedClass) bool DerivedClass::OnActorPositionUpdated ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & templeteID, const float & PosX, const float & PosY, const float & PosZ, const float & DirX, const float & DirY, const float & DirZ)
#define CALL_ServerToClient_OnActorPositionUpdated OnActorPositionUpdated ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & templeteID, const float & PosX, const float & PosY, const float & PosZ, const float & DirX, const float & DirY, const float & DirZ)
#define PARAM_ServerToClient_OnActorPositionUpdated ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & templeteID, const float & PosX, const float & PosY, const float & PosZ, const float & DirX, const float & DirY, const float & DirZ)
               
		virtual bool UpdateCharacterAnimState ( ::Proud::HostID, ::Proud::RmiContext& , const int & , const int & , const float & )		{ 
			return false;
		} 

#define DECRMI_ServerToClient_UpdateCharacterAnimState bool UpdateCharacterAnimState ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & clientId, const int & AnimSate, const float & Time) PN_OVERRIDE

#define DEFRMI_ServerToClient_UpdateCharacterAnimState(DerivedClass) bool DerivedClass::UpdateCharacterAnimState ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & clientId, const int & AnimSate, const float & Time)
#define CALL_ServerToClient_UpdateCharacterAnimState UpdateCharacterAnimState ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & clientId, const int & AnimSate, const float & Time)
#define PARAM_ServerToClient_UpdateCharacterAnimState ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & clientId, const int & AnimSate, const float & Time)
               
		virtual bool UpdateActorAnimState ( ::Proud::HostID, ::Proud::RmiContext& , const int & , const int & , const float & )		{ 
			return false;
		} 

#define DECRMI_ServerToClient_UpdateActorAnimState bool UpdateActorAnimState ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & templeteID, const int & AnimSate, const float & Time) PN_OVERRIDE

#define DEFRMI_ServerToClient_UpdateActorAnimState(DerivedClass) bool DerivedClass::UpdateActorAnimState ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & templeteID, const int & AnimSate, const float & Time)
#define CALL_ServerToClient_UpdateActorAnimState UpdateActorAnimState ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & templeteID, const int & AnimSate, const float & Time)
#define PARAM_ServerToClient_UpdateActorAnimState ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & templeteID, const int & AnimSate, const float & Time)
               
		virtual bool OnChat ( ::Proud::HostID, ::Proud::RmiContext& , const int & , const string & )		{ 
			return false;
		} 

#define DECRMI_ServerToClient_OnChat bool OnChat ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & clientId, const string & message) PN_OVERRIDE

#define DEFRMI_ServerToClient_OnChat(DerivedClass) bool DerivedClass::OnChat ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & clientId, const string & message)
#define CALL_ServerToClient_OnChat OnChat ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & clientId, const string & message)
#define PARAM_ServerToClient_OnChat ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & clientId, const string & message)
 
		virtual bool ProcessReceivedMessage(::Proud::CReceivedMessage &pa, void* hostTag) PN_OVERRIDE;
		static const PNTCHAR* RmiName_ResponseLoginEvent;
		static const PNTCHAR* RmiName_ResponseCheckNickname;
		static const PNTCHAR* RmiName_OnPlayerJoined;
		static const PNTCHAR* RmiName_OnOtherPlayerUpdated;
		static const PNTCHAR* RmiName_OnOtherPlayerAnimUpdated;
		static const PNTCHAR* RmiName_SpawnObjectEvent;
		static const PNTCHAR* RmiName_OnOtherActorUpdated;
		static const PNTCHAR* RmiName_OnOtherActorAnimUpdated;
		static const PNTCHAR* RmiName_OnPositionUpdated;
		static const PNTCHAR* RmiName_OnActorPositionUpdated;
		static const PNTCHAR* RmiName_UpdateCharacterAnimState;
		static const PNTCHAR* RmiName_UpdateActorAnimState;
		static const PNTCHAR* RmiName_OnChat;
		static const PNTCHAR* RmiName_First;
		virtual ::Proud::RmiID* GetRmiIDList() PN_OVERRIDE { return g_RmiIDList; }
		virtual int GetRmiIDListCount() PN_OVERRIDE { return g_RmiIDListCount; }
	};

#ifdef SUPPORTS_CPP11 
	
	class StubFunctional : public Stub 
	{
	public:
               
		std::function< bool ( ::Proud::HostID, ::Proud::RmiContext& , const bool & , const int & ) > ResponseLoginEvent_Function;
		virtual bool ResponseLoginEvent ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const bool & bIsSuccess, const int & ErrorType) 
		{ 
			if (ResponseLoginEvent_Function==nullptr) 
				return true; 
			return ResponseLoginEvent_Function(remote,rmiContext, bIsSuccess, ErrorType); 
		}

               
		std::function< bool ( ::Proud::HostID, ::Proud::RmiContext& , const int & , const bool & ) > ResponseCheckNickname_Function;
		virtual bool ResponseCheckNickname ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & clientId, const bool & bIsAble) 
		{ 
			if (ResponseCheckNickname_Function==nullptr) 
				return true; 
			return ResponseCheckNickname_Function(remote,rmiContext, clientId, bIsAble); 
		}

               
		std::function< bool ( ::Proud::HostID, ::Proud::RmiContext& , const int & , const string & , const float & , const float & , const float & ) > OnPlayerJoined_Function;
		virtual bool OnPlayerJoined ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & clientId, const string & szNickName, const float & PosX, const float & PosY, const float & PosZ) 
		{ 
			if (OnPlayerJoined_Function==nullptr) 
				return true; 
			return OnPlayerJoined_Function(remote,rmiContext, clientId, szNickName, PosX, PosY, PosZ); 
		}

               
		std::function< bool ( ::Proud::HostID, ::Proud::RmiContext& , const int & , const string & , const float & , const float & , const float & ) > OnOtherPlayerUpdated_Function;
		virtual bool OnOtherPlayerUpdated ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & ClientID, const string & NickName, const float & PosX, const float & PosY, const float & PosZ) 
		{ 
			if (OnOtherPlayerUpdated_Function==nullptr) 
				return true; 
			return OnOtherPlayerUpdated_Function(remote,rmiContext, ClientID, NickName, PosX, PosY, PosZ); 
		}

               
		std::function< bool ( ::Proud::HostID, ::Proud::RmiContext& , const int & , const int & , const int & ) > OnOtherPlayerAnimUpdated_Function;
		virtual bool OnOtherPlayerAnimUpdated ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & ClientID, const int & AnimState, const int & AnimTime) 
		{ 
			if (OnOtherPlayerAnimUpdated_Function==nullptr) 
				return true; 
			return OnOtherPlayerAnimUpdated_Function(remote,rmiContext, ClientID, AnimState, AnimTime); 
		}

               
		std::function< bool ( ::Proud::HostID, ::Proud::RmiContext& , const string & , const int & , const float & , const float & , const float & ) > SpawnObjectEvent_Function;
		virtual bool SpawnObjectEvent ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const string & Key, const int & templetedID, const float & px, const float & py, const float & pz) 
		{ 
			if (SpawnObjectEvent_Function==nullptr) 
				return true; 
			return SpawnObjectEvent_Function(remote,rmiContext, Key, templetedID, px, py, pz); 
		}

               
		std::function< bool ( ::Proud::HostID, ::Proud::RmiContext& , const int & , const float & , const float & , const float & ) > OnOtherActorUpdated_Function;
		virtual bool OnOtherActorUpdated ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & templeteID, const float & PosX, const float & PosY, const float & PosZ) 
		{ 
			if (OnOtherActorUpdated_Function==nullptr) 
				return true; 
			return OnOtherActorUpdated_Function(remote,rmiContext, templeteID, PosX, PosY, PosZ); 
		}

               
		std::function< bool ( ::Proud::HostID, ::Proud::RmiContext& , const int & , const int & , const int & ) > OnOtherActorAnimUpdated_Function;
		virtual bool OnOtherActorAnimUpdated ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & templeteID, const int & AnimState, const int & AnimTime) 
		{ 
			if (OnOtherActorAnimUpdated_Function==nullptr) 
				return true; 
			return OnOtherActorAnimUpdated_Function(remote,rmiContext, templeteID, AnimState, AnimTime); 
		}

               
		std::function< bool ( ::Proud::HostID, ::Proud::RmiContext& , const int & , const float & , const float & , const float & , const float & , const float & , const float & ) > OnPositionUpdated_Function;
		virtual bool OnPositionUpdated ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & clientId, const float & PosX, const float & PosY, const float & PosZ, const float & DirX, const float & DirY, const float & DirZ) 
		{ 
			if (OnPositionUpdated_Function==nullptr) 
				return true; 
			return OnPositionUpdated_Function(remote,rmiContext, clientId, PosX, PosY, PosZ, DirX, DirY, DirZ); 
		}

               
		std::function< bool ( ::Proud::HostID, ::Proud::RmiContext& , const int & , const float & , const float & , const float & , const float & , const float & , const float & ) > OnActorPositionUpdated_Function;
		virtual bool OnActorPositionUpdated ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & templeteID, const float & PosX, const float & PosY, const float & PosZ, const float & DirX, const float & DirY, const float & DirZ) 
		{ 
			if (OnActorPositionUpdated_Function==nullptr) 
				return true; 
			return OnActorPositionUpdated_Function(remote,rmiContext, templeteID, PosX, PosY, PosZ, DirX, DirY, DirZ); 
		}

               
		std::function< bool ( ::Proud::HostID, ::Proud::RmiContext& , const int & , const int & , const float & ) > UpdateCharacterAnimState_Function;
		virtual bool UpdateCharacterAnimState ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & clientId, const int & AnimSate, const float & Time) 
		{ 
			if (UpdateCharacterAnimState_Function==nullptr) 
				return true; 
			return UpdateCharacterAnimState_Function(remote,rmiContext, clientId, AnimSate, Time); 
		}

               
		std::function< bool ( ::Proud::HostID, ::Proud::RmiContext& , const int & , const int & , const float & ) > UpdateActorAnimState_Function;
		virtual bool UpdateActorAnimState ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & templeteID, const int & AnimSate, const float & Time) 
		{ 
			if (UpdateActorAnimState_Function==nullptr) 
				return true; 
			return UpdateActorAnimState_Function(remote,rmiContext, templeteID, AnimSate, Time); 
		}

               
		std::function< bool ( ::Proud::HostID, ::Proud::RmiContext& , const int & , const string & ) > OnChat_Function;
		virtual bool OnChat ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & clientId, const string & message) 
		{ 
			if (OnChat_Function==nullptr) 
				return true; 
			return OnChat_Function(remote,rmiContext, clientId, message); 
		}

	};
#endif

}


