 





// Generated by PIDL compiler.
// Do not modify this file, but modify the source .pidl file.

using System;
namespace ServerToClient
{
	internal class Common
	{
		// Message ID that replies to each RMI method. 
			public const Nettention.Proud.RmiID ResponseLoginEvent = (Nettention.Proud.RmiID)3000+1;
			public const Nettention.Proud.RmiID ResponseCheckNickname = (Nettention.Proud.RmiID)3000+2;
			public const Nettention.Proud.RmiID OnPlayerJoined = (Nettention.Proud.RmiID)3000+3;
			public const Nettention.Proud.RmiID OnOtherPlayerUpdated = (Nettention.Proud.RmiID)3000+4;
			public const Nettention.Proud.RmiID OnOtherPlayerAnimUpdated = (Nettention.Proud.RmiID)3000+5;
			public const Nettention.Proud.RmiID SpawnObjectEvent = (Nettention.Proud.RmiID)3000+6;
			public const Nettention.Proud.RmiID OnOtherActorUpdated = (Nettention.Proud.RmiID)3000+7;
			public const Nettention.Proud.RmiID OnOtherActorAnimUpdated = (Nettention.Proud.RmiID)3000+8;
			public const Nettention.Proud.RmiID OnPositionUpdated = (Nettention.Proud.RmiID)3000+9;
			public const Nettention.Proud.RmiID OnActorPositionUpdated = (Nettention.Proud.RmiID)3000+10;
			public const Nettention.Proud.RmiID UpdateCharacterAnimState = (Nettention.Proud.RmiID)3000+11;
			public const Nettention.Proud.RmiID UpdateActorAnimState = (Nettention.Proud.RmiID)3000+12;
			public const Nettention.Proud.RmiID OnChat = (Nettention.Proud.RmiID)3000+13;
		// List that has RMI ID.
		public static Nettention.Proud.RmiID[] RmiIDList = new Nettention.Proud.RmiID[] {
			ResponseLoginEvent,
			ResponseCheckNickname,
			OnPlayerJoined,
			OnOtherPlayerUpdated,
			OnOtherPlayerAnimUpdated,
			SpawnObjectEvent,
			OnOtherActorUpdated,
			OnOtherActorAnimUpdated,
			OnPositionUpdated,
			OnActorPositionUpdated,
			UpdateCharacterAnimState,
			UpdateActorAnimState,
			OnChat,
		};
	}
}






				 
