  






// Generated by PIDL compiler.
// Do not modify this file, but modify the source .pidl file.
   
#pragma once


#include "ServerRmi_common.h"

     
namespace ServerToClient {


	class Stub : public ::Proud::IRmiStub
	{
	public:
               
		virtual bool OnPlayerJoined ( ::Proud::HostID, ::Proud::RmiContext& , const int & , const float & , const float & , const float & )		{ 
			return false;
		} 

#define DECRMI_ServerToClient_OnPlayerJoined bool OnPlayerJoined ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & clientId, const float & PosX, const float & PosY, const float & PosZ) PN_OVERRIDE

#define DEFRMI_ServerToClient_OnPlayerJoined(DerivedClass) bool DerivedClass::OnPlayerJoined ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & clientId, const float & PosX, const float & PosY, const float & PosZ)
#define CALL_ServerToClient_OnPlayerJoined OnPlayerJoined ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & clientId, const float & PosX, const float & PosY, const float & PosZ)
#define PARAM_ServerToClient_OnPlayerJoined ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & clientId, const float & PosX, const float & PosY, const float & PosZ)
               
		virtual bool OnPositionUpdated ( ::Proud::HostID, ::Proud::RmiContext& , const int & , const float & , const float & , const float & , const float & , const float & , const float & )		{ 
			return false;
		} 

#define DECRMI_ServerToClient_OnPositionUpdated bool OnPositionUpdated ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & clientId, const float & PosX, const float & PosY, const float & PosZ, const float & DirX, const float & DirY, const float & DirZ) PN_OVERRIDE

#define DEFRMI_ServerToClient_OnPositionUpdated(DerivedClass) bool DerivedClass::OnPositionUpdated ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & clientId, const float & PosX, const float & PosY, const float & PosZ, const float & DirX, const float & DirY, const float & DirZ)
#define CALL_ServerToClient_OnPositionUpdated OnPositionUpdated ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & clientId, const float & PosX, const float & PosY, const float & PosZ, const float & DirX, const float & DirY, const float & DirZ)
#define PARAM_ServerToClient_OnPositionUpdated ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & clientId, const float & PosX, const float & PosY, const float & PosZ, const float & DirX, const float & DirY, const float & DirZ)
               
		virtual bool OnChat ( ::Proud::HostID, ::Proud::RmiContext& , const int & , const string & )		{ 
			return false;
		} 

#define DECRMI_ServerToClient_OnChat bool OnChat ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & clientId, const string & message) PN_OVERRIDE

#define DEFRMI_ServerToClient_OnChat(DerivedClass) bool DerivedClass::OnChat ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & clientId, const string & message)
#define CALL_ServerToClient_OnChat OnChat ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & clientId, const string & message)
#define PARAM_ServerToClient_OnChat ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & clientId, const string & message)
 
		virtual bool ProcessReceivedMessage(::Proud::CReceivedMessage &pa, void* hostTag) PN_OVERRIDE;
		static const PNTCHAR* RmiName_OnPlayerJoined;
		static const PNTCHAR* RmiName_OnPositionUpdated;
		static const PNTCHAR* RmiName_OnChat;
		static const PNTCHAR* RmiName_First;
		virtual ::Proud::RmiID* GetRmiIDList() PN_OVERRIDE { return g_RmiIDList; }
		virtual int GetRmiIDListCount() PN_OVERRIDE { return g_RmiIDListCount; }
	};

#ifdef SUPPORTS_CPP11 
	
	class StubFunctional : public Stub 
	{
	public:
               
		std::function< bool ( ::Proud::HostID, ::Proud::RmiContext& , const int & , const float & , const float & , const float & ) > OnPlayerJoined_Function;
		virtual bool OnPlayerJoined ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & clientId, const float & PosX, const float & PosY, const float & PosZ) 
		{ 
			if (OnPlayerJoined_Function==nullptr) 
				return true; 
			return OnPlayerJoined_Function(remote,rmiContext, clientId, PosX, PosY, PosZ); 
		}

               
		std::function< bool ( ::Proud::HostID, ::Proud::RmiContext& , const int & , const float & , const float & , const float & , const float & , const float & , const float & ) > OnPositionUpdated_Function;
		virtual bool OnPositionUpdated ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & clientId, const float & PosX, const float & PosY, const float & PosZ, const float & DirX, const float & DirY, const float & DirZ) 
		{ 
			if (OnPositionUpdated_Function==nullptr) 
				return true; 
			return OnPositionUpdated_Function(remote,rmiContext, clientId, PosX, PosY, PosZ, DirX, DirY, DirZ); 
		}

               
		std::function< bool ( ::Proud::HostID, ::Proud::RmiContext& , const int & , const string & ) > OnChat_Function;
		virtual bool OnChat ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & clientId, const string & message) 
		{ 
			if (OnChat_Function==nullptr) 
				return true; 
			return OnChat_Function(remote,rmiContext, clientId, message); 
		}

	};
#endif

}


