



  
// Generated by PIDL compiler.
// Do not modify this file, but modify the source .pidl file.

#pragma once


#include "ServerRmi_common.h"

namespace ServerToClient {


	class Proxy : public ::Proud::IRmiProxy
	{
	public:
	virtual bool ResponseLoginEvent ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const bool & bIsSuccess, const int & ErrorType) PN_SEALED; 
	virtual bool ResponseLoginEvent ( ::Proud::HostID *remotes, int remoteCount, ::Proud::RmiContext &rmiContext, const bool & bIsSuccess, const int & ErrorType)   PN_SEALED;  
	virtual bool ResponseCheckNickname ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & clientId, const bool & bIsAble) PN_SEALED; 
	virtual bool ResponseCheckNickname ( ::Proud::HostID *remotes, int remoteCount, ::Proud::RmiContext &rmiContext, const int & clientId, const bool & bIsAble)   PN_SEALED;  
	virtual bool OnPlayerJoined ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & clientId, const string & szNickName, const float & PosX, const float & PosY, const float & PosZ) PN_SEALED; 
	virtual bool OnPlayerJoined ( ::Proud::HostID *remotes, int remoteCount, ::Proud::RmiContext &rmiContext, const int & clientId, const string & szNickName, const float & PosX, const float & PosY, const float & PosZ)   PN_SEALED;  
	virtual bool OnOtherPlayerUpdated ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & ClientID, const string & NickName, const float & PosX, const float & PosY, const float & PosZ) PN_SEALED; 
	virtual bool OnOtherPlayerUpdated ( ::Proud::HostID *remotes, int remoteCount, ::Proud::RmiContext &rmiContext, const int & ClientID, const string & NickName, const float & PosX, const float & PosY, const float & PosZ)   PN_SEALED;  
	virtual bool OnOtherPlayerAnimUpdated ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & ClientID, const int & AnimState, const int & AnimTime) PN_SEALED; 
	virtual bool OnOtherPlayerAnimUpdated ( ::Proud::HostID *remotes, int remoteCount, ::Proud::RmiContext &rmiContext, const int & ClientID, const int & AnimState, const int & AnimTime)   PN_SEALED;  
	virtual bool SpawnObjectEvent ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const string & Key, const int & templetedID, const float & px, const float & py, const float & pz) PN_SEALED; 
	virtual bool SpawnObjectEvent ( ::Proud::HostID *remotes, int remoteCount, ::Proud::RmiContext &rmiContext, const string & Key, const int & templetedID, const float & px, const float & py, const float & pz)   PN_SEALED;  
	virtual bool OnOtherActorUpdated ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & templeteID, const float & PosX, const float & PosY, const float & PosZ) PN_SEALED; 
	virtual bool OnOtherActorUpdated ( ::Proud::HostID *remotes, int remoteCount, ::Proud::RmiContext &rmiContext, const int & templeteID, const float & PosX, const float & PosY, const float & PosZ)   PN_SEALED;  
	virtual bool OnOtherActorAnimUpdated ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & templeteID, const int & AnimState, const int & AnimTime) PN_SEALED; 
	virtual bool OnOtherActorAnimUpdated ( ::Proud::HostID *remotes, int remoteCount, ::Proud::RmiContext &rmiContext, const int & templeteID, const int & AnimState, const int & AnimTime)   PN_SEALED;  
	virtual bool OnPositionUpdated ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & clientId, const float & PosX, const float & PosY, const float & PosZ, const float & DirX, const float & DirY, const float & DirZ) PN_SEALED; 
	virtual bool OnPositionUpdated ( ::Proud::HostID *remotes, int remoteCount, ::Proud::RmiContext &rmiContext, const int & clientId, const float & PosX, const float & PosY, const float & PosZ, const float & DirX, const float & DirY, const float & DirZ)   PN_SEALED;  
	virtual bool OnActorPositionUpdated ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & templeteID, const float & PosX, const float & PosY, const float & PosZ, const float & DirX, const float & DirY, const float & DirZ) PN_SEALED; 
	virtual bool OnActorPositionUpdated ( ::Proud::HostID *remotes, int remoteCount, ::Proud::RmiContext &rmiContext, const int & templeteID, const float & PosX, const float & PosY, const float & PosZ, const float & DirX, const float & DirY, const float & DirZ)   PN_SEALED;  
	virtual bool UpdateCharacterAnimState ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & clientId, const int & AnimSate, const float & Time) PN_SEALED; 
	virtual bool UpdateCharacterAnimState ( ::Proud::HostID *remotes, int remoteCount, ::Proud::RmiContext &rmiContext, const int & clientId, const int & AnimSate, const float & Time)   PN_SEALED;  
	virtual bool UpdateActorAnimState ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & templeteID, const int & AnimSate, const float & Time) PN_SEALED; 
	virtual bool UpdateActorAnimState ( ::Proud::HostID *remotes, int remoteCount, ::Proud::RmiContext &rmiContext, const int & templeteID, const int & AnimSate, const float & Time)   PN_SEALED;  
	virtual bool OnChat ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & clientId, const string & message) PN_SEALED; 
	virtual bool OnChat ( ::Proud::HostID *remotes, int remoteCount, ::Proud::RmiContext &rmiContext, const int & clientId, const string & message)   PN_SEALED;  
static const PNTCHAR* RmiName_ResponseLoginEvent;
static const PNTCHAR* RmiName_ResponseCheckNickname;
static const PNTCHAR* RmiName_OnPlayerJoined;
static const PNTCHAR* RmiName_OnOtherPlayerUpdated;
static const PNTCHAR* RmiName_OnOtherPlayerAnimUpdated;
static const PNTCHAR* RmiName_SpawnObjectEvent;
static const PNTCHAR* RmiName_OnOtherActorUpdated;
static const PNTCHAR* RmiName_OnOtherActorAnimUpdated;
static const PNTCHAR* RmiName_OnPositionUpdated;
static const PNTCHAR* RmiName_OnActorPositionUpdated;
static const PNTCHAR* RmiName_UpdateCharacterAnimState;
static const PNTCHAR* RmiName_UpdateActorAnimState;
static const PNTCHAR* RmiName_OnChat;
static const PNTCHAR* RmiName_First;
		Proxy()
		{
			if(m_signature != 1)
				::Proud::ShowUserMisuseError(::Proud::ProxyBadSignatureErrorText);
		}

		virtual ::Proud::RmiID* GetRmiIDList() PN_OVERRIDE { return g_RmiIDList; } 
		virtual int GetRmiIDListCount() PN_OVERRIDE { return g_RmiIDListCount; }
	};

}



