 





// Generated by PIDL compiler.
// Do not modify this file, but modify the source .pidl file.

using System;
namespace ClientToServer
{
	internal class Common
	{
		// Message ID that replies to each RMI method. 
			public const Nettention.Proud.RmiID OnGameLogin = (Nettention.Proud.RmiID)2000+1;
			public const Nettention.Proud.RmiID Create_Character = (Nettention.Proud.RmiID)2000+2;
			public const Nettention.Proud.RmiID SpawnObjectEvent = (Nettention.Proud.RmiID)2000+3;
			public const Nettention.Proud.RmiID SpawnPlayerEvent = (Nettention.Proud.RmiID)2000+4;
			public const Nettention.Proud.RmiID RequestCheckNickname = (Nettention.Proud.RmiID)2000+5;
			public const Nettention.Proud.RmiID OnPositionUpdated = (Nettention.Proud.RmiID)2000+6;
			public const Nettention.Proud.RmiID OnActorPositionUpdated = (Nettention.Proud.RmiID)2000+7;
			public const Nettention.Proud.RmiID OnAnimUpdated = (Nettention.Proud.RmiID)2000+8;
			public const Nettention.Proud.RmiID OnActorAnimUpdated = (Nettention.Proud.RmiID)2000+9;
			public const Nettention.Proud.RmiID Request_AddItem = (Nettention.Proud.RmiID)2000+10;
			public const Nettention.Proud.RmiID Request_RemoveItem = (Nettention.Proud.RmiID)2000+11;
			public const Nettention.Proud.RmiID Request_ItemData = (Nettention.Proud.RmiID)2000+12;
			public const Nettention.Proud.RmiID Request_AddGold = (Nettention.Proud.RmiID)2000+13;
			public const Nettention.Proud.RmiID OnChat = (Nettention.Proud.RmiID)2000+14;
		// List that has RMI ID.
		public static Nettention.Proud.RmiID[] RmiIDList = new Nettention.Proud.RmiID[] {
			OnGameLogin,
			Create_Character,
			SpawnObjectEvent,
			SpawnPlayerEvent,
			RequestCheckNickname,
			OnPositionUpdated,
			OnActorPositionUpdated,
			OnAnimUpdated,
			OnActorAnimUpdated,
			Request_AddItem,
			Request_RemoveItem,
			Request_ItemData,
			Request_AddGold,
			OnChat,
		};
	}
}






				 
