




// Generated by PIDL compiler.
// Do not modify this file, but modify the source .pidl file.

using System;
using System.Net;	     

namespace ServerToClient
{
	internal class Stub:Nettention.Proud.RmiStub
	{
public AfterRmiInvocationDelegate AfterRmiInvocation = delegate(Nettention.Proud.AfterRmiSummary summary) {};
public BeforeRmiInvocationDelegate BeforeRmiInvocation = delegate(Nettention.Proud.BeforeRmiSummary summary) {};

		public delegate bool ResponseLoginEventDelegate(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, bool bIsSuccess, int ErrorType);  
		public ResponseLoginEventDelegate ResponseLoginEvent = delegate(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, bool bIsSuccess, int ErrorType)
		{ 
			return false;
		};
		public delegate bool ResponseCheckNicknameDelegate(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, int clientId, bool bIsAble);  
		public ResponseCheckNicknameDelegate ResponseCheckNickname = delegate(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, int clientId, bool bIsAble)
		{ 
			return false;
		};
		public delegate bool OnPlayerJoinedDelegate(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, int clientId, string szNickName, float PosX, float PosY, float PosZ);  
		public OnPlayerJoinedDelegate OnPlayerJoined = delegate(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, int clientId, string szNickName, float PosX, float PosY, float PosZ)
		{ 
			return false;
		};
		public delegate bool SpawnObjectEventDelegate(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, string Key, int templetedID, float px, float py, float pz);  
		public SpawnObjectEventDelegate SpawnObjectEvent = delegate(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, string Key, int templetedID, float px, float py, float pz)
		{ 
			return false;
		};
		public delegate bool OtherPlayerTransformUpdatedDelegate(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, int ClientID, string NickName, float ScaleX, float ScaleY, float ScaleZ, float AngleX, float AngleY, float AngleZ, float AngleW, float PosX, float PosY, float PosZ);  
		public OtherPlayerTransformUpdatedDelegate OtherPlayerTransformUpdated = delegate(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, int ClientID, string NickName, float ScaleX, float ScaleY, float ScaleZ, float AngleX, float AngleY, float AngleZ, float AngleW, float PosX, float PosY, float PosZ)
		{ 
			return false;
		};
		public delegate bool OnPlayerTransformUpdatedDelegate(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, int clientId, float ScaleX, float ScaleY, float ScaleZ, float AngleX, float AngleY, float AngleZ, float AngleW, float PosX, float PosY, float PosZ);  
		public OnPlayerTransformUpdatedDelegate OnPlayerTransformUpdated = delegate(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, int clientId, float ScaleX, float ScaleY, float ScaleZ, float AngleX, float AngleY, float AngleZ, float AngleW, float PosX, float PosY, float PosZ)
		{ 
			return false;
		};
		public delegate bool OtherActorTransformUpdatedDelegate(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, int templeteID, float ScaleX, float ScaleY, float ScaleZ, float AngleX, float AngleY, float AngleZ, float AngleW, float PosX, float PosY, float PosZ);  
		public OtherActorTransformUpdatedDelegate OtherActorTransformUpdated = delegate(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, int templeteID, float ScaleX, float ScaleY, float ScaleZ, float AngleX, float AngleY, float AngleZ, float AngleW, float PosX, float PosY, float PosZ)
		{ 
			return false;
		};
		public delegate bool ActorTransformUpdatedDelegate(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, int templeteID, float ScaleX, float ScaleY, float ScaleZ, float AngleX, float AngleY, float AngleZ, float AngleW, float PosX, float PosY, float PosZ);  
		public ActorTransformUpdatedDelegate ActorTransformUpdated = delegate(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, int templeteID, float ScaleX, float ScaleY, float ScaleZ, float AngleX, float AngleY, float AngleZ, float AngleW, float PosX, float PosY, float PosZ)
		{ 
			return false;
		};
		public delegate bool UpdateCharacterAnimStateDelegate(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, int clientId, int AnimSate, float Time);  
		public UpdateCharacterAnimStateDelegate UpdateCharacterAnimState = delegate(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, int clientId, int AnimSate, float Time)
		{ 
			return false;
		};
		public delegate bool OnOtherPlayerAnimUpdatedDelegate(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, int ClientID, int AnimState, int AnimTime);  
		public OnOtherPlayerAnimUpdatedDelegate OnOtherPlayerAnimUpdated = delegate(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, int ClientID, int AnimState, int AnimTime)
		{ 
			return false;
		};
		public delegate bool UpdateActorAnimStateDelegate(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, int templeteID, int AnimSate, float Time);  
		public UpdateActorAnimStateDelegate UpdateActorAnimState = delegate(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, int templeteID, int AnimSate, float Time)
		{ 
			return false;
		};
		public delegate bool OnOtherActorAnimUpdatedDelegate(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, int templeteID, int AnimState, int AnimTime);  
		public OnOtherActorAnimUpdatedDelegate OnOtherActorAnimUpdated = delegate(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, int templeteID, int AnimState, int AnimTime)
		{ 
			return false;
		};
		public delegate bool Request_AddItemDelegate(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, int iClientID, int iItemID, int iItemCount);  
		public Request_AddItemDelegate Request_AddItem = delegate(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, int iClientID, int iItemID, int iItemCount)
		{ 
			return false;
		};
		public delegate bool Request_RemoveItemDelegate(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, int iClientID, int iItemID, int iItemCount);  
		public Request_RemoveItemDelegate Request_RemoveItem = delegate(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, int iClientID, int iItemID, int iItemCount)
		{ 
			return false;
		};
		public delegate bool Request_ItemDataDelegate(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, int iClientID, int iItemID);  
		public Request_ItemDataDelegate Request_ItemData = delegate(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, int iClientID, int iItemID)
		{ 
			return false;
		};
		public delegate bool Request_AddGoldDelegate(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, int ClientID, int GoldAmount);  
		public Request_AddGoldDelegate Request_AddGold = delegate(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, int ClientID, int GoldAmount)
		{ 
			return false;
		};
		public delegate bool OnChatDelegate(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, int clientId, string message);  
		public OnChatDelegate OnChat = delegate(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, int clientId, string message)
		{ 
			return false;
		};
	public override bool ProcessReceivedMessage(Nettention.Proud.ReceivedMessage pa, Object hostTag) 
	{
		Nettention.Proud.HostID remote=pa.RemoteHostID;
		if(remote==Nettention.Proud.HostID.HostID_None)
		{
			ShowUnknownHostIDWarning(remote);
		}

		Nettention.Proud.Message __msg=pa.ReadOnlyMessage;
		int orgReadOffset = __msg.ReadOffset;
        Nettention.Proud.RmiID __rmiID = Nettention.Proud.RmiID.RmiID_None;
        if (!__msg.Read( out __rmiID))
            goto __fail;
					
		switch(__rmiID)
		{
        case Common.ResponseLoginEvent:
            ProcessReceivedMessage_ResponseLoginEvent(__msg, pa, hostTag, remote);
            break;
        case Common.ResponseCheckNickname:
            ProcessReceivedMessage_ResponseCheckNickname(__msg, pa, hostTag, remote);
            break;
        case Common.OnPlayerJoined:
            ProcessReceivedMessage_OnPlayerJoined(__msg, pa, hostTag, remote);
            break;
        case Common.SpawnObjectEvent:
            ProcessReceivedMessage_SpawnObjectEvent(__msg, pa, hostTag, remote);
            break;
        case Common.OtherPlayerTransformUpdated:
            ProcessReceivedMessage_OtherPlayerTransformUpdated(__msg, pa, hostTag, remote);
            break;
        case Common.OnPlayerTransformUpdated:
            ProcessReceivedMessage_OnPlayerTransformUpdated(__msg, pa, hostTag, remote);
            break;
        case Common.OtherActorTransformUpdated:
            ProcessReceivedMessage_OtherActorTransformUpdated(__msg, pa, hostTag, remote);
            break;
        case Common.ActorTransformUpdated:
            ProcessReceivedMessage_ActorTransformUpdated(__msg, pa, hostTag, remote);
            break;
        case Common.UpdateCharacterAnimState:
            ProcessReceivedMessage_UpdateCharacterAnimState(__msg, pa, hostTag, remote);
            break;
        case Common.OnOtherPlayerAnimUpdated:
            ProcessReceivedMessage_OnOtherPlayerAnimUpdated(__msg, pa, hostTag, remote);
            break;
        case Common.UpdateActorAnimState:
            ProcessReceivedMessage_UpdateActorAnimState(__msg, pa, hostTag, remote);
            break;
        case Common.OnOtherActorAnimUpdated:
            ProcessReceivedMessage_OnOtherActorAnimUpdated(__msg, pa, hostTag, remote);
            break;
        case Common.Request_AddItem:
            ProcessReceivedMessage_Request_AddItem(__msg, pa, hostTag, remote);
            break;
        case Common.Request_RemoveItem:
            ProcessReceivedMessage_Request_RemoveItem(__msg, pa, hostTag, remote);
            break;
        case Common.Request_ItemData:
            ProcessReceivedMessage_Request_ItemData(__msg, pa, hostTag, remote);
            break;
        case Common.Request_AddGold:
            ProcessReceivedMessage_Request_AddGold(__msg, pa, hostTag, remote);
            break;
        case Common.OnChat:
            ProcessReceivedMessage_OnChat(__msg, pa, hostTag, remote);
            break;
		default:
			 goto __fail;
		}
		return true;
__fail:
	  {
			__msg.ReadOffset = orgReadOffset;
			return false;
	  }
	}
    void ProcessReceivedMessage_ResponseLoginEvent(Nettention.Proud.Message __msg, Nettention.Proud.ReceivedMessage pa, Object hostTag, Nettention.Proud.HostID remote)
    {
        Nettention.Proud.RmiContext ctx = new Nettention.Proud.RmiContext();
        ctx.sentFrom=pa.RemoteHostID;
        ctx.relayed=pa.IsRelayed;
        ctx.hostTag=hostTag;
        ctx.encryptMode = pa.EncryptMode;
        ctx.compressMode = pa.CompressMode;
        ctx.rmiID = Common.ResponseLoginEvent;

        bool bIsSuccess; Nettention.Proud.Marshaler.Read(__msg,out bIsSuccess);	
int ErrorType; Nettention.Proud.Marshaler.Read(__msg,out ErrorType);	
core.PostCheckReadMessage(__msg, RmiName_ResponseLoginEvent);
        if(enableNotifyCallFromStub==true)
        {
        string parameterString = "";
        parameterString+=bIsSuccess.ToString()+",";
parameterString+=ErrorType.ToString()+",";
        NotifyCallFromStub(Common.ResponseLoginEvent, RmiName_ResponseLoginEvent,parameterString);
        }

        if(enableStubProfiling)
        {
        Nettention.Proud.BeforeRmiSummary summary = new Nettention.Proud.BeforeRmiSummary();
        summary.rmiID = Common.ResponseLoginEvent;
        summary.rmiName = RmiName_ResponseLoginEvent;
        summary.hostID = remote;
        summary.hostTag = hostTag;
        BeforeRmiInvocation(summary);
        }

        long t0 = Nettention.Proud.PreciseCurrentTime.GetTimeMs();

        // Call this method.
        bool __ret =ResponseLoginEvent (remote,ctx , bIsSuccess, ErrorType );

        if(__ret==false)
        {
        // Error: RMI function that a user did not create has been called. 
        core.ShowNotImplementedRmiWarning(RmiName_ResponseLoginEvent);
        }

        if(enableStubProfiling)
        {
        Nettention.Proud.AfterRmiSummary summary = new Nettention.Proud.AfterRmiSummary();
        summary.rmiID = Common.ResponseLoginEvent;
        summary.rmiName = RmiName_ResponseLoginEvent;
        summary.hostID = remote;
        summary.hostTag = hostTag;
        summary.elapsedTime = Nettention.Proud.PreciseCurrentTime.GetTimeMs()-t0;
        AfterRmiInvocation(summary);
        }
    }
    void ProcessReceivedMessage_ResponseCheckNickname(Nettention.Proud.Message __msg, Nettention.Proud.ReceivedMessage pa, Object hostTag, Nettention.Proud.HostID remote)
    {
        Nettention.Proud.RmiContext ctx = new Nettention.Proud.RmiContext();
        ctx.sentFrom=pa.RemoteHostID;
        ctx.relayed=pa.IsRelayed;
        ctx.hostTag=hostTag;
        ctx.encryptMode = pa.EncryptMode;
        ctx.compressMode = pa.CompressMode;
        ctx.rmiID = Common.ResponseCheckNickname;

        int clientId; Nettention.Proud.Marshaler.Read(__msg,out clientId);	
bool bIsAble; Nettention.Proud.Marshaler.Read(__msg,out bIsAble);	
core.PostCheckReadMessage(__msg, RmiName_ResponseCheckNickname);
        if(enableNotifyCallFromStub==true)
        {
        string parameterString = "";
        parameterString+=clientId.ToString()+",";
parameterString+=bIsAble.ToString()+",";
        NotifyCallFromStub(Common.ResponseCheckNickname, RmiName_ResponseCheckNickname,parameterString);
        }

        if(enableStubProfiling)
        {
        Nettention.Proud.BeforeRmiSummary summary = new Nettention.Proud.BeforeRmiSummary();
        summary.rmiID = Common.ResponseCheckNickname;
        summary.rmiName = RmiName_ResponseCheckNickname;
        summary.hostID = remote;
        summary.hostTag = hostTag;
        BeforeRmiInvocation(summary);
        }

        long t0 = Nettention.Proud.PreciseCurrentTime.GetTimeMs();

        // Call this method.
        bool __ret =ResponseCheckNickname (remote,ctx , clientId, bIsAble );

        if(__ret==false)
        {
        // Error: RMI function that a user did not create has been called. 
        core.ShowNotImplementedRmiWarning(RmiName_ResponseCheckNickname);
        }

        if(enableStubProfiling)
        {
        Nettention.Proud.AfterRmiSummary summary = new Nettention.Proud.AfterRmiSummary();
        summary.rmiID = Common.ResponseCheckNickname;
        summary.rmiName = RmiName_ResponseCheckNickname;
        summary.hostID = remote;
        summary.hostTag = hostTag;
        summary.elapsedTime = Nettention.Proud.PreciseCurrentTime.GetTimeMs()-t0;
        AfterRmiInvocation(summary);
        }
    }
    void ProcessReceivedMessage_OnPlayerJoined(Nettention.Proud.Message __msg, Nettention.Proud.ReceivedMessage pa, Object hostTag, Nettention.Proud.HostID remote)
    {
        Nettention.Proud.RmiContext ctx = new Nettention.Proud.RmiContext();
        ctx.sentFrom=pa.RemoteHostID;
        ctx.relayed=pa.IsRelayed;
        ctx.hostTag=hostTag;
        ctx.encryptMode = pa.EncryptMode;
        ctx.compressMode = pa.CompressMode;
        ctx.rmiID = Common.OnPlayerJoined;

        int clientId; Nettention.Proud.Marshaler.Read(__msg,out clientId);	
string szNickName; Nettention.Proud.Marshaler.Read(__msg,out szNickName);	
float PosX; Nettention.Proud.Marshaler.Read(__msg,out PosX);	
float PosY; Nettention.Proud.Marshaler.Read(__msg,out PosY);	
float PosZ; Nettention.Proud.Marshaler.Read(__msg,out PosZ);	
core.PostCheckReadMessage(__msg, RmiName_OnPlayerJoined);
        if(enableNotifyCallFromStub==true)
        {
        string parameterString = "";
        parameterString+=clientId.ToString()+",";
parameterString+=szNickName.ToString()+",";
parameterString+=PosX.ToString()+",";
parameterString+=PosY.ToString()+",";
parameterString+=PosZ.ToString()+",";
        NotifyCallFromStub(Common.OnPlayerJoined, RmiName_OnPlayerJoined,parameterString);
        }

        if(enableStubProfiling)
        {
        Nettention.Proud.BeforeRmiSummary summary = new Nettention.Proud.BeforeRmiSummary();
        summary.rmiID = Common.OnPlayerJoined;
        summary.rmiName = RmiName_OnPlayerJoined;
        summary.hostID = remote;
        summary.hostTag = hostTag;
        BeforeRmiInvocation(summary);
        }

        long t0 = Nettention.Proud.PreciseCurrentTime.GetTimeMs();

        // Call this method.
        bool __ret =OnPlayerJoined (remote,ctx , clientId, szNickName, PosX, PosY, PosZ );

        if(__ret==false)
        {
        // Error: RMI function that a user did not create has been called. 
        core.ShowNotImplementedRmiWarning(RmiName_OnPlayerJoined);
        }

        if(enableStubProfiling)
        {
        Nettention.Proud.AfterRmiSummary summary = new Nettention.Proud.AfterRmiSummary();
        summary.rmiID = Common.OnPlayerJoined;
        summary.rmiName = RmiName_OnPlayerJoined;
        summary.hostID = remote;
        summary.hostTag = hostTag;
        summary.elapsedTime = Nettention.Proud.PreciseCurrentTime.GetTimeMs()-t0;
        AfterRmiInvocation(summary);
        }
    }
    void ProcessReceivedMessage_SpawnObjectEvent(Nettention.Proud.Message __msg, Nettention.Proud.ReceivedMessage pa, Object hostTag, Nettention.Proud.HostID remote)
    {
        Nettention.Proud.RmiContext ctx = new Nettention.Proud.RmiContext();
        ctx.sentFrom=pa.RemoteHostID;
        ctx.relayed=pa.IsRelayed;
        ctx.hostTag=hostTag;
        ctx.encryptMode = pa.EncryptMode;
        ctx.compressMode = pa.CompressMode;
        ctx.rmiID = Common.SpawnObjectEvent;

        string Key; Nettention.Proud.Marshaler.Read(__msg,out Key);	
int templetedID; Nettention.Proud.Marshaler.Read(__msg,out templetedID);	
float px; Nettention.Proud.Marshaler.Read(__msg,out px);	
float py; Nettention.Proud.Marshaler.Read(__msg,out py);	
float pz; Nettention.Proud.Marshaler.Read(__msg,out pz);	
core.PostCheckReadMessage(__msg, RmiName_SpawnObjectEvent);
        if(enableNotifyCallFromStub==true)
        {
        string parameterString = "";
        parameterString+=Key.ToString()+",";
parameterString+=templetedID.ToString()+",";
parameterString+=px.ToString()+",";
parameterString+=py.ToString()+",";
parameterString+=pz.ToString()+",";
        NotifyCallFromStub(Common.SpawnObjectEvent, RmiName_SpawnObjectEvent,parameterString);
        }

        if(enableStubProfiling)
        {
        Nettention.Proud.BeforeRmiSummary summary = new Nettention.Proud.BeforeRmiSummary();
        summary.rmiID = Common.SpawnObjectEvent;
        summary.rmiName = RmiName_SpawnObjectEvent;
        summary.hostID = remote;
        summary.hostTag = hostTag;
        BeforeRmiInvocation(summary);
        }

        long t0 = Nettention.Proud.PreciseCurrentTime.GetTimeMs();

        // Call this method.
        bool __ret =SpawnObjectEvent (remote,ctx , Key, templetedID, px, py, pz );

        if(__ret==false)
        {
        // Error: RMI function that a user did not create has been called. 
        core.ShowNotImplementedRmiWarning(RmiName_SpawnObjectEvent);
        }

        if(enableStubProfiling)
        {
        Nettention.Proud.AfterRmiSummary summary = new Nettention.Proud.AfterRmiSummary();
        summary.rmiID = Common.SpawnObjectEvent;
        summary.rmiName = RmiName_SpawnObjectEvent;
        summary.hostID = remote;
        summary.hostTag = hostTag;
        summary.elapsedTime = Nettention.Proud.PreciseCurrentTime.GetTimeMs()-t0;
        AfterRmiInvocation(summary);
        }
    }
    void ProcessReceivedMessage_OtherPlayerTransformUpdated(Nettention.Proud.Message __msg, Nettention.Proud.ReceivedMessage pa, Object hostTag, Nettention.Proud.HostID remote)
    {
        Nettention.Proud.RmiContext ctx = new Nettention.Proud.RmiContext();
        ctx.sentFrom=pa.RemoteHostID;
        ctx.relayed=pa.IsRelayed;
        ctx.hostTag=hostTag;
        ctx.encryptMode = pa.EncryptMode;
        ctx.compressMode = pa.CompressMode;
        ctx.rmiID = Common.OtherPlayerTransformUpdated;

        int ClientID; Nettention.Proud.Marshaler.Read(__msg,out ClientID);	
string NickName; Nettention.Proud.Marshaler.Read(__msg,out NickName);	
float ScaleX; Nettention.Proud.Marshaler.Read(__msg,out ScaleX);	
float ScaleY; Nettention.Proud.Marshaler.Read(__msg,out ScaleY);	
float ScaleZ; Nettention.Proud.Marshaler.Read(__msg,out ScaleZ);	
float AngleX; Nettention.Proud.Marshaler.Read(__msg,out AngleX);	
float AngleY; Nettention.Proud.Marshaler.Read(__msg,out AngleY);	
float AngleZ; Nettention.Proud.Marshaler.Read(__msg,out AngleZ);	
float AngleW; Nettention.Proud.Marshaler.Read(__msg,out AngleW);	
float PosX; Nettention.Proud.Marshaler.Read(__msg,out PosX);	
float PosY; Nettention.Proud.Marshaler.Read(__msg,out PosY);	
float PosZ; Nettention.Proud.Marshaler.Read(__msg,out PosZ);	
core.PostCheckReadMessage(__msg, RmiName_OtherPlayerTransformUpdated);
        if(enableNotifyCallFromStub==true)
        {
        string parameterString = "";
        parameterString+=ClientID.ToString()+",";
parameterString+=NickName.ToString()+",";
parameterString+=ScaleX.ToString()+",";
parameterString+=ScaleY.ToString()+",";
parameterString+=ScaleZ.ToString()+",";
parameterString+=AngleX.ToString()+",";
parameterString+=AngleY.ToString()+",";
parameterString+=AngleZ.ToString()+",";
parameterString+=AngleW.ToString()+",";
parameterString+=PosX.ToString()+",";
parameterString+=PosY.ToString()+",";
parameterString+=PosZ.ToString()+",";
        NotifyCallFromStub(Common.OtherPlayerTransformUpdated, RmiName_OtherPlayerTransformUpdated,parameterString);
        }

        if(enableStubProfiling)
        {
        Nettention.Proud.BeforeRmiSummary summary = new Nettention.Proud.BeforeRmiSummary();
        summary.rmiID = Common.OtherPlayerTransformUpdated;
        summary.rmiName = RmiName_OtherPlayerTransformUpdated;
        summary.hostID = remote;
        summary.hostTag = hostTag;
        BeforeRmiInvocation(summary);
        }

        long t0 = Nettention.Proud.PreciseCurrentTime.GetTimeMs();

        // Call this method.
        bool __ret =OtherPlayerTransformUpdated (remote,ctx , ClientID, NickName, ScaleX, ScaleY, ScaleZ, AngleX, AngleY, AngleZ, AngleW, PosX, PosY, PosZ );

        if(__ret==false)
        {
        // Error: RMI function that a user did not create has been called. 
        core.ShowNotImplementedRmiWarning(RmiName_OtherPlayerTransformUpdated);
        }

        if(enableStubProfiling)
        {
        Nettention.Proud.AfterRmiSummary summary = new Nettention.Proud.AfterRmiSummary();
        summary.rmiID = Common.OtherPlayerTransformUpdated;
        summary.rmiName = RmiName_OtherPlayerTransformUpdated;
        summary.hostID = remote;
        summary.hostTag = hostTag;
        summary.elapsedTime = Nettention.Proud.PreciseCurrentTime.GetTimeMs()-t0;
        AfterRmiInvocation(summary);
        }
    }
    void ProcessReceivedMessage_OnPlayerTransformUpdated(Nettention.Proud.Message __msg, Nettention.Proud.ReceivedMessage pa, Object hostTag, Nettention.Proud.HostID remote)
    {
        Nettention.Proud.RmiContext ctx = new Nettention.Proud.RmiContext();
        ctx.sentFrom=pa.RemoteHostID;
        ctx.relayed=pa.IsRelayed;
        ctx.hostTag=hostTag;
        ctx.encryptMode = pa.EncryptMode;
        ctx.compressMode = pa.CompressMode;
        ctx.rmiID = Common.OnPlayerTransformUpdated;

        int clientId; Nettention.Proud.Marshaler.Read(__msg,out clientId);	
float ScaleX; Nettention.Proud.Marshaler.Read(__msg,out ScaleX);	
float ScaleY; Nettention.Proud.Marshaler.Read(__msg,out ScaleY);	
float ScaleZ; Nettention.Proud.Marshaler.Read(__msg,out ScaleZ);	
float AngleX; Nettention.Proud.Marshaler.Read(__msg,out AngleX);	
float AngleY; Nettention.Proud.Marshaler.Read(__msg,out AngleY);	
float AngleZ; Nettention.Proud.Marshaler.Read(__msg,out AngleZ);	
float AngleW; Nettention.Proud.Marshaler.Read(__msg,out AngleW);	
float PosX; Nettention.Proud.Marshaler.Read(__msg,out PosX);	
float PosY; Nettention.Proud.Marshaler.Read(__msg,out PosY);	
float PosZ; Nettention.Proud.Marshaler.Read(__msg,out PosZ);	
core.PostCheckReadMessage(__msg, RmiName_OnPlayerTransformUpdated);
        if(enableNotifyCallFromStub==true)
        {
        string parameterString = "";
        parameterString+=clientId.ToString()+",";
parameterString+=ScaleX.ToString()+",";
parameterString+=ScaleY.ToString()+",";
parameterString+=ScaleZ.ToString()+",";
parameterString+=AngleX.ToString()+",";
parameterString+=AngleY.ToString()+",";
parameterString+=AngleZ.ToString()+",";
parameterString+=AngleW.ToString()+",";
parameterString+=PosX.ToString()+",";
parameterString+=PosY.ToString()+",";
parameterString+=PosZ.ToString()+",";
        NotifyCallFromStub(Common.OnPlayerTransformUpdated, RmiName_OnPlayerTransformUpdated,parameterString);
        }

        if(enableStubProfiling)
        {
        Nettention.Proud.BeforeRmiSummary summary = new Nettention.Proud.BeforeRmiSummary();
        summary.rmiID = Common.OnPlayerTransformUpdated;
        summary.rmiName = RmiName_OnPlayerTransformUpdated;
        summary.hostID = remote;
        summary.hostTag = hostTag;
        BeforeRmiInvocation(summary);
        }

        long t0 = Nettention.Proud.PreciseCurrentTime.GetTimeMs();

        // Call this method.
        bool __ret =OnPlayerTransformUpdated (remote,ctx , clientId, ScaleX, ScaleY, ScaleZ, AngleX, AngleY, AngleZ, AngleW, PosX, PosY, PosZ );

        if(__ret==false)
        {
        // Error: RMI function that a user did not create has been called. 
        core.ShowNotImplementedRmiWarning(RmiName_OnPlayerTransformUpdated);
        }

        if(enableStubProfiling)
        {
        Nettention.Proud.AfterRmiSummary summary = new Nettention.Proud.AfterRmiSummary();
        summary.rmiID = Common.OnPlayerTransformUpdated;
        summary.rmiName = RmiName_OnPlayerTransformUpdated;
        summary.hostID = remote;
        summary.hostTag = hostTag;
        summary.elapsedTime = Nettention.Proud.PreciseCurrentTime.GetTimeMs()-t0;
        AfterRmiInvocation(summary);
        }
    }
    void ProcessReceivedMessage_OtherActorTransformUpdated(Nettention.Proud.Message __msg, Nettention.Proud.ReceivedMessage pa, Object hostTag, Nettention.Proud.HostID remote)
    {
        Nettention.Proud.RmiContext ctx = new Nettention.Proud.RmiContext();
        ctx.sentFrom=pa.RemoteHostID;
        ctx.relayed=pa.IsRelayed;
        ctx.hostTag=hostTag;
        ctx.encryptMode = pa.EncryptMode;
        ctx.compressMode = pa.CompressMode;
        ctx.rmiID = Common.OtherActorTransformUpdated;

        int templeteID; Nettention.Proud.Marshaler.Read(__msg,out templeteID);	
float ScaleX; Nettention.Proud.Marshaler.Read(__msg,out ScaleX);	
float ScaleY; Nettention.Proud.Marshaler.Read(__msg,out ScaleY);	
float ScaleZ; Nettention.Proud.Marshaler.Read(__msg,out ScaleZ);	
float AngleX; Nettention.Proud.Marshaler.Read(__msg,out AngleX);	
float AngleY; Nettention.Proud.Marshaler.Read(__msg,out AngleY);	
float AngleZ; Nettention.Proud.Marshaler.Read(__msg,out AngleZ);	
float AngleW; Nettention.Proud.Marshaler.Read(__msg,out AngleW);	
float PosX; Nettention.Proud.Marshaler.Read(__msg,out PosX);	
float PosY; Nettention.Proud.Marshaler.Read(__msg,out PosY);	
float PosZ; Nettention.Proud.Marshaler.Read(__msg,out PosZ);	
core.PostCheckReadMessage(__msg, RmiName_OtherActorTransformUpdated);
        if(enableNotifyCallFromStub==true)
        {
        string parameterString = "";
        parameterString+=templeteID.ToString()+",";
parameterString+=ScaleX.ToString()+",";
parameterString+=ScaleY.ToString()+",";
parameterString+=ScaleZ.ToString()+",";
parameterString+=AngleX.ToString()+",";
parameterString+=AngleY.ToString()+",";
parameterString+=AngleZ.ToString()+",";
parameterString+=AngleW.ToString()+",";
parameterString+=PosX.ToString()+",";
parameterString+=PosY.ToString()+",";
parameterString+=PosZ.ToString()+",";
        NotifyCallFromStub(Common.OtherActorTransformUpdated, RmiName_OtherActorTransformUpdated,parameterString);
        }

        if(enableStubProfiling)
        {
        Nettention.Proud.BeforeRmiSummary summary = new Nettention.Proud.BeforeRmiSummary();
        summary.rmiID = Common.OtherActorTransformUpdated;
        summary.rmiName = RmiName_OtherActorTransformUpdated;
        summary.hostID = remote;
        summary.hostTag = hostTag;
        BeforeRmiInvocation(summary);
        }

        long t0 = Nettention.Proud.PreciseCurrentTime.GetTimeMs();

        // Call this method.
        bool __ret =OtherActorTransformUpdated (remote,ctx , templeteID, ScaleX, ScaleY, ScaleZ, AngleX, AngleY, AngleZ, AngleW, PosX, PosY, PosZ );

        if(__ret==false)
        {
        // Error: RMI function that a user did not create has been called. 
        core.ShowNotImplementedRmiWarning(RmiName_OtherActorTransformUpdated);
        }

        if(enableStubProfiling)
        {
        Nettention.Proud.AfterRmiSummary summary = new Nettention.Proud.AfterRmiSummary();
        summary.rmiID = Common.OtherActorTransformUpdated;
        summary.rmiName = RmiName_OtherActorTransformUpdated;
        summary.hostID = remote;
        summary.hostTag = hostTag;
        summary.elapsedTime = Nettention.Proud.PreciseCurrentTime.GetTimeMs()-t0;
        AfterRmiInvocation(summary);
        }
    }
    void ProcessReceivedMessage_ActorTransformUpdated(Nettention.Proud.Message __msg, Nettention.Proud.ReceivedMessage pa, Object hostTag, Nettention.Proud.HostID remote)
    {
        Nettention.Proud.RmiContext ctx = new Nettention.Proud.RmiContext();
        ctx.sentFrom=pa.RemoteHostID;
        ctx.relayed=pa.IsRelayed;
        ctx.hostTag=hostTag;
        ctx.encryptMode = pa.EncryptMode;
        ctx.compressMode = pa.CompressMode;
        ctx.rmiID = Common.ActorTransformUpdated;

        int templeteID; Nettention.Proud.Marshaler.Read(__msg,out templeteID);	
float ScaleX; Nettention.Proud.Marshaler.Read(__msg,out ScaleX);	
float ScaleY; Nettention.Proud.Marshaler.Read(__msg,out ScaleY);	
float ScaleZ; Nettention.Proud.Marshaler.Read(__msg,out ScaleZ);	
float AngleX; Nettention.Proud.Marshaler.Read(__msg,out AngleX);	
float AngleY; Nettention.Proud.Marshaler.Read(__msg,out AngleY);	
float AngleZ; Nettention.Proud.Marshaler.Read(__msg,out AngleZ);	
float AngleW; Nettention.Proud.Marshaler.Read(__msg,out AngleW);	
float PosX; Nettention.Proud.Marshaler.Read(__msg,out PosX);	
float PosY; Nettention.Proud.Marshaler.Read(__msg,out PosY);	
float PosZ; Nettention.Proud.Marshaler.Read(__msg,out PosZ);	
core.PostCheckReadMessage(__msg, RmiName_ActorTransformUpdated);
        if(enableNotifyCallFromStub==true)
        {
        string parameterString = "";
        parameterString+=templeteID.ToString()+",";
parameterString+=ScaleX.ToString()+",";
parameterString+=ScaleY.ToString()+",";
parameterString+=ScaleZ.ToString()+",";
parameterString+=AngleX.ToString()+",";
parameterString+=AngleY.ToString()+",";
parameterString+=AngleZ.ToString()+",";
parameterString+=AngleW.ToString()+",";
parameterString+=PosX.ToString()+",";
parameterString+=PosY.ToString()+",";
parameterString+=PosZ.ToString()+",";
        NotifyCallFromStub(Common.ActorTransformUpdated, RmiName_ActorTransformUpdated,parameterString);
        }

        if(enableStubProfiling)
        {
        Nettention.Proud.BeforeRmiSummary summary = new Nettention.Proud.BeforeRmiSummary();
        summary.rmiID = Common.ActorTransformUpdated;
        summary.rmiName = RmiName_ActorTransformUpdated;
        summary.hostID = remote;
        summary.hostTag = hostTag;
        BeforeRmiInvocation(summary);
        }

        long t0 = Nettention.Proud.PreciseCurrentTime.GetTimeMs();

        // Call this method.
        bool __ret =ActorTransformUpdated (remote,ctx , templeteID, ScaleX, ScaleY, ScaleZ, AngleX, AngleY, AngleZ, AngleW, PosX, PosY, PosZ );

        if(__ret==false)
        {
        // Error: RMI function that a user did not create has been called. 
        core.ShowNotImplementedRmiWarning(RmiName_ActorTransformUpdated);
        }

        if(enableStubProfiling)
        {
        Nettention.Proud.AfterRmiSummary summary = new Nettention.Proud.AfterRmiSummary();
        summary.rmiID = Common.ActorTransformUpdated;
        summary.rmiName = RmiName_ActorTransformUpdated;
        summary.hostID = remote;
        summary.hostTag = hostTag;
        summary.elapsedTime = Nettention.Proud.PreciseCurrentTime.GetTimeMs()-t0;
        AfterRmiInvocation(summary);
        }
    }
    void ProcessReceivedMessage_UpdateCharacterAnimState(Nettention.Proud.Message __msg, Nettention.Proud.ReceivedMessage pa, Object hostTag, Nettention.Proud.HostID remote)
    {
        Nettention.Proud.RmiContext ctx = new Nettention.Proud.RmiContext();
        ctx.sentFrom=pa.RemoteHostID;
        ctx.relayed=pa.IsRelayed;
        ctx.hostTag=hostTag;
        ctx.encryptMode = pa.EncryptMode;
        ctx.compressMode = pa.CompressMode;
        ctx.rmiID = Common.UpdateCharacterAnimState;

        int clientId; Nettention.Proud.Marshaler.Read(__msg,out clientId);	
int AnimSate; Nettention.Proud.Marshaler.Read(__msg,out AnimSate);	
float Time; Nettention.Proud.Marshaler.Read(__msg,out Time);	
core.PostCheckReadMessage(__msg, RmiName_UpdateCharacterAnimState);
        if(enableNotifyCallFromStub==true)
        {
        string parameterString = "";
        parameterString+=clientId.ToString()+",";
parameterString+=AnimSate.ToString()+",";
parameterString+=Time.ToString()+",";
        NotifyCallFromStub(Common.UpdateCharacterAnimState, RmiName_UpdateCharacterAnimState,parameterString);
        }

        if(enableStubProfiling)
        {
        Nettention.Proud.BeforeRmiSummary summary = new Nettention.Proud.BeforeRmiSummary();
        summary.rmiID = Common.UpdateCharacterAnimState;
        summary.rmiName = RmiName_UpdateCharacterAnimState;
        summary.hostID = remote;
        summary.hostTag = hostTag;
        BeforeRmiInvocation(summary);
        }

        long t0 = Nettention.Proud.PreciseCurrentTime.GetTimeMs();

        // Call this method.
        bool __ret =UpdateCharacterAnimState (remote,ctx , clientId, AnimSate, Time );

        if(__ret==false)
        {
        // Error: RMI function that a user did not create has been called. 
        core.ShowNotImplementedRmiWarning(RmiName_UpdateCharacterAnimState);
        }

        if(enableStubProfiling)
        {
        Nettention.Proud.AfterRmiSummary summary = new Nettention.Proud.AfterRmiSummary();
        summary.rmiID = Common.UpdateCharacterAnimState;
        summary.rmiName = RmiName_UpdateCharacterAnimState;
        summary.hostID = remote;
        summary.hostTag = hostTag;
        summary.elapsedTime = Nettention.Proud.PreciseCurrentTime.GetTimeMs()-t0;
        AfterRmiInvocation(summary);
        }
    }
    void ProcessReceivedMessage_OnOtherPlayerAnimUpdated(Nettention.Proud.Message __msg, Nettention.Proud.ReceivedMessage pa, Object hostTag, Nettention.Proud.HostID remote)
    {
        Nettention.Proud.RmiContext ctx = new Nettention.Proud.RmiContext();
        ctx.sentFrom=pa.RemoteHostID;
        ctx.relayed=pa.IsRelayed;
        ctx.hostTag=hostTag;
        ctx.encryptMode = pa.EncryptMode;
        ctx.compressMode = pa.CompressMode;
        ctx.rmiID = Common.OnOtherPlayerAnimUpdated;

        int ClientID; Nettention.Proud.Marshaler.Read(__msg,out ClientID);	
int AnimState; Nettention.Proud.Marshaler.Read(__msg,out AnimState);	
int AnimTime; Nettention.Proud.Marshaler.Read(__msg,out AnimTime);	
core.PostCheckReadMessage(__msg, RmiName_OnOtherPlayerAnimUpdated);
        if(enableNotifyCallFromStub==true)
        {
        string parameterString = "";
        parameterString+=ClientID.ToString()+",";
parameterString+=AnimState.ToString()+",";
parameterString+=AnimTime.ToString()+",";
        NotifyCallFromStub(Common.OnOtherPlayerAnimUpdated, RmiName_OnOtherPlayerAnimUpdated,parameterString);
        }

        if(enableStubProfiling)
        {
        Nettention.Proud.BeforeRmiSummary summary = new Nettention.Proud.BeforeRmiSummary();
        summary.rmiID = Common.OnOtherPlayerAnimUpdated;
        summary.rmiName = RmiName_OnOtherPlayerAnimUpdated;
        summary.hostID = remote;
        summary.hostTag = hostTag;
        BeforeRmiInvocation(summary);
        }

        long t0 = Nettention.Proud.PreciseCurrentTime.GetTimeMs();

        // Call this method.
        bool __ret =OnOtherPlayerAnimUpdated (remote,ctx , ClientID, AnimState, AnimTime );

        if(__ret==false)
        {
        // Error: RMI function that a user did not create has been called. 
        core.ShowNotImplementedRmiWarning(RmiName_OnOtherPlayerAnimUpdated);
        }

        if(enableStubProfiling)
        {
        Nettention.Proud.AfterRmiSummary summary = new Nettention.Proud.AfterRmiSummary();
        summary.rmiID = Common.OnOtherPlayerAnimUpdated;
        summary.rmiName = RmiName_OnOtherPlayerAnimUpdated;
        summary.hostID = remote;
        summary.hostTag = hostTag;
        summary.elapsedTime = Nettention.Proud.PreciseCurrentTime.GetTimeMs()-t0;
        AfterRmiInvocation(summary);
        }
    }
    void ProcessReceivedMessage_UpdateActorAnimState(Nettention.Proud.Message __msg, Nettention.Proud.ReceivedMessage pa, Object hostTag, Nettention.Proud.HostID remote)
    {
        Nettention.Proud.RmiContext ctx = new Nettention.Proud.RmiContext();
        ctx.sentFrom=pa.RemoteHostID;
        ctx.relayed=pa.IsRelayed;
        ctx.hostTag=hostTag;
        ctx.encryptMode = pa.EncryptMode;
        ctx.compressMode = pa.CompressMode;
        ctx.rmiID = Common.UpdateActorAnimState;

        int templeteID; Nettention.Proud.Marshaler.Read(__msg,out templeteID);	
int AnimSate; Nettention.Proud.Marshaler.Read(__msg,out AnimSate);	
float Time; Nettention.Proud.Marshaler.Read(__msg,out Time);	
core.PostCheckReadMessage(__msg, RmiName_UpdateActorAnimState);
        if(enableNotifyCallFromStub==true)
        {
        string parameterString = "";
        parameterString+=templeteID.ToString()+",";
parameterString+=AnimSate.ToString()+",";
parameterString+=Time.ToString()+",";
        NotifyCallFromStub(Common.UpdateActorAnimState, RmiName_UpdateActorAnimState,parameterString);
        }

        if(enableStubProfiling)
        {
        Nettention.Proud.BeforeRmiSummary summary = new Nettention.Proud.BeforeRmiSummary();
        summary.rmiID = Common.UpdateActorAnimState;
        summary.rmiName = RmiName_UpdateActorAnimState;
        summary.hostID = remote;
        summary.hostTag = hostTag;
        BeforeRmiInvocation(summary);
        }

        long t0 = Nettention.Proud.PreciseCurrentTime.GetTimeMs();

        // Call this method.
        bool __ret =UpdateActorAnimState (remote,ctx , templeteID, AnimSate, Time );

        if(__ret==false)
        {
        // Error: RMI function that a user did not create has been called. 
        core.ShowNotImplementedRmiWarning(RmiName_UpdateActorAnimState);
        }

        if(enableStubProfiling)
        {
        Nettention.Proud.AfterRmiSummary summary = new Nettention.Proud.AfterRmiSummary();
        summary.rmiID = Common.UpdateActorAnimState;
        summary.rmiName = RmiName_UpdateActorAnimState;
        summary.hostID = remote;
        summary.hostTag = hostTag;
        summary.elapsedTime = Nettention.Proud.PreciseCurrentTime.GetTimeMs()-t0;
        AfterRmiInvocation(summary);
        }
    }
    void ProcessReceivedMessage_OnOtherActorAnimUpdated(Nettention.Proud.Message __msg, Nettention.Proud.ReceivedMessage pa, Object hostTag, Nettention.Proud.HostID remote)
    {
        Nettention.Proud.RmiContext ctx = new Nettention.Proud.RmiContext();
        ctx.sentFrom=pa.RemoteHostID;
        ctx.relayed=pa.IsRelayed;
        ctx.hostTag=hostTag;
        ctx.encryptMode = pa.EncryptMode;
        ctx.compressMode = pa.CompressMode;
        ctx.rmiID = Common.OnOtherActorAnimUpdated;

        int templeteID; Nettention.Proud.Marshaler.Read(__msg,out templeteID);	
int AnimState; Nettention.Proud.Marshaler.Read(__msg,out AnimState);	
int AnimTime; Nettention.Proud.Marshaler.Read(__msg,out AnimTime);	
core.PostCheckReadMessage(__msg, RmiName_OnOtherActorAnimUpdated);
        if(enableNotifyCallFromStub==true)
        {
        string parameterString = "";
        parameterString+=templeteID.ToString()+",";
parameterString+=AnimState.ToString()+",";
parameterString+=AnimTime.ToString()+",";
        NotifyCallFromStub(Common.OnOtherActorAnimUpdated, RmiName_OnOtherActorAnimUpdated,parameterString);
        }

        if(enableStubProfiling)
        {
        Nettention.Proud.BeforeRmiSummary summary = new Nettention.Proud.BeforeRmiSummary();
        summary.rmiID = Common.OnOtherActorAnimUpdated;
        summary.rmiName = RmiName_OnOtherActorAnimUpdated;
        summary.hostID = remote;
        summary.hostTag = hostTag;
        BeforeRmiInvocation(summary);
        }

        long t0 = Nettention.Proud.PreciseCurrentTime.GetTimeMs();

        // Call this method.
        bool __ret =OnOtherActorAnimUpdated (remote,ctx , templeteID, AnimState, AnimTime );

        if(__ret==false)
        {
        // Error: RMI function that a user did not create has been called. 
        core.ShowNotImplementedRmiWarning(RmiName_OnOtherActorAnimUpdated);
        }

        if(enableStubProfiling)
        {
        Nettention.Proud.AfterRmiSummary summary = new Nettention.Proud.AfterRmiSummary();
        summary.rmiID = Common.OnOtherActorAnimUpdated;
        summary.rmiName = RmiName_OnOtherActorAnimUpdated;
        summary.hostID = remote;
        summary.hostTag = hostTag;
        summary.elapsedTime = Nettention.Proud.PreciseCurrentTime.GetTimeMs()-t0;
        AfterRmiInvocation(summary);
        }
    }
    void ProcessReceivedMessage_Request_AddItem(Nettention.Proud.Message __msg, Nettention.Proud.ReceivedMessage pa, Object hostTag, Nettention.Proud.HostID remote)
    {
        Nettention.Proud.RmiContext ctx = new Nettention.Proud.RmiContext();
        ctx.sentFrom=pa.RemoteHostID;
        ctx.relayed=pa.IsRelayed;
        ctx.hostTag=hostTag;
        ctx.encryptMode = pa.EncryptMode;
        ctx.compressMode = pa.CompressMode;
        ctx.rmiID = Common.Request_AddItem;

        int iClientID; Nettention.Proud.Marshaler.Read(__msg,out iClientID);	
int iItemID; Nettention.Proud.Marshaler.Read(__msg,out iItemID);	
int iItemCount; Nettention.Proud.Marshaler.Read(__msg,out iItemCount);	
core.PostCheckReadMessage(__msg, RmiName_Request_AddItem);
        if(enableNotifyCallFromStub==true)
        {
        string parameterString = "";
        parameterString+=iClientID.ToString()+",";
parameterString+=iItemID.ToString()+",";
parameterString+=iItemCount.ToString()+",";
        NotifyCallFromStub(Common.Request_AddItem, RmiName_Request_AddItem,parameterString);
        }

        if(enableStubProfiling)
        {
        Nettention.Proud.BeforeRmiSummary summary = new Nettention.Proud.BeforeRmiSummary();
        summary.rmiID = Common.Request_AddItem;
        summary.rmiName = RmiName_Request_AddItem;
        summary.hostID = remote;
        summary.hostTag = hostTag;
        BeforeRmiInvocation(summary);
        }

        long t0 = Nettention.Proud.PreciseCurrentTime.GetTimeMs();

        // Call this method.
        bool __ret =Request_AddItem (remote,ctx , iClientID, iItemID, iItemCount );

        if(__ret==false)
        {
        // Error: RMI function that a user did not create has been called. 
        core.ShowNotImplementedRmiWarning(RmiName_Request_AddItem);
        }

        if(enableStubProfiling)
        {
        Nettention.Proud.AfterRmiSummary summary = new Nettention.Proud.AfterRmiSummary();
        summary.rmiID = Common.Request_AddItem;
        summary.rmiName = RmiName_Request_AddItem;
        summary.hostID = remote;
        summary.hostTag = hostTag;
        summary.elapsedTime = Nettention.Proud.PreciseCurrentTime.GetTimeMs()-t0;
        AfterRmiInvocation(summary);
        }
    }
    void ProcessReceivedMessage_Request_RemoveItem(Nettention.Proud.Message __msg, Nettention.Proud.ReceivedMessage pa, Object hostTag, Nettention.Proud.HostID remote)
    {
        Nettention.Proud.RmiContext ctx = new Nettention.Proud.RmiContext();
        ctx.sentFrom=pa.RemoteHostID;
        ctx.relayed=pa.IsRelayed;
        ctx.hostTag=hostTag;
        ctx.encryptMode = pa.EncryptMode;
        ctx.compressMode = pa.CompressMode;
        ctx.rmiID = Common.Request_RemoveItem;

        int iClientID; Nettention.Proud.Marshaler.Read(__msg,out iClientID);	
int iItemID; Nettention.Proud.Marshaler.Read(__msg,out iItemID);	
int iItemCount; Nettention.Proud.Marshaler.Read(__msg,out iItemCount);	
core.PostCheckReadMessage(__msg, RmiName_Request_RemoveItem);
        if(enableNotifyCallFromStub==true)
        {
        string parameterString = "";
        parameterString+=iClientID.ToString()+",";
parameterString+=iItemID.ToString()+",";
parameterString+=iItemCount.ToString()+",";
        NotifyCallFromStub(Common.Request_RemoveItem, RmiName_Request_RemoveItem,parameterString);
        }

        if(enableStubProfiling)
        {
        Nettention.Proud.BeforeRmiSummary summary = new Nettention.Proud.BeforeRmiSummary();
        summary.rmiID = Common.Request_RemoveItem;
        summary.rmiName = RmiName_Request_RemoveItem;
        summary.hostID = remote;
        summary.hostTag = hostTag;
        BeforeRmiInvocation(summary);
        }

        long t0 = Nettention.Proud.PreciseCurrentTime.GetTimeMs();

        // Call this method.
        bool __ret =Request_RemoveItem (remote,ctx , iClientID, iItemID, iItemCount );

        if(__ret==false)
        {
        // Error: RMI function that a user did not create has been called. 
        core.ShowNotImplementedRmiWarning(RmiName_Request_RemoveItem);
        }

        if(enableStubProfiling)
        {
        Nettention.Proud.AfterRmiSummary summary = new Nettention.Proud.AfterRmiSummary();
        summary.rmiID = Common.Request_RemoveItem;
        summary.rmiName = RmiName_Request_RemoveItem;
        summary.hostID = remote;
        summary.hostTag = hostTag;
        summary.elapsedTime = Nettention.Proud.PreciseCurrentTime.GetTimeMs()-t0;
        AfterRmiInvocation(summary);
        }
    }
    void ProcessReceivedMessage_Request_ItemData(Nettention.Proud.Message __msg, Nettention.Proud.ReceivedMessage pa, Object hostTag, Nettention.Proud.HostID remote)
    {
        Nettention.Proud.RmiContext ctx = new Nettention.Proud.RmiContext();
        ctx.sentFrom=pa.RemoteHostID;
        ctx.relayed=pa.IsRelayed;
        ctx.hostTag=hostTag;
        ctx.encryptMode = pa.EncryptMode;
        ctx.compressMode = pa.CompressMode;
        ctx.rmiID = Common.Request_ItemData;

        int iClientID; Nettention.Proud.Marshaler.Read(__msg,out iClientID);	
int iItemID; Nettention.Proud.Marshaler.Read(__msg,out iItemID);	
core.PostCheckReadMessage(__msg, RmiName_Request_ItemData);
        if(enableNotifyCallFromStub==true)
        {
        string parameterString = "";
        parameterString+=iClientID.ToString()+",";
parameterString+=iItemID.ToString()+",";
        NotifyCallFromStub(Common.Request_ItemData, RmiName_Request_ItemData,parameterString);
        }

        if(enableStubProfiling)
        {
        Nettention.Proud.BeforeRmiSummary summary = new Nettention.Proud.BeforeRmiSummary();
        summary.rmiID = Common.Request_ItemData;
        summary.rmiName = RmiName_Request_ItemData;
        summary.hostID = remote;
        summary.hostTag = hostTag;
        BeforeRmiInvocation(summary);
        }

        long t0 = Nettention.Proud.PreciseCurrentTime.GetTimeMs();

        // Call this method.
        bool __ret =Request_ItemData (remote,ctx , iClientID, iItemID );

        if(__ret==false)
        {
        // Error: RMI function that a user did not create has been called. 
        core.ShowNotImplementedRmiWarning(RmiName_Request_ItemData);
        }

        if(enableStubProfiling)
        {
        Nettention.Proud.AfterRmiSummary summary = new Nettention.Proud.AfterRmiSummary();
        summary.rmiID = Common.Request_ItemData;
        summary.rmiName = RmiName_Request_ItemData;
        summary.hostID = remote;
        summary.hostTag = hostTag;
        summary.elapsedTime = Nettention.Proud.PreciseCurrentTime.GetTimeMs()-t0;
        AfterRmiInvocation(summary);
        }
    }
    void ProcessReceivedMessage_Request_AddGold(Nettention.Proud.Message __msg, Nettention.Proud.ReceivedMessage pa, Object hostTag, Nettention.Proud.HostID remote)
    {
        Nettention.Proud.RmiContext ctx = new Nettention.Proud.RmiContext();
        ctx.sentFrom=pa.RemoteHostID;
        ctx.relayed=pa.IsRelayed;
        ctx.hostTag=hostTag;
        ctx.encryptMode = pa.EncryptMode;
        ctx.compressMode = pa.CompressMode;
        ctx.rmiID = Common.Request_AddGold;

        int ClientID; Nettention.Proud.Marshaler.Read(__msg,out ClientID);	
int GoldAmount; Nettention.Proud.Marshaler.Read(__msg,out GoldAmount);	
core.PostCheckReadMessage(__msg, RmiName_Request_AddGold);
        if(enableNotifyCallFromStub==true)
        {
        string parameterString = "";
        parameterString+=ClientID.ToString()+",";
parameterString+=GoldAmount.ToString()+",";
        NotifyCallFromStub(Common.Request_AddGold, RmiName_Request_AddGold,parameterString);
        }

        if(enableStubProfiling)
        {
        Nettention.Proud.BeforeRmiSummary summary = new Nettention.Proud.BeforeRmiSummary();
        summary.rmiID = Common.Request_AddGold;
        summary.rmiName = RmiName_Request_AddGold;
        summary.hostID = remote;
        summary.hostTag = hostTag;
        BeforeRmiInvocation(summary);
        }

        long t0 = Nettention.Proud.PreciseCurrentTime.GetTimeMs();

        // Call this method.
        bool __ret =Request_AddGold (remote,ctx , ClientID, GoldAmount );

        if(__ret==false)
        {
        // Error: RMI function that a user did not create has been called. 
        core.ShowNotImplementedRmiWarning(RmiName_Request_AddGold);
        }

        if(enableStubProfiling)
        {
        Nettention.Proud.AfterRmiSummary summary = new Nettention.Proud.AfterRmiSummary();
        summary.rmiID = Common.Request_AddGold;
        summary.rmiName = RmiName_Request_AddGold;
        summary.hostID = remote;
        summary.hostTag = hostTag;
        summary.elapsedTime = Nettention.Proud.PreciseCurrentTime.GetTimeMs()-t0;
        AfterRmiInvocation(summary);
        }
    }
    void ProcessReceivedMessage_OnChat(Nettention.Proud.Message __msg, Nettention.Proud.ReceivedMessage pa, Object hostTag, Nettention.Proud.HostID remote)
    {
        Nettention.Proud.RmiContext ctx = new Nettention.Proud.RmiContext();
        ctx.sentFrom=pa.RemoteHostID;
        ctx.relayed=pa.IsRelayed;
        ctx.hostTag=hostTag;
        ctx.encryptMode = pa.EncryptMode;
        ctx.compressMode = pa.CompressMode;
        ctx.rmiID = Common.OnChat;

        int clientId; Nettention.Proud.Marshaler.Read(__msg,out clientId);	
string message; Nettention.Proud.Marshaler.Read(__msg,out message);	
core.PostCheckReadMessage(__msg, RmiName_OnChat);
        if(enableNotifyCallFromStub==true)
        {
        string parameterString = "";
        parameterString+=clientId.ToString()+",";
parameterString+=message.ToString()+",";
        NotifyCallFromStub(Common.OnChat, RmiName_OnChat,parameterString);
        }

        if(enableStubProfiling)
        {
        Nettention.Proud.BeforeRmiSummary summary = new Nettention.Proud.BeforeRmiSummary();
        summary.rmiID = Common.OnChat;
        summary.rmiName = RmiName_OnChat;
        summary.hostID = remote;
        summary.hostTag = hostTag;
        BeforeRmiInvocation(summary);
        }

        long t0 = Nettention.Proud.PreciseCurrentTime.GetTimeMs();

        // Call this method.
        bool __ret =OnChat (remote,ctx , clientId, message );

        if(__ret==false)
        {
        // Error: RMI function that a user did not create has been called. 
        core.ShowNotImplementedRmiWarning(RmiName_OnChat);
        }

        if(enableStubProfiling)
        {
        Nettention.Proud.AfterRmiSummary summary = new Nettention.Proud.AfterRmiSummary();
        summary.rmiID = Common.OnChat;
        summary.rmiName = RmiName_OnChat;
        summary.hostID = remote;
        summary.hostTag = hostTag;
        summary.elapsedTime = Nettention.Proud.PreciseCurrentTime.GetTimeMs()-t0;
        AfterRmiInvocation(summary);
        }
    }
		#if USE_RMI_NAME_STRING
// RMI name declaration.
// It is the unique pointer that indicates RMI name such as RMI profiler.
public const string RmiName_ResponseLoginEvent="ResponseLoginEvent";
public const string RmiName_ResponseCheckNickname="ResponseCheckNickname";
public const string RmiName_OnPlayerJoined="OnPlayerJoined";
public const string RmiName_SpawnObjectEvent="SpawnObjectEvent";
public const string RmiName_OtherPlayerTransformUpdated="OtherPlayerTransformUpdated";
public const string RmiName_OnPlayerTransformUpdated="OnPlayerTransformUpdated";
public const string RmiName_OtherActorTransformUpdated="OtherActorTransformUpdated";
public const string RmiName_ActorTransformUpdated="ActorTransformUpdated";
public const string RmiName_UpdateCharacterAnimState="UpdateCharacterAnimState";
public const string RmiName_OnOtherPlayerAnimUpdated="OnOtherPlayerAnimUpdated";
public const string RmiName_UpdateActorAnimState="UpdateActorAnimState";
public const string RmiName_OnOtherActorAnimUpdated="OnOtherActorAnimUpdated";
public const string RmiName_Request_AddItem="Request_AddItem";
public const string RmiName_Request_RemoveItem="Request_RemoveItem";
public const string RmiName_Request_ItemData="Request_ItemData";
public const string RmiName_Request_AddGold="Request_AddGold";
public const string RmiName_OnChat="OnChat";
       
public const string RmiName_First = RmiName_ResponseLoginEvent;
		#else
// RMI name declaration.
// It is the unique pointer that indicates RMI name such as RMI profiler.
public const string RmiName_ResponseLoginEvent="";
public const string RmiName_ResponseCheckNickname="";
public const string RmiName_OnPlayerJoined="";
public const string RmiName_SpawnObjectEvent="";
public const string RmiName_OtherPlayerTransformUpdated="";
public const string RmiName_OnPlayerTransformUpdated="";
public const string RmiName_OtherActorTransformUpdated="";
public const string RmiName_ActorTransformUpdated="";
public const string RmiName_UpdateCharacterAnimState="";
public const string RmiName_OnOtherPlayerAnimUpdated="";
public const string RmiName_UpdateActorAnimState="";
public const string RmiName_OnOtherActorAnimUpdated="";
public const string RmiName_Request_AddItem="";
public const string RmiName_Request_RemoveItem="";
public const string RmiName_Request_ItemData="";
public const string RmiName_Request_AddGold="";
public const string RmiName_OnChat="";
       
public const string RmiName_First = "";
		#endif

		public override Nettention.Proud.RmiID[] GetRmiIDList { get{return Common.RmiIDList;} }
		
	}
}

