
// Generated by PIDL compiler.
// Do not modify this file, but modify the source .pidl file.


#include "ClientRmi_common.h"
namespace ClientToServer {


	::Proud::RmiID g_RmiIDList[] = {
               
		Rmi_OnGameLogin,
               
		Rmi_Create_Character,
               
		Rmi_SpawnObjectEvent,
               
		Rmi_SpawnPlayerEvent,
               
		Rmi_RequestCheckNickname,
               
		Rmi_OnPositionUpdated,
               
		Rmi_OnActorPositionUpdated,
               
		Rmi_OnAnimUpdated,
               
		Rmi_OnActorAnimUpdated,
               
		Rmi_OnChat,
	};

	int g_RmiIDListCount = 10;

}





