




// Generated by PIDL compiler.
// Do not modify this file, but modify the source .pidl file.

#include "pch.h"
#include "ServerRmi_proxy.h"

namespace ServerToClient {


        
	bool Proxy::ResponseLoginEvent ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const bool & bIsSuccess, const int & ErrorType)	{
		::Proud::CMessage __msg;
__msg.UseInternalBuffer();
__msg.SetSimplePacketMode(m_core->IsSimplePacketMode());

::Proud::RmiID __msgid=(::Proud::RmiID)Rmi_ResponseLoginEvent;
__msg.Write(__msgid); 
	
__msg << bIsSuccess;
__msg << ErrorType;
		
		return RmiSend(&remote,1,rmiContext,__msg,
			RmiName_ResponseLoginEvent, (::Proud::RmiID)Rmi_ResponseLoginEvent);
	}

	bool Proxy::ResponseLoginEvent ( ::Proud::HostID *remotes, int remoteCount, ::Proud::RmiContext &rmiContext, const bool & bIsSuccess, const int & ErrorType)  	{
		::Proud::CMessage __msg;
__msg.UseInternalBuffer();
__msg.SetSimplePacketMode(m_core->IsSimplePacketMode());

::Proud::RmiID __msgid=(::Proud::RmiID)Rmi_ResponseLoginEvent;
__msg.Write(__msgid); 
	
__msg << bIsSuccess;
__msg << ErrorType;
		
		return RmiSend(remotes,remoteCount,rmiContext,__msg,
			RmiName_ResponseLoginEvent, (::Proud::RmiID)Rmi_ResponseLoginEvent);
	}
        
	bool Proxy::ResponseCheckNickname ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & clientId, const bool & bIsAble)	{
		::Proud::CMessage __msg;
__msg.UseInternalBuffer();
__msg.SetSimplePacketMode(m_core->IsSimplePacketMode());

::Proud::RmiID __msgid=(::Proud::RmiID)Rmi_ResponseCheckNickname;
__msg.Write(__msgid); 
	
__msg << clientId;
__msg << bIsAble;
		
		return RmiSend(&remote,1,rmiContext,__msg,
			RmiName_ResponseCheckNickname, (::Proud::RmiID)Rmi_ResponseCheckNickname);
	}

	bool Proxy::ResponseCheckNickname ( ::Proud::HostID *remotes, int remoteCount, ::Proud::RmiContext &rmiContext, const int & clientId, const bool & bIsAble)  	{
		::Proud::CMessage __msg;
__msg.UseInternalBuffer();
__msg.SetSimplePacketMode(m_core->IsSimplePacketMode());

::Proud::RmiID __msgid=(::Proud::RmiID)Rmi_ResponseCheckNickname;
__msg.Write(__msgid); 
	
__msg << clientId;
__msg << bIsAble;
		
		return RmiSend(remotes,remoteCount,rmiContext,__msg,
			RmiName_ResponseCheckNickname, (::Proud::RmiID)Rmi_ResponseCheckNickname);
	}
        
	bool Proxy::OnPlayerJoined ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & clientId, const string & szNickName, const float & PosX, const float & PosY, const float & PosZ)	{
		::Proud::CMessage __msg;
__msg.UseInternalBuffer();
__msg.SetSimplePacketMode(m_core->IsSimplePacketMode());

::Proud::RmiID __msgid=(::Proud::RmiID)Rmi_OnPlayerJoined;
__msg.Write(__msgid); 
	
__msg << clientId;
__msg << szNickName;
__msg << PosX;
__msg << PosY;
__msg << PosZ;
		
		return RmiSend(&remote,1,rmiContext,__msg,
			RmiName_OnPlayerJoined, (::Proud::RmiID)Rmi_OnPlayerJoined);
	}

	bool Proxy::OnPlayerJoined ( ::Proud::HostID *remotes, int remoteCount, ::Proud::RmiContext &rmiContext, const int & clientId, const string & szNickName, const float & PosX, const float & PosY, const float & PosZ)  	{
		::Proud::CMessage __msg;
__msg.UseInternalBuffer();
__msg.SetSimplePacketMode(m_core->IsSimplePacketMode());

::Proud::RmiID __msgid=(::Proud::RmiID)Rmi_OnPlayerJoined;
__msg.Write(__msgid); 
	
__msg << clientId;
__msg << szNickName;
__msg << PosX;
__msg << PosY;
__msg << PosZ;
		
		return RmiSend(remotes,remoteCount,rmiContext,__msg,
			RmiName_OnPlayerJoined, (::Proud::RmiID)Rmi_OnPlayerJoined);
	}
        
	bool Proxy::SpawnObjectEvent ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const string & Key, const int & templetedID, const float & px, const float & py, const float & pz)	{
		::Proud::CMessage __msg;
__msg.UseInternalBuffer();
__msg.SetSimplePacketMode(m_core->IsSimplePacketMode());

::Proud::RmiID __msgid=(::Proud::RmiID)Rmi_SpawnObjectEvent;
__msg.Write(__msgid); 
	
__msg << Key;
__msg << templetedID;
__msg << px;
__msg << py;
__msg << pz;
		
		return RmiSend(&remote,1,rmiContext,__msg,
			RmiName_SpawnObjectEvent, (::Proud::RmiID)Rmi_SpawnObjectEvent);
	}

	bool Proxy::SpawnObjectEvent ( ::Proud::HostID *remotes, int remoteCount, ::Proud::RmiContext &rmiContext, const string & Key, const int & templetedID, const float & px, const float & py, const float & pz)  	{
		::Proud::CMessage __msg;
__msg.UseInternalBuffer();
__msg.SetSimplePacketMode(m_core->IsSimplePacketMode());

::Proud::RmiID __msgid=(::Proud::RmiID)Rmi_SpawnObjectEvent;
__msg.Write(__msgid); 
	
__msg << Key;
__msg << templetedID;
__msg << px;
__msg << py;
__msg << pz;
		
		return RmiSend(remotes,remoteCount,rmiContext,__msg,
			RmiName_SpawnObjectEvent, (::Proud::RmiID)Rmi_SpawnObjectEvent);
	}
        
	bool Proxy::OtherPlayerTransformUpdated ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & ClientID, const string & NickName, const float & ScaleX, const float & ScaleY, const float & ScaleZ, const float & AngleX, const float & AngleY, const float & AngleZ, const float & AngleW, const float & PosX, const float & PosY, const float & PosZ)	{
		::Proud::CMessage __msg;
__msg.UseInternalBuffer();
__msg.SetSimplePacketMode(m_core->IsSimplePacketMode());

::Proud::RmiID __msgid=(::Proud::RmiID)Rmi_OtherPlayerTransformUpdated;
__msg.Write(__msgid); 
	
__msg << ClientID;
__msg << NickName;
__msg << ScaleX;
__msg << ScaleY;
__msg << ScaleZ;
__msg << AngleX;
__msg << AngleY;
__msg << AngleZ;
__msg << AngleW;
__msg << PosX;
__msg << PosY;
__msg << PosZ;
		
		return RmiSend(&remote,1,rmiContext,__msg,
			RmiName_OtherPlayerTransformUpdated, (::Proud::RmiID)Rmi_OtherPlayerTransformUpdated);
	}

	bool Proxy::OtherPlayerTransformUpdated ( ::Proud::HostID *remotes, int remoteCount, ::Proud::RmiContext &rmiContext, const int & ClientID, const string & NickName, const float & ScaleX, const float & ScaleY, const float & ScaleZ, const float & AngleX, const float & AngleY, const float & AngleZ, const float & AngleW, const float & PosX, const float & PosY, const float & PosZ)  	{
		::Proud::CMessage __msg;
__msg.UseInternalBuffer();
__msg.SetSimplePacketMode(m_core->IsSimplePacketMode());

::Proud::RmiID __msgid=(::Proud::RmiID)Rmi_OtherPlayerTransformUpdated;
__msg.Write(__msgid); 
	
__msg << ClientID;
__msg << NickName;
__msg << ScaleX;
__msg << ScaleY;
__msg << ScaleZ;
__msg << AngleX;
__msg << AngleY;
__msg << AngleZ;
__msg << AngleW;
__msg << PosX;
__msg << PosY;
__msg << PosZ;
		
		return RmiSend(remotes,remoteCount,rmiContext,__msg,
			RmiName_OtherPlayerTransformUpdated, (::Proud::RmiID)Rmi_OtherPlayerTransformUpdated);
	}
        
	bool Proxy::OnPlayerTransformUpdated ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & clientId, const float & ScaleX, const float & ScaleY, const float & ScaleZ, const float & AngleX, const float & AngleY, const float & AngleZ, const float & AngleW, const float & PosX, const float & PosY, const float & PosZ)	{
		::Proud::CMessage __msg;
__msg.UseInternalBuffer();
__msg.SetSimplePacketMode(m_core->IsSimplePacketMode());

::Proud::RmiID __msgid=(::Proud::RmiID)Rmi_OnPlayerTransformUpdated;
__msg.Write(__msgid); 
	
__msg << clientId;
__msg << ScaleX;
__msg << ScaleY;
__msg << ScaleZ;
__msg << AngleX;
__msg << AngleY;
__msg << AngleZ;
__msg << AngleW;
__msg << PosX;
__msg << PosY;
__msg << PosZ;
		
		return RmiSend(&remote,1,rmiContext,__msg,
			RmiName_OnPlayerTransformUpdated, (::Proud::RmiID)Rmi_OnPlayerTransformUpdated);
	}

	bool Proxy::OnPlayerTransformUpdated ( ::Proud::HostID *remotes, int remoteCount, ::Proud::RmiContext &rmiContext, const int & clientId, const float & ScaleX, const float & ScaleY, const float & ScaleZ, const float & AngleX, const float & AngleY, const float & AngleZ, const float & AngleW, const float & PosX, const float & PosY, const float & PosZ)  	{
		::Proud::CMessage __msg;
__msg.UseInternalBuffer();
__msg.SetSimplePacketMode(m_core->IsSimplePacketMode());

::Proud::RmiID __msgid=(::Proud::RmiID)Rmi_OnPlayerTransformUpdated;
__msg.Write(__msgid); 
	
__msg << clientId;
__msg << ScaleX;
__msg << ScaleY;
__msg << ScaleZ;
__msg << AngleX;
__msg << AngleY;
__msg << AngleZ;
__msg << AngleW;
__msg << PosX;
__msg << PosY;
__msg << PosZ;
		
		return RmiSend(remotes,remoteCount,rmiContext,__msg,
			RmiName_OnPlayerTransformUpdated, (::Proud::RmiID)Rmi_OnPlayerTransformUpdated);
	}
        
	bool Proxy::OtherActorTransformUpdated ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & templeteID, const float & ScaleX, const float & ScaleY, const float & ScaleZ, const float & AngleX, const float & AngleY, const float & AngleZ, const float & AngleW, const float & PosX, const float & PosY, const float & PosZ)	{
		::Proud::CMessage __msg;
__msg.UseInternalBuffer();
__msg.SetSimplePacketMode(m_core->IsSimplePacketMode());

::Proud::RmiID __msgid=(::Proud::RmiID)Rmi_OtherActorTransformUpdated;
__msg.Write(__msgid); 
	
__msg << templeteID;
__msg << ScaleX;
__msg << ScaleY;
__msg << ScaleZ;
__msg << AngleX;
__msg << AngleY;
__msg << AngleZ;
__msg << AngleW;
__msg << PosX;
__msg << PosY;
__msg << PosZ;
		
		return RmiSend(&remote,1,rmiContext,__msg,
			RmiName_OtherActorTransformUpdated, (::Proud::RmiID)Rmi_OtherActorTransformUpdated);
	}

	bool Proxy::OtherActorTransformUpdated ( ::Proud::HostID *remotes, int remoteCount, ::Proud::RmiContext &rmiContext, const int & templeteID, const float & ScaleX, const float & ScaleY, const float & ScaleZ, const float & AngleX, const float & AngleY, const float & AngleZ, const float & AngleW, const float & PosX, const float & PosY, const float & PosZ)  	{
		::Proud::CMessage __msg;
__msg.UseInternalBuffer();
__msg.SetSimplePacketMode(m_core->IsSimplePacketMode());

::Proud::RmiID __msgid=(::Proud::RmiID)Rmi_OtherActorTransformUpdated;
__msg.Write(__msgid); 
	
__msg << templeteID;
__msg << ScaleX;
__msg << ScaleY;
__msg << ScaleZ;
__msg << AngleX;
__msg << AngleY;
__msg << AngleZ;
__msg << AngleW;
__msg << PosX;
__msg << PosY;
__msg << PosZ;
		
		return RmiSend(remotes,remoteCount,rmiContext,__msg,
			RmiName_OtherActorTransformUpdated, (::Proud::RmiID)Rmi_OtherActorTransformUpdated);
	}
        
	bool Proxy::ActorTransformUpdated ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & templeteID, const float & ScaleX, const float & ScaleY, const float & ScaleZ, const float & AngleX, const float & AngleY, const float & AngleZ, const float & AngleW, const float & PosX, const float & PosY, const float & PosZ)	{
		::Proud::CMessage __msg;
__msg.UseInternalBuffer();
__msg.SetSimplePacketMode(m_core->IsSimplePacketMode());

::Proud::RmiID __msgid=(::Proud::RmiID)Rmi_ActorTransformUpdated;
__msg.Write(__msgid); 
	
__msg << templeteID;
__msg << ScaleX;
__msg << ScaleY;
__msg << ScaleZ;
__msg << AngleX;
__msg << AngleY;
__msg << AngleZ;
__msg << AngleW;
__msg << PosX;
__msg << PosY;
__msg << PosZ;
		
		return RmiSend(&remote,1,rmiContext,__msg,
			RmiName_ActorTransformUpdated, (::Proud::RmiID)Rmi_ActorTransformUpdated);
	}

	bool Proxy::ActorTransformUpdated ( ::Proud::HostID *remotes, int remoteCount, ::Proud::RmiContext &rmiContext, const int & templeteID, const float & ScaleX, const float & ScaleY, const float & ScaleZ, const float & AngleX, const float & AngleY, const float & AngleZ, const float & AngleW, const float & PosX, const float & PosY, const float & PosZ)  	{
		::Proud::CMessage __msg;
__msg.UseInternalBuffer();
__msg.SetSimplePacketMode(m_core->IsSimplePacketMode());

::Proud::RmiID __msgid=(::Proud::RmiID)Rmi_ActorTransformUpdated;
__msg.Write(__msgid); 
	
__msg << templeteID;
__msg << ScaleX;
__msg << ScaleY;
__msg << ScaleZ;
__msg << AngleX;
__msg << AngleY;
__msg << AngleZ;
__msg << AngleW;
__msg << PosX;
__msg << PosY;
__msg << PosZ;
		
		return RmiSend(remotes,remoteCount,rmiContext,__msg,
			RmiName_ActorTransformUpdated, (::Proud::RmiID)Rmi_ActorTransformUpdated);
	}
        
	bool Proxy::UpdateCharacterAnimState ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & clientId, const int & AnimSate, const float & Time)	{
		::Proud::CMessage __msg;
__msg.UseInternalBuffer();
__msg.SetSimplePacketMode(m_core->IsSimplePacketMode());

::Proud::RmiID __msgid=(::Proud::RmiID)Rmi_UpdateCharacterAnimState;
__msg.Write(__msgid); 
	
__msg << clientId;
__msg << AnimSate;
__msg << Time;
		
		return RmiSend(&remote,1,rmiContext,__msg,
			RmiName_UpdateCharacterAnimState, (::Proud::RmiID)Rmi_UpdateCharacterAnimState);
	}

	bool Proxy::UpdateCharacterAnimState ( ::Proud::HostID *remotes, int remoteCount, ::Proud::RmiContext &rmiContext, const int & clientId, const int & AnimSate, const float & Time)  	{
		::Proud::CMessage __msg;
__msg.UseInternalBuffer();
__msg.SetSimplePacketMode(m_core->IsSimplePacketMode());

::Proud::RmiID __msgid=(::Proud::RmiID)Rmi_UpdateCharacterAnimState;
__msg.Write(__msgid); 
	
__msg << clientId;
__msg << AnimSate;
__msg << Time;
		
		return RmiSend(remotes,remoteCount,rmiContext,__msg,
			RmiName_UpdateCharacterAnimState, (::Proud::RmiID)Rmi_UpdateCharacterAnimState);
	}
        
	bool Proxy::OnOtherPlayerAnimUpdated ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & ClientID, const int & AnimState, const int & AnimTime)	{
		::Proud::CMessage __msg;
__msg.UseInternalBuffer();
__msg.SetSimplePacketMode(m_core->IsSimplePacketMode());

::Proud::RmiID __msgid=(::Proud::RmiID)Rmi_OnOtherPlayerAnimUpdated;
__msg.Write(__msgid); 
	
__msg << ClientID;
__msg << AnimState;
__msg << AnimTime;
		
		return RmiSend(&remote,1,rmiContext,__msg,
			RmiName_OnOtherPlayerAnimUpdated, (::Proud::RmiID)Rmi_OnOtherPlayerAnimUpdated);
	}

	bool Proxy::OnOtherPlayerAnimUpdated ( ::Proud::HostID *remotes, int remoteCount, ::Proud::RmiContext &rmiContext, const int & ClientID, const int & AnimState, const int & AnimTime)  	{
		::Proud::CMessage __msg;
__msg.UseInternalBuffer();
__msg.SetSimplePacketMode(m_core->IsSimplePacketMode());

::Proud::RmiID __msgid=(::Proud::RmiID)Rmi_OnOtherPlayerAnimUpdated;
__msg.Write(__msgid); 
	
__msg << ClientID;
__msg << AnimState;
__msg << AnimTime;
		
		return RmiSend(remotes,remoteCount,rmiContext,__msg,
			RmiName_OnOtherPlayerAnimUpdated, (::Proud::RmiID)Rmi_OnOtherPlayerAnimUpdated);
	}
        
	bool Proxy::UpdateActorAnimState ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & templeteID, const int & AnimSate, const float & Time)	{
		::Proud::CMessage __msg;
__msg.UseInternalBuffer();
__msg.SetSimplePacketMode(m_core->IsSimplePacketMode());

::Proud::RmiID __msgid=(::Proud::RmiID)Rmi_UpdateActorAnimState;
__msg.Write(__msgid); 
	
__msg << templeteID;
__msg << AnimSate;
__msg << Time;
		
		return RmiSend(&remote,1,rmiContext,__msg,
			RmiName_UpdateActorAnimState, (::Proud::RmiID)Rmi_UpdateActorAnimState);
	}

	bool Proxy::UpdateActorAnimState ( ::Proud::HostID *remotes, int remoteCount, ::Proud::RmiContext &rmiContext, const int & templeteID, const int & AnimSate, const float & Time)  	{
		::Proud::CMessage __msg;
__msg.UseInternalBuffer();
__msg.SetSimplePacketMode(m_core->IsSimplePacketMode());

::Proud::RmiID __msgid=(::Proud::RmiID)Rmi_UpdateActorAnimState;
__msg.Write(__msgid); 
	
__msg << templeteID;
__msg << AnimSate;
__msg << Time;
		
		return RmiSend(remotes,remoteCount,rmiContext,__msg,
			RmiName_UpdateActorAnimState, (::Proud::RmiID)Rmi_UpdateActorAnimState);
	}
        
	bool Proxy::OnOtherActorAnimUpdated ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & templeteID, const int & AnimState, const int & AnimTime)	{
		::Proud::CMessage __msg;
__msg.UseInternalBuffer();
__msg.SetSimplePacketMode(m_core->IsSimplePacketMode());

::Proud::RmiID __msgid=(::Proud::RmiID)Rmi_OnOtherActorAnimUpdated;
__msg.Write(__msgid); 
	
__msg << templeteID;
__msg << AnimState;
__msg << AnimTime;
		
		return RmiSend(&remote,1,rmiContext,__msg,
			RmiName_OnOtherActorAnimUpdated, (::Proud::RmiID)Rmi_OnOtherActorAnimUpdated);
	}

	bool Proxy::OnOtherActorAnimUpdated ( ::Proud::HostID *remotes, int remoteCount, ::Proud::RmiContext &rmiContext, const int & templeteID, const int & AnimState, const int & AnimTime)  	{
		::Proud::CMessage __msg;
__msg.UseInternalBuffer();
__msg.SetSimplePacketMode(m_core->IsSimplePacketMode());

::Proud::RmiID __msgid=(::Proud::RmiID)Rmi_OnOtherActorAnimUpdated;
__msg.Write(__msgid); 
	
__msg << templeteID;
__msg << AnimState;
__msg << AnimTime;
		
		return RmiSend(remotes,remoteCount,rmiContext,__msg,
			RmiName_OnOtherActorAnimUpdated, (::Proud::RmiID)Rmi_OnOtherActorAnimUpdated);
	}
        
	bool Proxy::Response_UpdateSlot ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & iClientID, const int & iSlotID, const int & iItemID, const int & iItemCount)	{
		::Proud::CMessage __msg;
__msg.UseInternalBuffer();
__msg.SetSimplePacketMode(m_core->IsSimplePacketMode());

::Proud::RmiID __msgid=(::Proud::RmiID)Rmi_Response_UpdateSlot;
__msg.Write(__msgid); 
	
__msg << iClientID;
__msg << iSlotID;
__msg << iItemID;
__msg << iItemCount;
		
		return RmiSend(&remote,1,rmiContext,__msg,
			RmiName_Response_UpdateSlot, (::Proud::RmiID)Rmi_Response_UpdateSlot);
	}

	bool Proxy::Response_UpdateSlot ( ::Proud::HostID *remotes, int remoteCount, ::Proud::RmiContext &rmiContext, const int & iClientID, const int & iSlotID, const int & iItemID, const int & iItemCount)  	{
		::Proud::CMessage __msg;
__msg.UseInternalBuffer();
__msg.SetSimplePacketMode(m_core->IsSimplePacketMode());

::Proud::RmiID __msgid=(::Proud::RmiID)Rmi_Response_UpdateSlot;
__msg.Write(__msgid); 
	
__msg << iClientID;
__msg << iSlotID;
__msg << iItemID;
__msg << iItemCount;
		
		return RmiSend(remotes,remoteCount,rmiContext,__msg,
			RmiName_Response_UpdateSlot, (::Proud::RmiID)Rmi_Response_UpdateSlot);
	}
        
	bool Proxy::Response_Gold ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & ClientID, const int & Gold)	{
		::Proud::CMessage __msg;
__msg.UseInternalBuffer();
__msg.SetSimplePacketMode(m_core->IsSimplePacketMode());

::Proud::RmiID __msgid=(::Proud::RmiID)Rmi_Response_Gold;
__msg.Write(__msgid); 
	
__msg << ClientID;
__msg << Gold;
		
		return RmiSend(&remote,1,rmiContext,__msg,
			RmiName_Response_Gold, (::Proud::RmiID)Rmi_Response_Gold);
	}

	bool Proxy::Response_Gold ( ::Proud::HostID *remotes, int remoteCount, ::Proud::RmiContext &rmiContext, const int & ClientID, const int & Gold)  	{
		::Proud::CMessage __msg;
__msg.UseInternalBuffer();
__msg.SetSimplePacketMode(m_core->IsSimplePacketMode());

::Proud::RmiID __msgid=(::Proud::RmiID)Rmi_Response_Gold;
__msg.Write(__msgid); 
	
__msg << ClientID;
__msg << Gold;
		
		return RmiSend(remotes,remoteCount,rmiContext,__msg,
			RmiName_Response_Gold, (::Proud::RmiID)Rmi_Response_Gold);
	}
        
	bool Proxy::OnChat ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & clientId, const string & message)	{
		::Proud::CMessage __msg;
__msg.UseInternalBuffer();
__msg.SetSimplePacketMode(m_core->IsSimplePacketMode());

::Proud::RmiID __msgid=(::Proud::RmiID)Rmi_OnChat;
__msg.Write(__msgid); 
	
__msg << clientId;
__msg << message;
		
		return RmiSend(&remote,1,rmiContext,__msg,
			RmiName_OnChat, (::Proud::RmiID)Rmi_OnChat);
	}

	bool Proxy::OnChat ( ::Proud::HostID *remotes, int remoteCount, ::Proud::RmiContext &rmiContext, const int & clientId, const string & message)  	{
		::Proud::CMessage __msg;
__msg.UseInternalBuffer();
__msg.SetSimplePacketMode(m_core->IsSimplePacketMode());

::Proud::RmiID __msgid=(::Proud::RmiID)Rmi_OnChat;
__msg.Write(__msgid); 
	
__msg << clientId;
__msg << message;
		
		return RmiSend(remotes,remoteCount,rmiContext,__msg,
			RmiName_OnChat, (::Proud::RmiID)Rmi_OnChat);
	}
#ifdef USE_RMI_NAME_STRING
const PNTCHAR* Proxy::RmiName_ResponseLoginEvent =_PNT("ResponseLoginEvent");
#else
const PNTCHAR* Proxy::RmiName_ResponseLoginEvent =_PNT("");
#endif
#ifdef USE_RMI_NAME_STRING
const PNTCHAR* Proxy::RmiName_ResponseCheckNickname =_PNT("ResponseCheckNickname");
#else
const PNTCHAR* Proxy::RmiName_ResponseCheckNickname =_PNT("");
#endif
#ifdef USE_RMI_NAME_STRING
const PNTCHAR* Proxy::RmiName_OnPlayerJoined =_PNT("OnPlayerJoined");
#else
const PNTCHAR* Proxy::RmiName_OnPlayerJoined =_PNT("");
#endif
#ifdef USE_RMI_NAME_STRING
const PNTCHAR* Proxy::RmiName_SpawnObjectEvent =_PNT("SpawnObjectEvent");
#else
const PNTCHAR* Proxy::RmiName_SpawnObjectEvent =_PNT("");
#endif
#ifdef USE_RMI_NAME_STRING
const PNTCHAR* Proxy::RmiName_OtherPlayerTransformUpdated =_PNT("OtherPlayerTransformUpdated");
#else
const PNTCHAR* Proxy::RmiName_OtherPlayerTransformUpdated =_PNT("");
#endif
#ifdef USE_RMI_NAME_STRING
const PNTCHAR* Proxy::RmiName_OnPlayerTransformUpdated =_PNT("OnPlayerTransformUpdated");
#else
const PNTCHAR* Proxy::RmiName_OnPlayerTransformUpdated =_PNT("");
#endif
#ifdef USE_RMI_NAME_STRING
const PNTCHAR* Proxy::RmiName_OtherActorTransformUpdated =_PNT("OtherActorTransformUpdated");
#else
const PNTCHAR* Proxy::RmiName_OtherActorTransformUpdated =_PNT("");
#endif
#ifdef USE_RMI_NAME_STRING
const PNTCHAR* Proxy::RmiName_ActorTransformUpdated =_PNT("ActorTransformUpdated");
#else
const PNTCHAR* Proxy::RmiName_ActorTransformUpdated =_PNT("");
#endif
#ifdef USE_RMI_NAME_STRING
const PNTCHAR* Proxy::RmiName_UpdateCharacterAnimState =_PNT("UpdateCharacterAnimState");
#else
const PNTCHAR* Proxy::RmiName_UpdateCharacterAnimState =_PNT("");
#endif
#ifdef USE_RMI_NAME_STRING
const PNTCHAR* Proxy::RmiName_OnOtherPlayerAnimUpdated =_PNT("OnOtherPlayerAnimUpdated");
#else
const PNTCHAR* Proxy::RmiName_OnOtherPlayerAnimUpdated =_PNT("");
#endif
#ifdef USE_RMI_NAME_STRING
const PNTCHAR* Proxy::RmiName_UpdateActorAnimState =_PNT("UpdateActorAnimState");
#else
const PNTCHAR* Proxy::RmiName_UpdateActorAnimState =_PNT("");
#endif
#ifdef USE_RMI_NAME_STRING
const PNTCHAR* Proxy::RmiName_OnOtherActorAnimUpdated =_PNT("OnOtherActorAnimUpdated");
#else
const PNTCHAR* Proxy::RmiName_OnOtherActorAnimUpdated =_PNT("");
#endif
#ifdef USE_RMI_NAME_STRING
const PNTCHAR* Proxy::RmiName_Response_UpdateSlot =_PNT("Response_UpdateSlot");
#else
const PNTCHAR* Proxy::RmiName_Response_UpdateSlot =_PNT("");
#endif
#ifdef USE_RMI_NAME_STRING
const PNTCHAR* Proxy::RmiName_Response_Gold =_PNT("Response_Gold");
#else
const PNTCHAR* Proxy::RmiName_Response_Gold =_PNT("");
#endif
#ifdef USE_RMI_NAME_STRING
const PNTCHAR* Proxy::RmiName_OnChat =_PNT("OnChat");
#else
const PNTCHAR* Proxy::RmiName_OnChat =_PNT("");
#endif
const PNTCHAR* Proxy::RmiName_First = RmiName_ResponseLoginEvent;

}



