
// Generated by PIDL compiler.
// Do not modify this file, but modify the source .pidl file.

#include "pch.h"
#include "ServerRmi_common.h"
namespace ServerToClient {


	::Proud::RmiID g_RmiIDList[] = {
               
		Rmi_OnPlayerJoined,
               
		Rmi_OnOtherPlayerUpdated,
               
		Rmi_OnPositionUpdated,
               
		Rmi_UpdateCharacterAnimState,
               
		Rmi_ResponseCheckNickname,
               
		Rmi_OnChat,
	};

	int g_RmiIDListCount = 6;

}





