




// Generated by PIDL compiler.
// Do not modify this file, but modify the source .pidl file.

#include "pch.h"
#include "ServerRmi_proxy.h"

namespace ServerToClient {


        
	bool Proxy::OnPlayerJoined ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & clientId, const string & szNickName, const float & PosX, const float & PosY, const float & PosZ)	{
		::Proud::CMessage __msg;
__msg.UseInternalBuffer();
__msg.SetSimplePacketMode(m_core->IsSimplePacketMode());

::Proud::RmiID __msgid=(::Proud::RmiID)Rmi_OnPlayerJoined;
__msg.Write(__msgid); 
	
__msg << clientId;
__msg << szNickName;
__msg << PosX;
__msg << PosY;
__msg << PosZ;
		
		return RmiSend(&remote,1,rmiContext,__msg,
			RmiName_OnPlayerJoined, (::Proud::RmiID)Rmi_OnPlayerJoined);
	}

	bool Proxy::OnPlayerJoined ( ::Proud::HostID *remotes, int remoteCount, ::Proud::RmiContext &rmiContext, const int & clientId, const string & szNickName, const float & PosX, const float & PosY, const float & PosZ)  	{
		::Proud::CMessage __msg;
__msg.UseInternalBuffer();
__msg.SetSimplePacketMode(m_core->IsSimplePacketMode());

::Proud::RmiID __msgid=(::Proud::RmiID)Rmi_OnPlayerJoined;
__msg.Write(__msgid); 
	
__msg << clientId;
__msg << szNickName;
__msg << PosX;
__msg << PosY;
__msg << PosZ;
		
		return RmiSend(remotes,remoteCount,rmiContext,__msg,
			RmiName_OnPlayerJoined, (::Proud::RmiID)Rmi_OnPlayerJoined);
	}
        
	bool Proxy::OnOtherPlayerUpdated ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & ClientID, const string & NickName, const float & PosX, const float & PosY, const float & PosZ)	{
		::Proud::CMessage __msg;
__msg.UseInternalBuffer();
__msg.SetSimplePacketMode(m_core->IsSimplePacketMode());

::Proud::RmiID __msgid=(::Proud::RmiID)Rmi_OnOtherPlayerUpdated;
__msg.Write(__msgid); 
	
__msg << ClientID;
__msg << NickName;
__msg << PosX;
__msg << PosY;
__msg << PosZ;
		
		return RmiSend(&remote,1,rmiContext,__msg,
			RmiName_OnOtherPlayerUpdated, (::Proud::RmiID)Rmi_OnOtherPlayerUpdated);
	}

	bool Proxy::OnOtherPlayerUpdated ( ::Proud::HostID *remotes, int remoteCount, ::Proud::RmiContext &rmiContext, const int & ClientID, const string & NickName, const float & PosX, const float & PosY, const float & PosZ)  	{
		::Proud::CMessage __msg;
__msg.UseInternalBuffer();
__msg.SetSimplePacketMode(m_core->IsSimplePacketMode());

::Proud::RmiID __msgid=(::Proud::RmiID)Rmi_OnOtherPlayerUpdated;
__msg.Write(__msgid); 
	
__msg << ClientID;
__msg << NickName;
__msg << PosX;
__msg << PosY;
__msg << PosZ;
		
		return RmiSend(remotes,remoteCount,rmiContext,__msg,
			RmiName_OnOtherPlayerUpdated, (::Proud::RmiID)Rmi_OnOtherPlayerUpdated);
	}
        
	bool Proxy::OnPositionUpdated ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & clientId, const float & PosX, const float & PosY, const float & PosZ, const float & DirX, const float & DirY, const float & DirZ)	{
		::Proud::CMessage __msg;
__msg.UseInternalBuffer();
__msg.SetSimplePacketMode(m_core->IsSimplePacketMode());

::Proud::RmiID __msgid=(::Proud::RmiID)Rmi_OnPositionUpdated;
__msg.Write(__msgid); 
	
__msg << clientId;
__msg << PosX;
__msg << PosY;
__msg << PosZ;
__msg << DirX;
__msg << DirY;
__msg << DirZ;
		
		return RmiSend(&remote,1,rmiContext,__msg,
			RmiName_OnPositionUpdated, (::Proud::RmiID)Rmi_OnPositionUpdated);
	}

	bool Proxy::OnPositionUpdated ( ::Proud::HostID *remotes, int remoteCount, ::Proud::RmiContext &rmiContext, const int & clientId, const float & PosX, const float & PosY, const float & PosZ, const float & DirX, const float & DirY, const float & DirZ)  	{
		::Proud::CMessage __msg;
__msg.UseInternalBuffer();
__msg.SetSimplePacketMode(m_core->IsSimplePacketMode());

::Proud::RmiID __msgid=(::Proud::RmiID)Rmi_OnPositionUpdated;
__msg.Write(__msgid); 
	
__msg << clientId;
__msg << PosX;
__msg << PosY;
__msg << PosZ;
__msg << DirX;
__msg << DirY;
__msg << DirZ;
		
		return RmiSend(remotes,remoteCount,rmiContext,__msg,
			RmiName_OnPositionUpdated, (::Proud::RmiID)Rmi_OnPositionUpdated);
	}
        
	bool Proxy::UpdateCharacterAnimState ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & clientId, const int & AnimSate, const float & Time)	{
		::Proud::CMessage __msg;
__msg.UseInternalBuffer();
__msg.SetSimplePacketMode(m_core->IsSimplePacketMode());

::Proud::RmiID __msgid=(::Proud::RmiID)Rmi_UpdateCharacterAnimState;
__msg.Write(__msgid); 
	
__msg << clientId;
__msg << AnimSate;
__msg << Time;
		
		return RmiSend(&remote,1,rmiContext,__msg,
			RmiName_UpdateCharacterAnimState, (::Proud::RmiID)Rmi_UpdateCharacterAnimState);
	}

	bool Proxy::UpdateCharacterAnimState ( ::Proud::HostID *remotes, int remoteCount, ::Proud::RmiContext &rmiContext, const int & clientId, const int & AnimSate, const float & Time)  	{
		::Proud::CMessage __msg;
__msg.UseInternalBuffer();
__msg.SetSimplePacketMode(m_core->IsSimplePacketMode());

::Proud::RmiID __msgid=(::Proud::RmiID)Rmi_UpdateCharacterAnimState;
__msg.Write(__msgid); 
	
__msg << clientId;
__msg << AnimSate;
__msg << Time;
		
		return RmiSend(remotes,remoteCount,rmiContext,__msg,
			RmiName_UpdateCharacterAnimState, (::Proud::RmiID)Rmi_UpdateCharacterAnimState);
	}
        
	bool Proxy::ResponseCheckNickname ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & clientId, const bool & bIsAble)	{
		::Proud::CMessage __msg;
__msg.UseInternalBuffer();
__msg.SetSimplePacketMode(m_core->IsSimplePacketMode());

::Proud::RmiID __msgid=(::Proud::RmiID)Rmi_ResponseCheckNickname;
__msg.Write(__msgid); 
	
__msg << clientId;
__msg << bIsAble;
		
		return RmiSend(&remote,1,rmiContext,__msg,
			RmiName_ResponseCheckNickname, (::Proud::RmiID)Rmi_ResponseCheckNickname);
	}

	bool Proxy::ResponseCheckNickname ( ::Proud::HostID *remotes, int remoteCount, ::Proud::RmiContext &rmiContext, const int & clientId, const bool & bIsAble)  	{
		::Proud::CMessage __msg;
__msg.UseInternalBuffer();
__msg.SetSimplePacketMode(m_core->IsSimplePacketMode());

::Proud::RmiID __msgid=(::Proud::RmiID)Rmi_ResponseCheckNickname;
__msg.Write(__msgid); 
	
__msg << clientId;
__msg << bIsAble;
		
		return RmiSend(remotes,remoteCount,rmiContext,__msg,
			RmiName_ResponseCheckNickname, (::Proud::RmiID)Rmi_ResponseCheckNickname);
	}
        
	bool Proxy::OnChat ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const int & clientId, const string & message)	{
		::Proud::CMessage __msg;
__msg.UseInternalBuffer();
__msg.SetSimplePacketMode(m_core->IsSimplePacketMode());

::Proud::RmiID __msgid=(::Proud::RmiID)Rmi_OnChat;
__msg.Write(__msgid); 
	
__msg << clientId;
__msg << message;
		
		return RmiSend(&remote,1,rmiContext,__msg,
			RmiName_OnChat, (::Proud::RmiID)Rmi_OnChat);
	}

	bool Proxy::OnChat ( ::Proud::HostID *remotes, int remoteCount, ::Proud::RmiContext &rmiContext, const int & clientId, const string & message)  	{
		::Proud::CMessage __msg;
__msg.UseInternalBuffer();
__msg.SetSimplePacketMode(m_core->IsSimplePacketMode());

::Proud::RmiID __msgid=(::Proud::RmiID)Rmi_OnChat;
__msg.Write(__msgid); 
	
__msg << clientId;
__msg << message;
		
		return RmiSend(remotes,remoteCount,rmiContext,__msg,
			RmiName_OnChat, (::Proud::RmiID)Rmi_OnChat);
	}
#ifdef USE_RMI_NAME_STRING
const PNTCHAR* Proxy::RmiName_OnPlayerJoined =_PNT("OnPlayerJoined");
#else
const PNTCHAR* Proxy::RmiName_OnPlayerJoined =_PNT("");
#endif
#ifdef USE_RMI_NAME_STRING
const PNTCHAR* Proxy::RmiName_OnOtherPlayerUpdated =_PNT("OnOtherPlayerUpdated");
#else
const PNTCHAR* Proxy::RmiName_OnOtherPlayerUpdated =_PNT("");
#endif
#ifdef USE_RMI_NAME_STRING
const PNTCHAR* Proxy::RmiName_OnPositionUpdated =_PNT("OnPositionUpdated");
#else
const PNTCHAR* Proxy::RmiName_OnPositionUpdated =_PNT("");
#endif
#ifdef USE_RMI_NAME_STRING
const PNTCHAR* Proxy::RmiName_UpdateCharacterAnimState =_PNT("UpdateCharacterAnimState");
#else
const PNTCHAR* Proxy::RmiName_UpdateCharacterAnimState =_PNT("");
#endif
#ifdef USE_RMI_NAME_STRING
const PNTCHAR* Proxy::RmiName_ResponseCheckNickname =_PNT("ResponseCheckNickname");
#else
const PNTCHAR* Proxy::RmiName_ResponseCheckNickname =_PNT("");
#endif
#ifdef USE_RMI_NAME_STRING
const PNTCHAR* Proxy::RmiName_OnChat =_PNT("OnChat");
#else
const PNTCHAR* Proxy::RmiName_OnChat =_PNT("");
#endif
const PNTCHAR* Proxy::RmiName_First = RmiName_OnPlayerJoined;

}



