




// Generated by PIDL compiler.
// Do not modify this file, but modify the source .pidl file.

using System;
using System.Net;

namespace ClientToServer
{
	internal class Proxy:Nettention.Proud.RmiProxy
	{
public bool OnPositionUpdated(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, int clientId, float PosX, float PosY, float PosZ, float DirX, float DirY, float DirZ)
{
	using (Nettention.Proud.FreeListPopper<Nettention.Proud.Message> freeList = new Nettention.Proud.FreeListPopper<Nettention.Proud.Message>())
		{
		Nettention.Proud.Message __msg=freeList.GetObject();
		__msg.Clear();
		__msg.SimplePacketMode = core.IsSimplePacketMode();
		Nettention.Proud.RmiID __msgid= Common.OnPositionUpdated;
		__msg.Write(__msgid);
		Nettention.Proud.Marshaler.Write(__msg, clientId);
		Nettention.Proud.Marshaler.Write(__msg, PosX);
		Nettention.Proud.Marshaler.Write(__msg, PosY);
		Nettention.Proud.Marshaler.Write(__msg, PosZ);
		Nettention.Proud.Marshaler.Write(__msg, DirX);
		Nettention.Proud.Marshaler.Write(__msg, DirY);
		Nettention.Proud.Marshaler.Write(__msg, DirZ);
		
	Nettention.Proud.HostID[] __list = new Nettention.Proud.HostID[1];
	__list[0] = remote;
		
	return RmiSend(__list,rmiContext,__msg,
		RmiName_OnPositionUpdated, Common.OnPositionUpdated);
        }
}

public bool OnPositionUpdated(Nettention.Proud.HostID[] remotes,Nettention.Proud.RmiContext rmiContext, int clientId, float PosX, float PosY, float PosZ, float DirX, float DirY, float DirZ)
{
	using (Nettention.Proud.FreeListPopper<Nettention.Proud.Message> freeList = new Nettention.Proud.FreeListPopper<Nettention.Proud.Message>())
{
Nettention.Proud.Message __msg=freeList.GetObject();
__msg.Clear();
__msg.SimplePacketMode = core.IsSimplePacketMode();
Nettention.Proud.RmiID __msgid= Common.OnPositionUpdated;
__msg.Write(__msgid);
Nettention.Proud.Marshaler.Write(__msg, clientId);
Nettention.Proud.Marshaler.Write(__msg, PosX);
Nettention.Proud.Marshaler.Write(__msg, PosY);
Nettention.Proud.Marshaler.Write(__msg, PosZ);
Nettention.Proud.Marshaler.Write(__msg, DirX);
Nettention.Proud.Marshaler.Write(__msg, DirY);
Nettention.Proud.Marshaler.Write(__msg, DirZ);
		
	return RmiSend(remotes,rmiContext,__msg,
		RmiName_OnPositionUpdated, Common.OnPositionUpdated);
        }
}
public bool OnChat(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, int clientId, string message)
{
	using (Nettention.Proud.FreeListPopper<Nettention.Proud.Message> freeList = new Nettention.Proud.FreeListPopper<Nettention.Proud.Message>())
		{
		Nettention.Proud.Message __msg=freeList.GetObject();
		__msg.Clear();
		__msg.SimplePacketMode = core.IsSimplePacketMode();
		Nettention.Proud.RmiID __msgid= Common.OnChat;
		__msg.Write(__msgid);
		Nettention.Proud.Marshaler.Write(__msg, clientId);
		Nettention.Proud.Marshaler.Write(__msg, message);
		
	Nettention.Proud.HostID[] __list = new Nettention.Proud.HostID[1];
	__list[0] = remote;
		
	return RmiSend(__list,rmiContext,__msg,
		RmiName_OnChat, Common.OnChat);
        }
}

public bool OnChat(Nettention.Proud.HostID[] remotes,Nettention.Proud.RmiContext rmiContext, int clientId, string message)
{
	using (Nettention.Proud.FreeListPopper<Nettention.Proud.Message> freeList = new Nettention.Proud.FreeListPopper<Nettention.Proud.Message>())
{
Nettention.Proud.Message __msg=freeList.GetObject();
__msg.Clear();
__msg.SimplePacketMode = core.IsSimplePacketMode();
Nettention.Proud.RmiID __msgid= Common.OnChat;
__msg.Write(__msgid);
Nettention.Proud.Marshaler.Write(__msg, clientId);
Nettention.Proud.Marshaler.Write(__msg, message);
		
	return RmiSend(remotes,rmiContext,__msg,
		RmiName_OnChat, Common.OnChat);
        }
}
	
		#if USE_RMI_NAME_STRING
// RMI name declaration.
// It is the unique pointer that indicates RMI name such as RMI profiler.
public const string RmiName_OnPositionUpdated="OnPositionUpdated";
public const string RmiName_OnChat="OnChat";
       
public const string RmiName_First = RmiName_OnPositionUpdated;
		#else
// RMI name declaration.
// It is the unique pointer that indicates RMI name such as RMI profiler.
public const string RmiName_OnPositionUpdated="";
public const string RmiName_OnChat="";
       
public const string RmiName_First = "";
		#endif

		public override Nettention.Proud.RmiID[] GetRmiIDList() { return Common.RmiIDList; } 
	}
}

