




// Generated by PIDL compiler.
// Do not modify this file, but modify the source .pidl file.

using System;
using System.Net;	     

namespace ServerToClient
{
	internal class Stub:Nettention.Proud.RmiStub
	{
public AfterRmiInvocationDelegate AfterRmiInvocation = delegate(Nettention.Proud.AfterRmiSummary summary) {};
public BeforeRmiInvocationDelegate BeforeRmiInvocation = delegate(Nettention.Proud.BeforeRmiSummary summary) {};

		public delegate bool OnPlayerJoinedDelegate(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, int clientId, float PosX, float PosY, float PosZ);  
		public OnPlayerJoinedDelegate OnPlayerJoined = delegate(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, int clientId, float PosX, float PosY, float PosZ)
		{ 
			return false;
		};
		public delegate bool OnPositionUpdatedDelegate(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, int clientId, float PosX, float PosY, float PosZ, float DirX, float DirY, float DirZ);  
		public OnPositionUpdatedDelegate OnPositionUpdated = delegate(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, int clientId, float PosX, float PosY, float PosZ, float DirX, float DirY, float DirZ)
		{ 
			return false;
		};
		public delegate bool OnChatDelegate(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, int clientId, string message);  
		public OnChatDelegate OnChat = delegate(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, int clientId, string message)
		{ 
			return false;
		};
	public override bool ProcessReceivedMessage(Nettention.Proud.ReceivedMessage pa, Object hostTag) 
	{
		Nettention.Proud.HostID remote=pa.RemoteHostID;
		if(remote==Nettention.Proud.HostID.HostID_None)
		{
			ShowUnknownHostIDWarning(remote);
		}

		Nettention.Proud.Message __msg=pa.ReadOnlyMessage;
		int orgReadOffset = __msg.ReadOffset;
        Nettention.Proud.RmiID __rmiID = Nettention.Proud.RmiID.RmiID_None;
        if (!__msg.Read( out __rmiID))
            goto __fail;
					
		switch(__rmiID)
		{
        case Common.OnPlayerJoined:
            ProcessReceivedMessage_OnPlayerJoined(__msg, pa, hostTag, remote);
            break;
        case Common.OnPositionUpdated:
            ProcessReceivedMessage_OnPositionUpdated(__msg, pa, hostTag, remote);
            break;
        case Common.OnChat:
            ProcessReceivedMessage_OnChat(__msg, pa, hostTag, remote);
            break;
		default:
			 goto __fail;
		}
		return true;
__fail:
	  {
			__msg.ReadOffset = orgReadOffset;
			return false;
	  }
	}
    void ProcessReceivedMessage_OnPlayerJoined(Nettention.Proud.Message __msg, Nettention.Proud.ReceivedMessage pa, Object hostTag, Nettention.Proud.HostID remote)
    {
        Nettention.Proud.RmiContext ctx = new Nettention.Proud.RmiContext();
        ctx.sentFrom=pa.RemoteHostID;
        ctx.relayed=pa.IsRelayed;
        ctx.hostTag=hostTag;
        ctx.encryptMode = pa.EncryptMode;
        ctx.compressMode = pa.CompressMode;
        ctx.rmiID = Common.OnPlayerJoined;

        int clientId; Nettention.Proud.Marshaler.Read(__msg,out clientId);	
float PosX; Nettention.Proud.Marshaler.Read(__msg,out PosX);	
float PosY; Nettention.Proud.Marshaler.Read(__msg,out PosY);	
float PosZ; Nettention.Proud.Marshaler.Read(__msg,out PosZ);	
core.PostCheckReadMessage(__msg, RmiName_OnPlayerJoined);
        if(enableNotifyCallFromStub==true)
        {
        string parameterString = "";
        parameterString+=clientId.ToString()+",";
parameterString+=PosX.ToString()+",";
parameterString+=PosY.ToString()+",";
parameterString+=PosZ.ToString()+",";
        NotifyCallFromStub(Common.OnPlayerJoined, RmiName_OnPlayerJoined,parameterString);
        }

        if(enableStubProfiling)
        {
        Nettention.Proud.BeforeRmiSummary summary = new Nettention.Proud.BeforeRmiSummary();
        summary.rmiID = Common.OnPlayerJoined;
        summary.rmiName = RmiName_OnPlayerJoined;
        summary.hostID = remote;
        summary.hostTag = hostTag;
        BeforeRmiInvocation(summary);
        }

        long t0 = Nettention.Proud.PreciseCurrentTime.GetTimeMs();

        // Call this method.
        bool __ret =OnPlayerJoined (remote,ctx , clientId, PosX, PosY, PosZ );

        if(__ret==false)
        {
        // Error: RMI function that a user did not create has been called. 
        core.ShowNotImplementedRmiWarning(RmiName_OnPlayerJoined);
        }

        if(enableStubProfiling)
        {
        Nettention.Proud.AfterRmiSummary summary = new Nettention.Proud.AfterRmiSummary();
        summary.rmiID = Common.OnPlayerJoined;
        summary.rmiName = RmiName_OnPlayerJoined;
        summary.hostID = remote;
        summary.hostTag = hostTag;
        summary.elapsedTime = Nettention.Proud.PreciseCurrentTime.GetTimeMs()-t0;
        AfterRmiInvocation(summary);
        }
    }
    void ProcessReceivedMessage_OnPositionUpdated(Nettention.Proud.Message __msg, Nettention.Proud.ReceivedMessage pa, Object hostTag, Nettention.Proud.HostID remote)
    {
        Nettention.Proud.RmiContext ctx = new Nettention.Proud.RmiContext();
        ctx.sentFrom=pa.RemoteHostID;
        ctx.relayed=pa.IsRelayed;
        ctx.hostTag=hostTag;
        ctx.encryptMode = pa.EncryptMode;
        ctx.compressMode = pa.CompressMode;
        ctx.rmiID = Common.OnPositionUpdated;

        int clientId; Nettention.Proud.Marshaler.Read(__msg,out clientId);	
float PosX; Nettention.Proud.Marshaler.Read(__msg,out PosX);	
float PosY; Nettention.Proud.Marshaler.Read(__msg,out PosY);	
float PosZ; Nettention.Proud.Marshaler.Read(__msg,out PosZ);	
float DirX; Nettention.Proud.Marshaler.Read(__msg,out DirX);	
float DirY; Nettention.Proud.Marshaler.Read(__msg,out DirY);	
float DirZ; Nettention.Proud.Marshaler.Read(__msg,out DirZ);	
core.PostCheckReadMessage(__msg, RmiName_OnPositionUpdated);
        if(enableNotifyCallFromStub==true)
        {
        string parameterString = "";
        parameterString+=clientId.ToString()+",";
parameterString+=PosX.ToString()+",";
parameterString+=PosY.ToString()+",";
parameterString+=PosZ.ToString()+",";
parameterString+=DirX.ToString()+",";
parameterString+=DirY.ToString()+",";
parameterString+=DirZ.ToString()+",";
        NotifyCallFromStub(Common.OnPositionUpdated, RmiName_OnPositionUpdated,parameterString);
        }

        if(enableStubProfiling)
        {
        Nettention.Proud.BeforeRmiSummary summary = new Nettention.Proud.BeforeRmiSummary();
        summary.rmiID = Common.OnPositionUpdated;
        summary.rmiName = RmiName_OnPositionUpdated;
        summary.hostID = remote;
        summary.hostTag = hostTag;
        BeforeRmiInvocation(summary);
        }

        long t0 = Nettention.Proud.PreciseCurrentTime.GetTimeMs();

        // Call this method.
        bool __ret =OnPositionUpdated (remote,ctx , clientId, PosX, PosY, PosZ, DirX, DirY, DirZ );

        if(__ret==false)
        {
        // Error: RMI function that a user did not create has been called. 
        core.ShowNotImplementedRmiWarning(RmiName_OnPositionUpdated);
        }

        if(enableStubProfiling)
        {
        Nettention.Proud.AfterRmiSummary summary = new Nettention.Proud.AfterRmiSummary();
        summary.rmiID = Common.OnPositionUpdated;
        summary.rmiName = RmiName_OnPositionUpdated;
        summary.hostID = remote;
        summary.hostTag = hostTag;
        summary.elapsedTime = Nettention.Proud.PreciseCurrentTime.GetTimeMs()-t0;
        AfterRmiInvocation(summary);
        }
    }
    void ProcessReceivedMessage_OnChat(Nettention.Proud.Message __msg, Nettention.Proud.ReceivedMessage pa, Object hostTag, Nettention.Proud.HostID remote)
    {
        Nettention.Proud.RmiContext ctx = new Nettention.Proud.RmiContext();
        ctx.sentFrom=pa.RemoteHostID;
        ctx.relayed=pa.IsRelayed;
        ctx.hostTag=hostTag;
        ctx.encryptMode = pa.EncryptMode;
        ctx.compressMode = pa.CompressMode;
        ctx.rmiID = Common.OnChat;

        int clientId; Nettention.Proud.Marshaler.Read(__msg,out clientId);	
string message; Nettention.Proud.Marshaler.Read(__msg,out message);	
core.PostCheckReadMessage(__msg, RmiName_OnChat);
        if(enableNotifyCallFromStub==true)
        {
        string parameterString = "";
        parameterString+=clientId.ToString()+",";
parameterString+=message.ToString()+",";
        NotifyCallFromStub(Common.OnChat, RmiName_OnChat,parameterString);
        }

        if(enableStubProfiling)
        {
        Nettention.Proud.BeforeRmiSummary summary = new Nettention.Proud.BeforeRmiSummary();
        summary.rmiID = Common.OnChat;
        summary.rmiName = RmiName_OnChat;
        summary.hostID = remote;
        summary.hostTag = hostTag;
        BeforeRmiInvocation(summary);
        }

        long t0 = Nettention.Proud.PreciseCurrentTime.GetTimeMs();

        // Call this method.
        bool __ret =OnChat (remote,ctx , clientId, message );

        if(__ret==false)
        {
        // Error: RMI function that a user did not create has been called. 
        core.ShowNotImplementedRmiWarning(RmiName_OnChat);
        }

        if(enableStubProfiling)
        {
        Nettention.Proud.AfterRmiSummary summary = new Nettention.Proud.AfterRmiSummary();
        summary.rmiID = Common.OnChat;
        summary.rmiName = RmiName_OnChat;
        summary.hostID = remote;
        summary.hostTag = hostTag;
        summary.elapsedTime = Nettention.Proud.PreciseCurrentTime.GetTimeMs()-t0;
        AfterRmiInvocation(summary);
        }
    }
		#if USE_RMI_NAME_STRING
// RMI name declaration.
// It is the unique pointer that indicates RMI name such as RMI profiler.
public const string RmiName_OnPlayerJoined="OnPlayerJoined";
public const string RmiName_OnPositionUpdated="OnPositionUpdated";
public const string RmiName_OnChat="OnChat";
       
public const string RmiName_First = RmiName_OnPlayerJoined;
		#else
// RMI name declaration.
// It is the unique pointer that indicates RMI name such as RMI profiler.
public const string RmiName_OnPlayerJoined="";
public const string RmiName_OnPositionUpdated="";
public const string RmiName_OnChat="";
       
public const string RmiName_First = "";
		#endif

		public override Nettention.Proud.RmiID[] GetRmiIDList { get{return Common.RmiIDList;} }
		
	}
}

